### ISSUE TITLE
process space-only variables 

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/PyBaMM#1006]
At the moment `ProcessedVariable` only works if `len(t)>1` (except for the special case of  2D finite elements, which can handle "fixed t" cases). It would be good to set it up so that any variables that are functions of space only can be processed.

**Comment by tinosulzer** [comment]
Yeah would be great to fix that for the solutions of the algebraic solvers too. I had been working around it by giving `[0,1]` as the t_eval for variables that depend only on space.

If we can automatically figure out if the variable was only a function of space, I wonder if we still need to raise that error at all? I guess it might then be hard to figure out that the solver has failed (i.e. hit an event too early) though.

**Comment by rtimms** [comment]
I think it would be good to remove that error. I think it should (hopefully) be obvious to the user if there is only one entry in `t` when they were expecting more? 

Do we need to know if a variable depends on space? As in, you can pass any `t` to evaluate and it will just return the same thing? I think the name I used for this issue is wrong, and what I really meant was fix for `len(solution.t)=1`, in which case you can still evaluate the variable in the same way, but need to create an interpolant of lower dimension.

**Comment by tinosulzer** [comment]
Yes, I think just creating a lower-dimensional interpolant in the case where `len(solution.t)=1` would be appropriate. Maybe the ODE/DAE solvers (i.e. non-algebraic) themselves should raise the error still?

**Comment by rtimms** [comment]
Yeah I think that is the best place to raise that error
