### ISSUE TITLE
Backwards compatibility with other versions of Python3

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#101]

**Comment by fcooper8472** [comment]
This has caused a number of issues.

* Python 3.4: `Could not find a version that satisfies the requirement pandas>=0.23 (from pybamm==0.0.0)`
* Pythons 3.5 and 3.7 fall over on the scikits solvers

I'll look into them, but any immediate ideas @martinjrobins ?

**Comment by tinosulzer** [comment]
AFAIK the pandas version number is arbitrary, everything would probably still work with earlier versions

On 14 Feb 2019 21:09, Fergus Cooper <notifications@github.com> wrote:

This has caused a number of issues.

  *   Python 3.4: Could not find a version that satisfies the requirement pandas>=0.23 (from pybamm==0.0.0)
  *   Pythons 3.5 and 3.7 fall over on the scikits solvers

I'll look into them, but any immediate ideas @martinjrobins<https://github.com/martinjrobins> ?

**Comment by fcooper8472** [comment]
Ok, also looks as though the `@` operator was not introduced until Python 3.5.  Anyone know if you can pull it in in 3.4?

**Comment by tinosulzer** [comment]
looks like `np.dot` has almost the same functionality as long as we don't try to multiply 3D matrices

**Comment by fcooper8472** [comment]
If we're at the point of ditching more modern language features, though: are we serving a big constituency by supporting python 3.4?

I notice that 3.4 is the default python3 on Ubuntu 14.04 LTS, but that reaches end of life in April this year.  Ubuntu 16.04 LTS gives you 3.5 by default.  If you're installing with anaconda in any case you're getting the latest, which likely covers anyone using windows.

I would be as happy to not support 3.4 as I would be to replace `@` with `np.dot`, but happy to be overruled.

**Comment by martinjrobins** [comment]
I'm happy to require python 3.5 and up

**Comment by tinosulzer** [comment]
Me too

On 15 Feb 2019 10:54, Martin Robinson <notifications@github.com> wrote:

I'm happy to require python 3.5 and up

**Comment by fcooper8472** [comment]
@martinjrobins any ideas on the ODES related failures? I'm unable to reproduce them outside of travis... everything seems to be installed and set up correctly.  Can't think of any reason that it would work on 3.6 but not 3.5 or 3.7...

**Comment by martinjrobins** [comment]
The README.md for odes.scikit says its for Python 3.3-3.5, so they might not have tested on 3.7. But it doesn't explain why 3.5 is not working. Maybe you can have a look at their travis setup, make sure we arn't missing anything?

**Comment by tinosulzer** [comment]
Will need to update `README.md` and `CONTRIBUTING.md` to say we only support Python3.5+

**Comment by fcooper8472** [comment]
Ok, I've tried using the sundials install scripts used by [ODEs](https://github.com/bmcage/odes), and we're getting the same errors.

I'll open an issue over at ODEs and see if there's something obvious we're doing wrong.

**Comment by fcooper8472** [comment]
See https://github.com/bmcage/odes/issues/92

**Comment by fcooper8472** [comment]
https://travis-ci.org/tinosulzer/PyBaMM/jobs/503052350
