### ISSUE TITLE
CI tests are not run on PRs from forks

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#1012]
When a PR is made from a fork, the CI tests on GitHub actions do not start. See #1009 and #1010 for example. I don't know if this is due to a temporary outage or a bug in the workflow

@tlestang  @dalonsoa

**Comment by dalonsoa** [comment]
Sorry! I dind't realised this was assigned to @tlestang and have open a PR with - I think - the solution.

**Comment by tlestang** [comment]
No worries! I'm just finding out about this issue :)

**Comment by tlestang** [comment]
I guess CI was only triggered by pushes?

**Comment by dalonsoa** [comment]
Yes, that was the issue. I've just added `pull_request` to trigger it also when there's a PR. In principle, it will trigger then theres a PR against ANY branch, but I guess in practive it will be just develop and, from time to time, master.
