### ISSUE TITLE
Charge-transfer resistance

### ISSUE THREAD

**Issue by gyouhoc** [pybamm-team/PyBaMM#1019]
Is it possible to estimate charge-transfer resistance with this model? 
If so, what is the output variable name for this?

**Comment by tinosulzer** [comment]
I think we call this "reaction overpotential". You can do `model.variables.search("reaction overpotential")` to see all the different ones but "X-averaged reaction overpotential [V]" is probably what you are looking for

**Comment by tinosulzer** [comment]
@gyouhoc can I close this?

**Comment by gyouhoc** [comment]
sorry for the delay.
