### ISSUE TITLE
add list to parameter sets docs

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/PyBaMM#1033]
Add a list of the available AuthorYear parameter sets in the docs for parameter_sets. At the moment there is no obvious way of seeing what sets are available other than opening the parameter_sets file. Is there a sensible way to automate this?

**Comment by tinosulzer** [comment]
Yeah this should be automated so it doesn't get out of date .It would probably be pretty easy to automate once you figure out how to make the github workflow run a script and push the result back. One for @tlestang ?

**Comment by tlestang** [comment]
Sounds good, I'll think about it

**Comment by priyanshuone6** [comment]
Could you please elaborate more on this?

**Comment by rtimms** [comment]
We currently have a number of parameters sets which are available by calling `pyabmm.parameter_sets.AuthorYear` (see [here](https://github.com/pybamm-team/PyBaMM/blob/develop/pybamm/parameters/parameter_sets.py).  Details about these sets have been added manually to the documentation, but it would be good to automate this so that you don't have to manually update the docstring every time a new parameter set is added.

**Comment by priyanshuone6** [comment]
Can I work on this issue because @tlestang is already assigned to it?

**Comment by tinosulzer** [comment]
I don't think he is actively working on this right now

**Comment by priyanshuone6** [comment]
Please confirm, if I am getting it right

If AuthorYear like this is added in the `parameter_sets.py`
https://github.com/pybamm-team/PyBaMM/blob/8ed813e8406bc2b272a6f2ddc5a4144ff59e6700/pybamm/parameters/parameter_sets.py#L68-L78
then I have to convert these new AuthorYear into this
https://github.com/pybamm-team/PyBaMM/blob/8ed813e8406bc2b272a6f2ddc5a4144ff59e6700/pybamm/parameters/parameter_sets.py#L29-L33 by automating them using github workflow in which a script will run and push the result back in form of a pull request

**Comment by tinosulzer** [comment]
Yes, and you can use something like this
https://github.com/pybamm-team/PyBaMM/blob/8ed813e8406bc2b272a6f2ddc5a4144ff59e6700/pybamm/citations.py#L90-L94
to do the formatting of the citation

**Comment by priyanshuone6** [comment]
In which folder should I place the script.py?
