### ISSUE TITLE
update installation instructions

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/PyBaMM#1040]
update installation instructions to specify python 3.7 and use virtualenv instead of venv (so that people have wheel)

**Comment by tinosulzer** [comment]
Which installation instructions is this referring to?

**Comment by rtimms** [comment]
looks like just in the user install instructions on readthedocs where we give instruction on creating a virtual env

**Comment by tinosulzer** [comment]
Ok, it says a few lines above to use python 3.7, but I guess we can repeat it

**Comment by rtimms** [comment]
yeah I think also using virtualenv as people in the workshop ran into problems as they had to do pip install wheel first
