### ISSUE TITLE
Simplify compare model examples

### ISSUE THREAD

**Issue by ferranbrosa** [pybamm-team/PyBaMM#1049]
Rewrite the compare model examples so they use Simulations instead of the long way (processing parameters, meshing...).

**Comment by ferranbrosa** [comment]
The file `compare_lithium_ion.py` starts with:
```
parser = argparse.ArgumentParser()
parser.add_argument(
    "--debug", action="store_true", help="Set logging level to 'DEBUG'."
)
args = parser.parse_args()
if args.debug:
    pybamm.set_logging_level("DEBUG")
else:
    pybamm.set_logging_level("INFO")
```

Do we want to keep it? Or take it out to simplify?

@rtimms

**Comment by tinosulzer** [comment]
I don't really use that any more so feel free to remove, but keep `pybamm.set_logging_level("INFO")`
