### ISSUE TITLE
Update Getting Started notebooks

### ISSUE THREAD

**Issue by ferranbrosa** [pybamm-team/PyBaMM#1079]
**Summary**
Now that Google Colab compatibility is about to go live it would be nice to create an introductory set of notebooks in the website (Getting Started) section which would launch directly in Colab. Might be a good time to think if we want to update/extend the Getting Started notebooks from the experience we got in the workshops.

 **Motivation**
Set up a very user-friendly set of notebooks to lower the entry barrier to PyBaMM.

**Comment by ferranbrosa** [comment]
Here is a possible structure for the notebooks:

1. How to run a simulation: basically you define a model, a simulation and run it (the basic stuff, kind of "Hello world!").
2. Compare models: again, very few lines but we are introducing the three standard models.
3. Basic plotting: it also helps introducing the variables so we don't have to do it later.
4. Change parameters: in the same script.
5. Run experiments: quite descriptive.
6. Advanced model features: model options, access variables, store outputs...
7. Advanced solver features: change mesh resolution and solver tolerance.

**Comment by tlestang** [comment]
I agree that having some ready-to-try examples on the website would do a lot of good.
Other than notebooks, the new kid in the block is [https://www.streamlit.io/](streamlit.io) which could be useful to showcases some potential use cases of pybamm

**Comment by ferranbrosa** [comment]
That looks really cool! Might be useful in the future to write some scripts with some data analysis features. @TomTranter would that be helpful for the GUI?
