### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by vishankkumar** [pybamm-team/PyBaMM#1102]
**Describe the bug**
dynamic_plot() function is generating a recursion error that says "RecursionError: maximum recursion depth exceeded while calling a Python object".

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'examples/scripts'
2. Run 'python DFN.py'
3. See error

**Expected behaviour**
Examples are expected to work without error if the prerequisites are met, which I checked earlier.

**Screenshots**
(Screenshot attached)

**Additional context**
![Screenshot from 2020-07-10 16-07-21](https://user-images.githubusercontent.com/32134010/87163422-9f976100-c2c7-11ea-8f03-0778bf9059b0.png)

**Comment by tinosulzer** [comment]
Looking at the traceback, this looks like a problem with matplotlib rather than pybamm. Do you get this error with the other examples or just this one? Can you try updating to the latest version of matplotlib?

**Comment by vishankkumar** [comment]
Thanks for your quick response. Updating matplotlib worked for me, now examples are running fine.
