### ISSUE TITLE
Add upwinding and downwinding operators for convection-dominated flow

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#1126]
Consider a standard reaction-advection-diffusion equation,
```
dc/dt = D d2c/dx2 - d/dx( c * v ) + s
```
Currently, with the `FiniteVolume` discretisation, the `c` term in convection gets discretised with a central volume (in `process_binary_operators`). However, if transport is convection dominated (`D << 1`), then
1. The numerical solution is unstable, http://www.mathematik.uni-dortmund.de/~kuzmin/cfdintro/lecture5.pdf
1. the boundary conditions are almost entirely ignored, since boundary conditions only come in through the diffusion operator.

This can be fixed by introducing an upwinding (if v > 0) or downwinding (if v < 0) term, which should be explicitly stated when defining the equations (this could perhaps be automated at a later stage). The resulting discretisation of `upwind(c)` would be a concatenation `[bc_in, c]`, where `bc_in` is chosen to satisfy the Dirichlet boundary condition at c=0. Similarly, the discretisation of `downwind(c)` would be `[c, bc_in]`. This is the lowest-order discretisation possible, higher-order corrections are possible, see http://www.mathematik.uni-dortmund.de/~kuzmin/cfdintro/lecture5.pdf (e.g. "Quadratic upwind difference scheme (QUICK)") and may be required to avoid smearing.

**Comment by ferranbrosa** [comment]
Related to that, the book by Leveque (https://www.cambridge.org/core/books/finite-volume-methods-for-hyperbolic-problems/97D5D1ACB1926DA1D4D52EAD6909E2B9) might be useful. It says that all the methods in the book are implemented in ClawPack, which is a NumFocus affiliated project, so it might be an interesting mid-term goal to write a ClawPack wrapper.
