### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by gyouhoc** [pybamm-team/PyBaMM#1135]
Hi, 

I am currently working on increasing the capacity (1C discharge capacity) of the model. 
Would you provide me some tips on this? Which material parameter needed to be updated?

**Comment by tinosulzer** [comment]
Changing the geometric parameters (height and width of the current collectors) is probably the easiest way. Or you can change the maximum particle concentrations, but then you need to be careful.

**Comment by gyouhoc** [comment]
I have fixed geometric parameters.
maximum particle concentrations = Maximum concentration in negative electrode [mol.m-3] and Maximum concentration in positive electrode [mol.m-3] ? 
Which electrode has greater influence on the capacity increase?

**Comment by tinosulzer** [comment]
> maximum particle concentrations = Maximum concentration in negative electrode [mol.m-3] and Maximum concentration in positive electrode [mol.m-3] ?

Yes

> Which electrode has greater influence on the capacity increase?

To be honest, this is more of a science question than a software one. We are open for collaboration/research projects on such questions but need to know more information about the system. You can email me vsulzer at umich.edu
