### ISSUE TITLE
Repeated entry

### ISSUE THREAD

**Issue by dalonsoa** [pybamm-team/PyBaMM#1140]
The last entry in this dictionary of `base_sei.py` is repeated. It looks that the last one is missing the units. I guess it should be [mol.m-3], but I'm not entirly sure.

https://github.com/pybamm-team/PyBaMM/blob/c320ad7700211606e53ccfe3ac867d30c495b9c5/pybamm/models/submodels/interface/sei/base_sei.py#L173-L185

**Comment by tinosulzer** [comment]
Good spot, yes it should be [mol.m-3]

**Comment by tinosulzer** [comment]
@all-contributors please add @dalonsoa for bug report
