### ISSUE TITLE
Add simple equivalent circuit model

### ISSUE THREAD

**Issue by Scottmar93** [pybamm-team/PyBaMM#1143]
**Summary**
Add a simple equivalent circuit model that is coupled to the "potential pair" current collectors. Will start with just a resistor and add RC circuits later. 

**Reason** 
Simple, easy to parameterize models that can give information about cell utilization. These are good to have in PyBaMM so that the EC and physics-based approaches can be easily compared.

**Comment by DavidMStraub** [comment]
Is somebody still pursuing this? I agree it would be great to have this functionality to have a way to compare the easy to parameterize EC models that are used in real-time applications to the physics-based models in the same framework.

**Comment by tinosulzer** [comment]
Looks like it doesn't need too much to get this over the line, even if it's just "1D" for now

**Comment by KennethNwanoro** [comment]
Is anyone still on this? This is the next thing I would like to implement/see in Pybamm (equivalent circuit models). Useful for comparing physics based models as well as fitting EIS data to decouple internal resistances . If no one is still doing this, I can take it up or work with them. Regards.
