### ISSUE TITLE
Colorbar on 2d data shows wrong values

### ISSUE THREAD

**Issue by TomTranter** [pybamm-team/PyBaMM#1145]
**Describe the bug**
I was running a simulation where temperature in a 1+1D model wasn't changing much (less than 1 degree) but the colorbar made it look like it varied by 10s of degrees because it is adjusted up and down by 4% of the absolute value (298) after plotting the mesh when variable_limits="tight". First of all I'm not sure it should be adjusting it at all after plotting and refreshing. Secondly 4% of the data range would make more sense.

**To Reproduce**
Steps to reproduce the behaviour:
```
import pybamm

param = pybamm.ParameterValues(chemistry=pybamm.parameter_sets.Marquis2019)
model_1D_lumped = pybamm.lithium_ion.SPMe({"dimensionality": 1,
                                           "current collector": "potential pair",
                                           "thermal": "x-lumped"})
sim_1D_lumped = pybamm.Simulation(model_1D_lumped, parameter_values=param)
sim_1D_lumped.solve([0, 36])
temp = sim_1D_lumped.solution["Cell temperature [K]"].entries
t_min = temp.min()
t_max = temp.max()
variable_limits = {"X-averaged cell temperature [K]": (t_min, t_max),
                   "Cell temperature [K]": (t_min, t_max),
                   "Volume-averaged cell temperature [K]": (t_min, t_max)}
print(t_min, t_max)
sim_1D_lumped.plot(["X-averaged cell temperature [K]",
                    "Cell temperature [K]",
                    "Volume-averaged cell temperature [K]"],
                    variable_limits="tight",
                    )
```

**Expected behaviour**
A true representation of the temperature range that update dynamically for each time step

**Screenshots**
![image](https://user-images.githubusercontent.com/7068741/92790771-fb539880-f3a3-11ea-89bc-636d3930651a.png)

**Comment by TomTranter** [comment]
Using the actual variable limits from the dictionary instead gives the best results.
![image](https://user-images.githubusercontent.com/7068741/92791447-951b4580-f3a4-11ea-8dfa-6937f27e4751.png)

Not specifying the limits again makes the range too wide but at least shows the right colour and scale
![image](https://user-images.githubusercontent.com/7068741/92791565-afedba00-f3a4-11ea-8b86-418ef6920e6a.png)

I am happy to make the changes and adjust the limits based on the data range but also make sure what is shown on the colorbar is the same as the plot - 2 conflated issues here really

**Comment by tinosulzer** [comment]
So, just to understand, are you suggesting that the colorbar should be fixed to (min of variable, max of variable) even when `variable_limits` is `"tight"`? Which would be the same behaviour (for 2d data) as having `variable_limits="fixed"`?

**Comment by tinosulzer** [comment]
i.e. does the following give you exactly what you want?
```python3
variable_limits = {"X-averaged cell temperature [K]": "tight",
                   "Cell temperature [K]": "fixed",
                   "Volume-averaged cell temperature [K]": "tight"}
```
If so, we could add an option which sets 1D variables to tight and 2D variables to fixed

**Comment by TomTranter** [comment]
I think there is a genuine bug. In the first screen shot you see the variation in temperature and corresponding colorbar and they have been scaled differently. ax_min and ax_max increase the range on the colorbar only so my small temperature difference looked as though it was massive.

**Comment by tinosulzer** [comment]
Ah yeah, I see

**Comment by tinosulzer** [comment]
@TomTranter this might be a good first issue for someone if you don't have time to do and can explain exactly what is needed

**Comment by TomTranter** [comment]
Yep, I’d forgotten about this until the other day

**Comment by tinosulzer** [comment]
@TomTranter  I wasn't able to reproduce the problem with different scalings. Do you still see it or have we accidentally fixed it?

**Comment by rtimms** [comment]
I think this is fixed. @TomTranter can you test and confirm?
