### ISSUE TITLE
API documentation missing on RTD

### ISSUE THREAD

**Issue by bessman** [pybamm-team/PyBaMM#1164]
**Describe the bug**
The API documentation on readthedocs is missing/empty.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://pybamm.readthedocs.io/en/latest/#module-pybamm
2. Click on any class
3. No documentation to be seen

**Expected behaviour**
The API documentation should contain the same information found in class and method docstrings, as it does when building the documentation locally.

**Screenshots**
On readthedocs:
![](https://i.imgur.com/7NOFKIO.png)

Local build:
![](https://i.imgur.com/BTypTCo.png)

**Comment by tlestang** [comment]
Hi @bessman , thanks for reporting the problem.
Changes proposed in #1165 should fix that.

Some dependencies (jax, jaxlib) were not listed on the file that read the docs reads to know which dependencies to install to build the docs, resulting in autodoc (which builds the API docs) issuing warnings. Unfortunately the documentation was still built successfully... just without the API docs!
