### ISSUE TITLE
"spherical polar" coordinates ignore left boundary condition

### ISSUE THREAD

**Issue by bessman** [pybamm-team/PyBaMM#1174]
**Describe the bug**
When using "spherical polar" coordinates, the left boundary condition seems to always be zero flux, regardless of what the user specifies.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the 'Creating Models/2-a-pde-model.ipynb' notebook.
2. Change the left boundary condition type and/or value to anything.
3. Rerun notebook.
4. Final result is the same.

**Expected behaviour**
The left boundary condition should be user-changeable. Alternatively, if zero flux is intentionally enforced on the left boundary in spherical coordinates, the user should be warned of this fact if they request something else.

**Comment by tinosulzer** [comment]
Thanks for pointing out - seems to be something do with with the multiplication by `r**2` which we should be more careful about

**Comment by ferranbrosa** [comment]
Hi @bessman! I think that for spherical (and cylindrical coordinates) the condition at r=0 should always be a no-flux condition (note that, in reality, this is an artificial boundary that arises due to the parameterization of the domain). What problem are you trying to solve that gives you a BC other than no-flux?

**Comment by bessman** [comment]
I noticed it while working through some of the example notebooks. Specifically, in "Creating Models/2-a-pde-model.ipynb", the left boundary condition type is given as Dirichlet in the code. This should result in an incorrect result, but does not, because the boundary condition is ignored.

As you say, that's not typically going to be a problem when dealing with spherical particels. I just think the behavior should be clearly documented if it is intentional, to avoid surprising the user.

**Comment by rtimms** [comment]
thanks @bessman looks like this was a typo in the notebook. as discussed, symmetry always gives no flux at r=0 in spherical polars, but it would be good to add a warning if people try to use a different condition

**Comment by ferranbrosa** [comment]
Cool, I will modify the code so it throws an error if a "left" bc is passed that it is not a no-flux condition.

**Comment by tinosulzer** [comment]
@all-contributors add @bessman for bugs, examples

**Comment by tinosulzer** [comment]
@all-contributors add @bessman for bugs, examples

**Comment by tinosulzer** [comment]
Good bot
