### ISSUE TITLE
Add erf and erfc functions

### ISSUE THREAD

**Issue by brosaplanella** [pybamm-team/PyBaMM#1183]
**Summary**
Add the error function (erf) and complementary error function (erfc) to PyBaMM.

 **Motivation**
These functions come up in some applications (e.g. Stefan problems) and it would good to have them into PyBaMM. Should be an easy implementation, however it would require calling SciPy from `functions.py`. Would that be an issue?

**Comment by tinosulzer** [comment]
That would be fine, the only question is whether casadi has those functions

**Comment by ferranbrosa** [comment]
It has `erf`. If we define the PyBaMM function `Erfc` as `1 - Erf` then Casadi should be able to cope with it, right?
