### ISSUE TITLE
Raise error when saving bad variable name to mat file

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#1203]
If a `.mat` file has a variable name with a space in the name, MATLAB won't be able to load it. So we shouldn't save it. Raise error instead and suggest making a new variable with a more MATLAB-compatible name.
We could try converting spaces to underscores, etc, but units (`[mol.m-3]`) would not work (none of [, ., - are ok)

**Comment by tinosulzer** [comment]
Alternatively, add an extra keyword argument to `solution.save_data` which allows the user to provide a dictionary of name conversions

**Comment by rtimms** [comment]
I think passing a dict of name conversion is more user-friendly that created new variables
