### ISSUE TITLE
Optionally convert variable to casadi format before evaluating

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#1221]
Right now, for fast models such as the SPM, solving the model takes 2 ms but evaluating the voltage takes 160 ms. 

Under the right combination of conditions, it might be faster to convert a variable to casadi before evaluating it. The converted variable could be saved to a dictionary such as `model.casadi_variables` which would then be available to the next solution. This could also bypass the need for doing `y.full()` after solving to convert from casadi format to numpy format (`y.full()` takes as much time as doing the integration itself, 0.5 ms).

Could also try vectorizing as suggested in #788

**Comment by TomTranter** [comment]
Would this work best for the volume averaged properties? If this were a CFD solver you could define monitoring points etc in the mesh to keep an eye on certain variables - not sure wee need to go that far and we're not monitoring convergence but I really like the idea of getting a few bits of key info on the fly - would help me solve the jellyroll problem a bit faster

**Comment by tinosulzer** [comment]
I don't think volume-averaged or not makes a difference. There is no way to evaluate at just a single point without evaluating the whole thing first. (In general) the volume-averaged variables are the explicit integral (i.e. the dot product of a vector of ones and the variable) so you have to evaluate the full distribution before you can get the volume-averaged variable.
