### ISSUE TITLE
sparse mat-vec support for EvaluatorJax

### ISSUE THREAD

**Issue by martinjrobins** [pybamm-team/PyBaMM#1235]
**Summary**

currently `pybamm.EvaluatorJax` does not support sparse matrices, because jax does not support them. It just replaces all sparse mats in expression tree with dense ones. However, you can implement a sparse mat-vec multiplication in jax easily enough (see https://gist.github.com/romanodev/34a471e8914989dbedee85febdbe7c77), so I propose replacing all sparse mat-vec mults with this, should be a lot faster.

 **Motivation**

a sparse mat-vec mult will be much faster than the equivalent dense mat-vec

**Comment by martinjrobins** [comment]
anyone know if this will work for the DFN model? I had a brief play with it, and found a place in the expression tree where a constant sparse matrix is multiplied by a dense matrix (with entries depending on the state vector). It could be that I'm doing something wrong, but if anyone knows if there is definitely a matrix-matrix multiply in the DFN model, or any others, let me know!

**Comment by tinosulzer** [comment]
The only `matmul` operations in the DFN model should be matrix-vector, or vector-vector (i.e. dot product) for "integration". If there are some matrix-matrix matmuls I would be interested to know where they are.
There may be some elementwise multiplications that are matrix-matrix though

**Comment by martinjrobins** [comment]
you are absolutely right, this was me making a mistake and adding a 1D vector with a 2D column vector, which gave a 2D matrix via broadcasting. Fixed now
