### ISSUE TITLE
Add JAX citation for the JAX solvers

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#1243]

**Comment by tinosulzer** [comment]
Also add default ref to numpy paper (?)

@article{harris2020array,
  title={Array programming with NumPy},
  author={Harris, Charles R and Millman, K Jarrod and van der Walt, St{\'e}fan J and Gommers, Ralf and Virtanen, Pauli and Cournapeau, David and Wieser, Eric and Taylor, Julian and Berg, Sebastian and Smith, Nathaniel J and others},
  journal={Nature},
  volume={585},
  number={7825},
  pages={357--362},
  year={2020},
  publisher={Nature Publishing Group}
}

**Comment by martinjrobins** [comment]
Re JAX, the developers ask you to cite the github repo itself (they are still working on a paper):
```
@software{jax2018github,
  author = {James Bradbury and Roy Frostig and Peter Hawkins and Matthew James Johnson and Chris Leary and Dougal Maclaurin and Skye Wanderman-Milne},
  title = {{JAX}: composable transformations of {P}ython+{N}um{P}y programs},
  url = {http://github.com/google/jax},
  version = {0.2.5},
  year = {2018},
}
```
