### ISSUE TITLE
Reformat DFN half-cell

### ISSUE THREAD

**Issue by brosaplanella** [pybamm-team/PyBaMM#1253]
Reformat the basic DFN half-cell so that the lithium counter is always on the left and the working electrode on the right, to be consistent with the standard DFN half-cell definitions of current and terminal voltage.

**Comment by brosaplanella** [comment]
After playing around with it, I have noticed that this requires changing the definition of the geometry. Thinking of the long run as well (when we integrate it in the submodel structure), I am thinking of doing the following. Define a `half_cell_geometry` (similar to `battery_geometry`), which has a lithium electrode, a separator and a working (porous) electrode. When defining the geometry, we pass an option to define the working electrode and this sets the right parameters.

Is there a better way of doing it?

**Comment by tinosulzer** [comment]
Can't think of a better way right now

**Comment by tinosulzer** [comment]
As discussed today, the new format is much clearer and we should go ahead with it. Then, the half-cell models can use the submodel structure by passing the option "half-cell" or "full cell" to the submodels (this will require a little bit of submodel refactoring, but hopefully not too much).
