### ISSUE TITLE
Literature references for SEI models

### ISSUE THREAD

**Issue by maurosgroi** [pybamm-team/PyBaMM#1260]
Dear all,
my name is Mauro Sgroi. I work at Centro Ricerche FIAT on Li-ion cells.
I'm new to PyBamm and I'm trying to understand the details of the package.
I've seen that some SEI models are present but I cannot find the relative literature references in readthedocs.
Are they available?

Thanks a lot in advance and best regards,
Mauro Sgroi.

**Comment by rtimms** [comment]
@Scottmar93 do you have the refs for these to hand?

**Comment by tinosulzer** [comment]
@Scottmar93 how much work would it be to make your thesis chapter into an arxiv-worthy publication?
