### ISSUE TITLE
Enertech cell data not included in the release

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#1266]
Do we need to edit MANIFEST.in? Are there other things we forgot to add to this @tlestang ?
<img width="1176" alt="Screen Shot 2020-12-02 at 9 22 44 PM" src="https://user-images.githubusercontent.com/20817509/100955471-990ebd80-34e4-11eb-9982-d8561f1fba83.png">

**Comment by tlestang** [comment]
At the moment only files ending in ".py", ".csv" or ".md" are added to the distribution, because we don't want to add any ".pyc" file.
```python
# setup.py (around l. 136)
pybamm_data = []
for file_ext in ["*.csv", "*.py", "*.md", ".txt"]:
    # Get all the files ending in file_ext in pybamm/input dir.
    # list_of_files = [
    #    'pybamm/input/drive_cycles/car_current.csv',
    #    'pybamm/input/drive_cycles/US06.csv',
    # ...
    list_of_files = glob.glob("pybamm/input/**/" + file_ext, recursive=True)
    ...
```
