### ISSUE TITLE
try reformatting Symbol.orphans to avoid creating new_copy

### ISSUE THREAD

**Issue by valentinsulzer** [pybamm-team/PyBaMM#1353]
Currently, `symbol.orphans` is expensive as it calls `new_copy`.
This is done to avoid tree corruption errors in anytree.

It might be possible to make it significantly faster by simply storing the variables that are assigned to `children` before they are fixed into the expression tree (which is what causes the corruption errors).

Edit: it's so easy, I can't believe we didn't do it this way the first time around

**Comment by tinosulzer** [comment]
Closing, will do as part of #1301
