### ISSUE TITLE
Incorrect values for y axis in 2D simulation?

### ISSUE THREAD

**Issue by DavidMStraub** [pybamm-team/PyBaMM#1363]
**Describe the bug**

This might not be a bug but just me not understanding how to do things properly (PyBaMM beginner...).
When using a 2+1D pouch cell model, the plot uses values for the y (horizontal) axis which are not what I would expect based on the `Electrode width` parameter setting.

**To Reproduce**
Steps to reproduce the behaviour:

```python
import pybamm

options = {"cell geometry": "pouch", "thermal": "x-lumped", "dimensionality": 2}
model = pybamm.lithium_ion.SPM(options=options)
geometry = model.default_geometry

parameter_values = model.default_parameter_values
parameter_values.update(
    {
        "Electrode height [m]": 0.3,
        "Electrode width [m]": 0.1,
        "Negative tab width [m]": 0.03,
        "Positive tab width [m]": 0.03,
        "Negative tab centre y-coordinate [m]": 0.03,
        "Positive tab centre y-coordinate [m]": 0.07,
        "Negative tab centre z-coordinate [m]": 0.3,
        "Positive tab centre z-coordinate [m]": 0.3,
    }
)
parameter_values.process_model(model)
parameter_values.process_geometry(geometry)

sim = pybamm.Simulation(model, parameter_values=parameter_values, solver=pybamm.CasadiSolver("fast"))
sim.solve([0, 60])
```
**Expected behaviour**

I expected the horizontal axis (y) to extend from 0 to 10 cm.

**Screenshots**

![image](https://user-images.githubusercontent.com/10965193/107036629-383c8380-67ba-11eb-948f-e327235b03cc.png)

**Additional context**

Using PyBaMM 0.3.0 or current master (no difference). Python 3.8.5.

**Comment by tinosulzer** [comment]
Yeah that's a bug, thanks for spotting. Fixing now

**Comment by tinosulzer** [comment]
@all-contributors add @DavidMStraub for bug

**Comment by tinosulzer** [comment]
FYI, you can pass the plot function a "spatial_unit" argument to display mm or m instead of um https://pybamm.readthedocs.io/en/latest/source/plotting/quick_plot.html

**Comment by tinosulzer** [comment]
@all-contributors add @DavidMStraub for bug

**Comment by DavidMStraub** [comment]
Thanks for the quick fix!
