### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/PyBaMM#1373]
There are some broken links that don't seem to be getting picked up by the link checker. Two I have spotted are the Read The Docs in the README
![Screenshot from 2021-02-10 09-37-59](https://user-images.githubusercontent.com/43040151/107491925-b666a480-6b83-11eb-8167-240a3a065398.png)

and one of the links in `change-settings.ipynb`
![Screenshot from 2021-02-10 09-38-04](https://user-images.githubusercontent.com/43040151/107491937-ba92c200-6b83-11eb-9368-02bd77ed4bb4.png)

@priyanshuone6 do you know why these get missed?

**Comment by priyanshuone6** [comment]
I checked and found that the link checker is not picking up these links due to which they are not getting checked. I am not sure why this happening. I will try to find other options to maybe replace this workflow.

**Comment by rtimms** [comment]
great, thanks!

**Comment by tinosulzer** [comment]
maybe it doesn't check things that don't start with `https`?

**Comment by priyanshuone6** [comment]
`[Read The Docs](readthedocs.io)` and `[here](../simulation-class.ipynb)` are without `https`.
I think that's why the URL checker is not picking up these links.
