### ISSUE TITLE
PEP fix styling around docstring

### ISSUE THREAD

**Issue by priyanshuone6** [pybamm-team/PyBaMM#1376]
I found these styling errors around docstring in functions in various files that doesn't adhere to Python's [PEP guidelines](https://www.python.org/dev/peps/pep-0257/#specification).
https://github.com/pybamm-team/PyBaMM/blob/9883106d84a8ad43b299ea4e0ce8ef58d395cb28/pybamm/citations.py#L29-L30
https://github.com/pybamm-team/PyBaMM/blob/9883106d84a8ad43b299ea4e0ce8ef58d395cb28/pybamm/settings.py#L32-L33
https://github.com/pybamm-team/PyBaMM/blob/9883106d84a8ad43b299ea4e0ce8ef58d395cb28/pybamm/util.py#L63-L64

**Expected behavior**
Find all those functions and replace `"` with 3 double quotes `"""` for consistency across the repository .

It can be marked as a good first issue

**Comment by asinghgaba** [comment]
If anyone’s not working on it, I can get this done.

**Comment by tinosulzer** [comment]
There are probably several other places where it's like this, I wasn't aware of the PEP guideline for this
