### ISSUE TITLE
Local ECM resistance

### ISSUE THREAD

**Issue by DavidMStraub** [pybamm-team/PyBaMM#1377]
**Describe the bug**

Hi, I am trying to understand the "Local ECM resistance" variable. It seems like this is [defined](https://github.com/pybamm-team/PyBaMM/blob/develop/pybamm/models/full_battery_models/base_battery_model.py#L904-L934) as the sum of all overpotentials, plus the difference between current OCV and initial OCV, divided by the current. If I understand correctly, this corresponds to treating the entire cell as a single Ohmic resistor with a time-dependent resistance. However, what I would have expected is that "ECM" refers to a model with a voltage source for OCV in series with an Ohmic resistor, so the OCV is not considered in the voltage difference.

It could be that this is intentional, so I would just like to clarify.

**To Reproduce**

```python
import pybamm
model = pybamm.lithium_ion.SPM()
sim = pybamm.Simulation(model)
sim.solve([0, 3600])
sim.plot(["Local ECM resistance [Ohm]"])
```

**Expected behaviour**

I would have expected the internal resistance (defined as the resistance in series with the OCV voltage source) to not vary drastically during discharge.

**Screenshots**

![image](https://user-images.githubusercontent.com/10965193/107669353-f025d100-6c91-11eb-95de-e00c05d52609.png)

**Additional context**
Reproduced under v0.3.0 and on master (903b4a05ef5a4f91633e990d4aec12c53df723a2).

**Comment by tinosulzer** [comment]
Hmm yeah I agree it probably shouldn't include the OCV change - @TomTranter ?

**Comment by TomTranter** [comment]
Yeah it was intentional but change in ocv is also another variable so could
be taken out of this one

**Comment by tinosulzer** [comment]
Yeah I think not having it in this variable is more intuitive. @DavidMStraub could you open a PR?
