### ISSUE TITLE
Problem with parameter_sets.py auto-generated docs

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#1386]
- The automatic PR should only be opened when there is a push to develop (not any branch as is currently the case)
- Current formatting is making the doctests fail

@priyanshuone6 could you fix this?

**Comment by priyanshuone6** [comment]
Could you please elaborate more on the doctest failing?

**Comment by tinosulzer** [comment]
Here's the broken test: https://github.com/pybamm-team/PyBaMM/runs/1889607759#step:11:207
You can test this locally with `python run-tests.py --doctest`

**Comment by priyanshuone6** [comment]
I tried to solve the error `/home/priyanshu/work/PyBaMM/pybamm/parameters/parameter_sets.py:docstring of pybamm.parameters.parameter_sets:9:Unexpected indentation.
FAILED`  but I am unable to find the problem in line 9 which is causing the tests to fail. Could you please help me with this?

**Comment by tinosulzer** [comment]
rst is quite picky about indentations in lists. You could try isolating the problem by commenting things out and running the local test. I think sometimes they want a `\` at the end of the line in a list
