### ISSUE TITLE
Operating mode docs

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/PyBaMM#1388]
The “operating mode” option is missing from the doc string for `BaseBatteryModel`

**Comment by Saransh-cpp** [comment]
Can you please elaborate on what should be added to description of "operating mode" ? Should I add this - "Sets the operating mode for the model. Can be "Current" (default), "voltage" or "power""? There was also an ```elif``` condition while checking for the "operating mode" -
```python
elif callable(self.options["operating mode"]):
            self.submodels[
                "external circuit"
            ] = pybamm.external_circuit.FunctionControl(
                self.param, self.options["operating mode"]
            )
```
What can I add for this in the docstring? Thanks!

**Comment by rtimms** [comment]
You could say something like "Alternatively, the operating mode can be controlled with an arbitrary function by passing the function directly as the option. In this case the function must define the residual of an algebraic equation. The applied current will be solved for such that the algebraic constraint is satisfied."

**Comment by Saransh-cpp** [comment]
Thanks! I will add this in the doc string.
