### ISSUE TITLE
Replace binder with google colab

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/PyBaMM#1390]
In some places (e.g. [here](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#binder)) we still point to binder for using notebooks, but I think our preference now would be to point people to use [Google Colab](https://colab.research.google.com/github/pybamm-team/PyBaMM/blob/master/) instead.

**Comment by Saransh-cpp** [comment]
Does this issue only require looking for all the undesired links and replacing them?

**Comment by rtimms** [comment]
Yeah, and updating any text around it too if it refers to binder. Looks like there are only 2 places to change it actually.

**Comment by Saransh-cpp** [comment]
Okay! I'll look around at other places as well and make all the necessary changes.
