### ISSUE TITLE
readthedocs.io is still using the master branch to show docs

### ISSUE THREAD

**Issue by priyanshuone6** [pybamm-team/PyBaMM#1426]
**Describe the bug**
While reading the PyBaMM documentation from [pybamm.readthedocs.io](https://pybamm.readthedocs.io/en/latest/), I noticed that in [Adding a Model](https://pybamm.readthedocs.io/en/latest/tutorials/add-model.html) various links like the `create a model`, `expression tress` are still broken, because [pybamm.readthedocs.io](https://pybamm.readthedocs.io/en/latest/) is still using the master branch to show its docs, as all the broken links were already fixed in the develop branch using the link checker workflow.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://pybamm.readthedocs.io/en/latest/tutorials/add-model.html
2. Click on `create a model` or `expression tress`
<img width="960" alt="Screenshot (54)" src="https://user-images.githubusercontent.com/64051212/110915477-b0f4a980-833d-11eb-8e3e-54494e2c08bd.png">

**Expected behaviour**
[pybamm.readthedocs.io](https://pybamm.readthedocs.io/en/latest/) shows the latest and updated files from the develop branch instead of the master branch.
And maybe we can [create a webhook](https://docs.readthedocs.io/en/stable/webhooks.html) to automatically update the docs with every push in the repository.

**Comment by tinosulzer** [comment]
Thanks for catching this @priyanshuone6 . We already had the webhook, I updated it to point to develop. Your test works now

**Comment by tinosulzer** [comment]
@all-contributors add @priyanshuone6 for bugs
