### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by DrMichaelCornish** [pybamm-team/PyBaMM#1469]
The instructions for developer install found in the "Installation" section of https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md state that the user should run "tox -e pybamm-requires" in the second step (I'm on ubuntu 20.04). However, this creates an error. The step should specify that the user first clones the github repo and then change directory to the pybamm folder. Once that is done, the command "tox -e pybamm-requires" runs without issue. 

This order of operations is specified in the more detailed instructions linked to a the end of that installation section https://pybamm.readthedocs.io/en/latest/install/install-from-source.html

**Comment by tinosulzer** [comment]
Thanks Michael, @tlestang  is it time to update the docs now with the new instructions for sundials?

**Comment by tlestang** [comment]
Yes. For the specific issue of the developer install, I think the contributing guide should just point to the docs.
