### ISSUE TITLE
broken urls

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#1488]
Looks like some URLs are broken (consistently failing):
https://github.com/pybamm-team/PyBaMM/runs/2579697833

**Comment by tinosulzer** [comment]
looks like most of these urls appeared after @Saransh-cpp committed the parameterization notebook, not sure why

**Comment by Saransh-cpp** [comment]
> looks like most of these urls appeared after @Saransh-cpp committed the parameterization notebook, not sure why

Yes, I just had a look on this and I don't know why but they somehow popped up in the plots.
