### ISSUE TITLE
Infinite loop occurs

### ISSUE THREAD

**Issue by gyouhoc** [pybamm-team/PyBaMM#1493]
While I conduct multiple simulation with Pybamm, I find that the simulation generates an infinite loop and causes the python program to be halted. 

![error_shot](https://user-images.githubusercontent.com/60714526/119517026-3dabe280-bd45-11eb-871d-d56e42466db2.PNG) 
The script stops here (no response) 

![error_shot_2](https://user-images.githubusercontent.com/60714526/119517135-59af8400-bd45-11eb-84d8-0306fcb59f68.PNG)

**Comment by tinosulzer** [comment]
Can you try using `CasadiSolver("fast with events")` instead?

**Comment by gyouhoc** [comment]
for me, ("fast with events") doesn't work. I tried three different solver options and "old safe" is working with an warning. 

"safe": SolverError: Maximum number of decreased steps occurred at t=0.0. Try solving the model up to this time only or reducing dt_max (currently, dt_max=81.88051713742692).

"fast": SolverError: .../casadi/interfaces/sundials/idas_interface.cpp:569: IDASolve returned "IDA_CONV_FAIL". Consult IDAS documentation.

"old safe": working with an warning
            psetup failed: .../casadi/interfaces/sundials/idas_interface.cpp:827: Calculating Jacobian failed

**Comment by tinosulzer** [comment]
Please provide an entire script that can be run to test this

**Comment by gyouhoc** [comment]
Here is the script and required data.

**Comment by tinosulzer** [comment]
I don't see it

**Comment by Prasanna-murata** [comment]
Can you please say the solution to this in case you discussed it

**Comment by Sunnyturicum** [comment]
Hey, I have the same issue. Is there a solution to this problem?

**Comment by brosaplanella** [comment]
Please provide a minimum working example and the full error log, so we can look into it.

**Comment by Sunnyturicum** [comment]
Thank you for taking the time. I have attached a minimal working example and full error log.
```
import pybamm
import matplotlib.pyplot as plt
import numpy as np

model = pybamm.lithium_ion.DFN(
    {
        "lithium plating": "partially reversible",
        "lithium plating porosity change": "true",  # alias for "SEI porosity change"
    }
)

param = pybamm.ParameterValues("OKane2022")

cycle_number = 1000
exp = pybamm.Experiment(
    ["Hold at 4.2 V until C/100",
    "Rest for 4 hours",
    "Discharge at 0.1C until 2.5 V",  # initial capacity check
    "Charge at 0.3C until 4.2 V",
    "Hold at 4.2 V until C/100",]
    + [("Discharge at 1C until 2.5 V",  # ageing cycles
    "Charge at 0.3C until 4.2 V",
    "Hold at 4.2 V until C/100",)] * cycle_number
    + ["Discharge at 0.1C until 2.5 V"],  # final capacity check
    period="5 minutes"
)

sim = pybamm.Simulation(model, parameter_values=param, experiment=exp)

# safe solver
safe_solver = pybamm.CasadiSolver(atol=1e-3, rtol=1e-3, mode="safe", dt_max=100)

sol = sim.solve(solver=safe_solver)

```

The error message is:

At t = 299.979 and h = 4.56806e-09, the corrector convergence failed repeatedly or with |h| = hmin.
2023-08-07 08:57:26.287 - [ERROR] callbacks.on_experiment_error(224): Simulation error: Error in Function::call for 'F' [IdasInterface] at .../casadi/core/function.cpp:1401:
Error in Function::call for 'F' [IdasInterface] at .../casadi/core/function.cpp:330:
.../casadi/interfaces/sundials/idas_interface.cpp:596: IDASolve returned "IDA_CONV_FAIL". Consult IDAS documentation.
ERROR:pybamm.logger:Simulation error: Error in Function::call for 'F' [IdasInterface] at .../casadi/core/function.cpp:1401:
Error in Function::call for 'F' [IdasInterface] at .../casadi/core/function.cpp:330:
.../casadi/interfaces/sundials/idas_interface.cpp:596: IDASolve returned "IDA_CONV_FAIL". Consult IDAS documentation.

**Comment by brosaplanella** [comment]
Using the following solver works for me:
```python3
safe_solver = pybamm.CasadiSolver(mode="safe")
```

**Comment by Sunnyturicum** [comment]
Thank you for your answer. I ran the model with your solver. Unfortunately, I still get the following error message after 319/1000 cycles. 

"""
At t = 299.973 and h = 1.45273e-09, the corrector convergence failed repeatedly or with |h| = hmin.
2023-08-07 19:28:09.253 - [ERROR] callbacks.on_experiment_error(224): Simulation error: Error in Function::call for 'F' [IdasInterface] at .../casadi/core/function.cpp:1401:
Error in Function::call for 'F' [IdasInterface] at .../casadi/core/function.cpp:330:
.../casadi/interfaces/sundials/idas_interface.cpp:596: IDASolve returned "IDA_CONV_FAIL". Consult IDAS documentation.
ERROR:pybamm.logger:Simulation error: Error in Function::call for 'F' [IdasInterface] at .../casadi/core/function.cpp:1401:
Error in Function::call for 'F' [IdasInterface] at .../casadi/core/function.cpp:330:
.../casadi/interfaces/sundials/idas_interface.cpp:596: IDASolve returned "IDA_CONV_FAIL". Consult IDAS documentation.
"""

Do you have an idea why this happens? From the IDAS documentation, it is unclear to me what causes the error IDA_CONV_FAIL.

**Comment by brosaplanella** [comment]
That's strange, mine ran all 1000 cycles. Check that you are using the most recent version of PyBaMM and Casadi.

**Comment by Sunnyturicum** [comment]
By separately installing the Casadi Solver, the new version got installed, and it works now - thank you.

```
%pip install casadi
%pip install pybamm
```

**Comment by flag2freefish** [comment]
same problem, and try all above methods, and then still failed.
code like this. please help me. thank you very much
import pybamm
import matplotlib.pyplot as plt

model = pybamm.lithium_ion.DFN(
    {
        "SEI": "solvent-diffusion limited",
        "SEI porosity change": "true",
        "lithium plating": "partially reversible",
        "lithium plating porosity change": "true",
        "calculate discharge energy": "true",
    }
)

parameter_values = pybamm.ParameterValues("OKane2022")

def graphite_ocp(sto):
    u_eq = (
        0.6379
        + 0.5416 * pybamm.exp(-305.5309 * sto)
        + 0.044 * pybamm.tanh(-(sto - 0.1958) / 0.1088)
        - 0.1978 * pybamm.tanh((sto - 1.0571) / 0.0854)
        - 0.6875 * pybamm.tanh((sto + 0.0117) / 0.0529)
        - 0.0175 * pybamm.tanh((sto-0.5692) / 0.0875)
    )
    return u_eq

def LFP_ocp(sto):
    u_eq = (
        3.4323
        - 0.8428 * pybamm.exp(-80.2493 * (1 - sto) ** 1.3198)
        - 3.2474e-6 * pybamm.exp(20.2645 * (1 - sto) ** 3.8003)
        + 3.2482e-6 * pybamm.exp(20.2646 * (1 - sto) ** 3.7995)
    )
    return u_eq

def negative_electrode_OCP_entropic_change(sto, c_s_max):
    dEdT = (
        2.8957
        - 5.2972 * pybamm.cos(pybamm.arctan(1/(sto**2) - 1))
        + 4.0370 * pybamm.cos(2 * pybamm.arctan(1/(sto**2) - 1))
        - 2.5304 * pybamm.cos(3 * pybamm.arctan(1/(sto**2) - 1))
        + 1.2717 * pybamm.cos(4 * pybamm.arctan(1/(sto**2) - 1))
        - 0.4884 * pybamm.cos(5 * pybamm.arctan(1/(sto**2) - 1))
        + 0.1301 * pybamm.cos(6 * pybamm.arctan(1/(sto**2) - 1))
        - 0.1086 * pybamm.cos(7 * pybamm.arctan(1/(sto**2) - 1))
    )
    return dEdT

def positive_electrode_OCP_entropic_change(sto, c_s_max):
    dEdT = (
        -0.3538 * sto ** 8
        + 1.3902 * sto ** 7
        - 2.2585 * sto ** 6
        + 1.9635 * sto ** 5
        - 0.9872 * sto ** 4
        + 0.2886 * sto ** 3
        - 0.0463 * sto ** 2
        + 0.0032 * sto
        - 1.9186e-5
    )
    return dEdT

def electrolyte_diffusivity_arrhenius(c_e, T):
    D_c_e = (
        5.2969e-20 * c_e ** 3
        - 2.7984e-16 * c_e ** 2
        + 2.8086e-13 * c_e
        + 3.4857e-10
    )
    E_D_c_e = 16500
    arrhenius = pybamm.exp(E_D_c_e / pybamm.constants.R * (1 / 298.15 - 1 / T))
    return D_c_e * arrhenius

def electrolyte_conductivity_arrhenius(c_e, T):
    sigma_e = (
        3.2948e-10 * c_e ** 3
        - 1.6463e-6 * c_e ** 2
        + 2.2550e-3 * c_e
        + 2.5977e-2
    )
    E_sigma_e = 4000
    arrhenius = pybamm.exp(E_sigma_e / pybamm.constants.R * (1 / 298.15 - 1 / T))
    return sigma_e * arrhenius

def cation_transference_number_arrhenius(c_e, T):
    t_plus = (
        5.7052e-17 * c_e ** 5
        - 4.7979e-13 * c_e ** 4
        + 1.2203e-9 * c_e ** 3
        - 1.1791e-6 * c_e ** 2
        + 2.8155e-4 * c_e
        + 3.5182e-1
    )
    E_t_plus = 16500
    arrhenius = pybamm.exp(E_t_plus / pybamm.constants.R * (1 / 298.15 - 1 / T))
    return t_plus * arrhenius

def thermodynamic_factor_arrhenius(c_e, T):
    dlnfdlnc = (
        -4.4566e-10 * c_e ** 3
        + 1.5644e-6 * c_e ** 2
        - 7.4218e-5 * c_e
        - 3.1908e-2
    )
    E_dlnfdlnc = 16500
    arrhenius = pybamm.Exp(E_dlnfdlnc / pybamm.constants.R * (1 / 298.15 - 1 / T))
    return dlnfdlnc * arrhenius

def graphite_diffusivity(sto, T):
    D_ref = 6e-14
    E_D_s = 3.5e4
    arrhenius = pybamm.Exp(E_D_s / pybamm.constants.R * (1 / 298.15 - 1 / T))
    return D_ref * arrhenius

def LFP_diffusivity(sto, T):
    D_ref = 4e-13
    E_D_s = 20000
    arrhenius = pybamm.Exp(E_D_s / pybamm.constants.R * (1 / 298.15 - 1 / T))
    return D_ref * arrhenius

def graphite_electrolyte_exchange_current_density(c_e, c_s_surf, c_s_max, T):
    c_e_0 = pybamm.Parameter("Initial concentration in electrolyte [mol.m-3]")
    k = 6
    m_ref = k * 2 / (c_s_max * c_e_0 ** 0.5)
    E_r = 20e3
    arrhenius = pybamm.Exp(E_r / pybamm.constants.R * (1 / 298.15 - 1 / T))
    return m_ref * arrhenius * c_e ** 0.5 * c_s_surf ** 0.5 * (c_s_max - c_s_surf) ** 0.5

def LFP_electrolyte_exchange_current_density(c_e, c_s_surf, c_s_max, T):
    c_e_0 = pybamm.Parameter("Initial concentration in electrolyte [mol.m-3]")
    k = 2
    m_ref = k * 2 / (c_s_max * c_e_0 ** 0.5)
    E_r = 53e3
    arrhenius = pybamm.Exp(E_r / pybamm.constants.R * (1 / 298.15 - 1 / T))
    return m_ref * arrhenius * c_e ** 0.5 * c_s_surf ** 0.5 * (c_s_max - c_s_surf) ** 0.5

parameter_values["Thermodynamic factor"] = thermodynamic_factor_arrhenius
parameter_values["Cation transference number"] = cation_transference_number_arrhenius
parameter_values["Electrolyte conductivity [S.m-1]"] = electrolyte_conductivity_arrhenius
parameter_values["Electrolyte diffusivity [m2.s-1]"] = electrolyte_diffusivity_arrhenius
parameter_values["Negative electrode OCP [V]"] = graphite_ocp
parameter_values["Positive electrode OCP [V]"] = LFP_ocp
parameter_values["Negative electrode OCP entropic change [V.K-1]"] = negative_electrode_OCP_entropic_change
parameter_values["Positive electrode OCP entropic change [V.K-1]"] = positive_electrode_OCP_entropic_change
parameter_values["Electrode height [m]"] = 1
parameter_values["Negative electrode Bruggeman coefficient (electrode)"] = 1
parameter_values["Positive electrode Bruggeman coefficient (electrode)"] = 1
parameter_values["Lower voltage cut-off [V]"] = 2.5
parameter_values["Upper voltage cut-off [V]"] = 3.65
parameter_values["Open-circuit voltage at 0% SOC [V]"] = 2.5
parameter_values["Open-circuit voltage at 100% SOC [V]"] = 3.65
parameter_values["Initial concentration in negative electrode [mol.m-3]"] = 766.88
parameter_values["Initial concentration in positive electrode [mol.m-3]"] = 19058
parameter_values["Maximum concentration in negative electrode [mol.m-3]"] = 31507.0
parameter_values["Maximum concentration in positive electrode [mol.m-3]"] = 21190
parameter_values["Negative electrode active material volume fraction"] = 0.67038
parameter_values["Positive electrode active material volume fraction"] = 0.58407
parameter_values["Negative electrode porosity"] = 0.269
parameter_values["Positive electrode porosity"] = 0.336
parameter_values["Separator porosity"] = 0.42
parameter_values["Negative electrode thickness [m]"] = 5.3e-5
parameter_values["Positive electrode thickness [m]"] = 8.5e-5
parameter_values["Separator thickness [m]"] = 1.6e-5
parameter_values["Negative particle radius [m]"] = 8.1e-6
parameter_values["Positive particle radius [m]"] = 1.25e-6
parameter_values["Negative electrode diffusivity [m2.s-1]"] = graphite_diffusivity
parameter_values["Positive electrode diffusivity [m2.s-1]"] = LFP_diffusivity
parameter_values["Negative electrode exchange-current density [A.m-2]"] = graphite_electrolyte_exchange_current_density
parameter_values["Positive electrode exchange-current density [A.m-2]"] = LFP_electrolyte_exchange_current_density
parameter_values["Electrode width [m]"] = 0.47
var_pts = {"x_n": 5, "x_s": 5, "x_p": 5, "r_n": 30, "r_p": 30,}
pybamm.set_logging_level("NOTICE")

cycle_number = 1000
experiment = pybamm.Experiment(
    ["Rest for 1 hours", "Discharge at 0.1C until 2.5 V", "Charge at 1C until 3.65 V", "Hold at 3.65 V until C/100",]
    + [("Discharge at 1C until 2.5 V", "Charge at 1C until 3.65 V", "Hold at 3.65 V until C/25",)] * cycle_number
    + ["Discharge at 0.1C until 2.5 V", "Charge at 1C until 3.65 V", "Hold at 3.65 V until C/100",],
    termination="70% capacity"
)

simulation = pybamm.Simulation(model, parameter_values = parameter_values, experiment = experiment, var_pts = var_pts)
solution = simulation.solve(pybamm.CasadiSolver(mode="safe without grid", return_solution_if_failed_early=True))

**Comment by flag2freefish** [comment]
using pybamm>23.5 will output log like they said. it might be a bug.

**Comment by GeXu66** [comment]
> By separately installing the Casadi Solver, the new version got installed, and it works now - thank you.
> 
> ```
> %pip install casadi
> %pip install pybamm
> ```

hello! I met the same problem, could you tell me your casadi and pybamm version? Thank you!

**Comment by Sunnyturicum** [comment]
> > By separately installing the Casadi Solver, the new version got installed, and it works now - thank you.
> > ```
> > %pip install casadi
> > %pip install pybamm
> > ```
> 
> hello! I met the same problem, could you tell me your casadi and pybamm version? Thank you!

Look at this: https://github.com/ArnaudOlt/dissertation_pybamm
