### ISSUE TITLE
Voltage control when using "surface form"

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/PyBaMM#1507]
If you try to use voltage control with the "surface form" option anything other than "false" you get the error `ModelError: each variable in the algebraic eqn keys must appear in the eqn` due to the check [here](https://github.com/pybamm-team/PyBaMM/blob/develop/pybamm/models/base_model.py#L655). If you comment out the check then it works fine. Should we relax this check further? 

The problem, in this case, is that the "Total current density" variable doesn't appear in the equation `V - pybamm.FunctionParameter("Voltage function [V]", {"Time [s]": pybamm.t * self.param.timescale})`

Full example:
 
```python3
import pybamm 

model = pybamm.lithium_ion.SPM(options={"surface form": "algebraic"})

for var in [
    "Terminal voltage", 
    "X-averaged positive electrode surface potential difference", 
    "X-averaged negative electrode surface potential difference",
]:
    print(model.variables[var])

#experiment = pybamm.Experiment(["Hold at 3.8 V until 10 mA"])
experiment = pybamm.Experiment(
    [
        (
            "Discharge at C/5 for 10 hours or until 3.3 V",
            "Rest for 1 hour",
            "Charge at 1 A until 4.1 V",
            "Hold at 4.1 V until 10 mA",
            "Rest for 1 hour",
        ),
    ]
)

sim = pybamm.Simulation(model, experiment=experiment)
sim.solve()
```

**Comment by rtimms** [comment]
I'm not sure why we need this check anyway? So long as the variable appears somewhere in the model then it should be fine? E.g. the model

```python3
model.algebraic = {
    a: a - 2 * c,
    b: b + 3,
    c: a + b -2,
}
````

is valid even though `c` doesn't appear in the equation for `c`. Sure I could swap the keys `a` and `c`, but I shouldn't have to.

**Comment by tinosulzer** [comment]
Yeah we don't *need* the check, and there are other checks that would catch most cases that would cause problems anyway. Let's get rid of it
