### ISSUE TITLE
Expose additional parameters in DFN half cell

### ISSUE THREAD

**Issue by molel-gt** [pybamm-team/PyBaMM#1527]
**Summary**
Expose additional variables/parameters that are already computed, and make them accessible in the solution.

 **Motivation**
Ratio of diffusion times to discharge times are already computed, but not exposed in variables. So is the superficial current density.

**Additional context**
Parameters to add include:

- Current density [A.m-2]
- Electrolyte transport to discharge time
- Solid diffusion to discharge time
- Divergence in current density

It would likely be useful to expose all variables that are not user-inputs.

**Comment by molel-gt** [comment]
@tinosulzer I would like to pick this up, but wanted to confirm with you first.

**Comment by tinosulzer** [comment]
Yep go for it

**Comment by tinosulzer** [comment]
Closed since full DFN can now do half-cell simulations
