### ISSUE TITLE
Solving 2D pouch model with explicit experiment fails

### ISSUE THREAD

**Issue by DavidMStraub** [pybamm-team/PyBaMM#1547]
**Describe the bug**

Running the default pouch model with a manually specified `Experiment` causes the Casadi solver to fail.

**To Reproduce**

```python
import pybamm
options = {"cell geometry": "pouch", "thermal": "x-lumped", "dimensionality": 2}
model = pybamm.lithium_ion.SPMe(options=options)
experiment = pybamm.Experiment([
    "Discharge with 5 C for 1 minute"
])
sim = pybamm.Simulation(model, experiment=experiment)
sim.solve()
```

**Expected behaviour**
Solve

**Screenshots**

```
RuntimeError: .../casadi/core/function_internal.hpp:1257: Input 1 (i1) has mismatching shape. Got 11-by-1. Allowed dimensions, in general, are:
 - The input dimension N-by-M (here 2-by-1)
 - A scalar, i.e. 1-by-1
 - M-by-N if N=1 or M=1 (i.e. a transposed vector)
 - N-by-M1 if K*M1=M for some K (argument repeated horizontally)
 - N-by-P*M, indicating evaluation with multiple arguments (P must be a multiple of 1 for consistency with previous inputs)
 - ```

**Comment by tinosulzer** [comment]
This will fix it for now
```python3
sim.solve(calc_esoh=False)
```
also `solver=pybamm.CasadiSolver("fast with events")` might be a bit faster

**Comment by DavidMStraub** [comment]
Hi @tinosulzer, I just ran into a very similar issue (`Input 1 (i1) has mismatching shape. Got 141-by-1.`) when doing a simulation with `"lithium plating": "irreversible"`. Setting `calc_esoh=False` didn't solve it. I'm using current `develop`. Any idea how to fix it?

**Comment by DavidMStraub** [comment]
I'll open a new issue with a minimal example.
