### ISSUE TITLE
Dimensions interchanged in 2D processed variable

### ISSUE THREAD

**Issue by DavidMStraub** [pybamm-team/PyBaMM#1554]
**Describe the bug**

I'm plotting a 2D processed variable and finding that when I specify the spatial variables y and z, they seem to be interchanged.

**To Reproduce**
Steps to reproduce the behaviour:

```python
import pybamm
options = {"cell geometry": "pouch", "thermal": "x-lumped", "dimensionality": 2, "current collector": "potential pair"}
model = pybamm.lithium_ion.SPMe(options=options)
experiment = pybamm.Experiment(["Discharge with 3 C for 10 seconds"])
solver = pybamm.CasadiSolver("fast")
sim = pybamm.Simulation(model, experiment=experiment, solver=solver)
sim.solve()
sim.plot(["X-averaged Ohmic heating [W.m-3]"], spatial_unit="m")
print(sim.solution["X-averaged Ohmic heating [W.m-3]"](t=10, y=0.147, z=0.137))
print(sim.solution["X-averaged Ohmic heating [W.m-3]"](t=10, y=0.207, z=0.1))
```

![grafik](https://user-images.githubusercontent.com/10965193/126126098-4f4cb9b3-50ab-4006-8c33-3272781fc753.png)

```
array(9830.35092739)
array(17052.65235706)
```

**Expected behaviour**

The first printed value should be directly on top of the positive tab, which - as expected and shown in the plot - has a larger heat generation. The second printed value, which has the large heat generation, is a (y, z) point on the right edge of the pouch. So it seems that y and z are interchanged.

**Comment by rtimms** [comment]
Looks like this was an issue with how the entries of variables that were discretised using FEM were indexed. I have opened a PR with a fix. @DavidMStraub could you checkout the branch and double-check this works as expected please?

**Comment by DavidMStraub** [comment]
Yes, looks good (for the case I was considering), thanks!
