### ISSUE TITLE
installing sckits.odes bug

### ISSUE THREAD

**Issue by martinjrobins** [pybamm-team/PyBaMM#1560]
**Describe the bug**
Trying to install scikits.odes according to [docs](https://pybamm.readthedocs.io/en/latest/install/GNU-linux.html#scikits-odes-label) results in an error

**To Reproduce**
Steps to reproduce the behaviour:

```
mrobins-XPS-15-9570: |env|  ~/git/PyBaMM  |issue-1477-idaklu-send ?:6 ✗|
→ pybamm_install_odes --install-sundials
/home/mrobins/git/PyBaMM/pybamm/scikits_odes_setup.log
2021-07-22 08:08:42,685 - [INFO] install_odes.main(123): Starting scikits.odes setup
usage: pybamm_install_odes [-h] [--sundials-libs SUNDIALS_LIBS] [--install-dir INSTALL_DIR]
pybamm_install_odes: error: unrecognized arguments: --install-sundials
```

**Expected behaviour**
scikits.odes is installed

**Comment by Saransh-cpp** [comment]
`--install-sundials` was removed a long time ago but the documentation was not updated. It should be good to go now, all the bugs were fixed and the documentation was updated.
