### ISSUE TITLE
Possible bug in reaction limited SEI model

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/PyBaMM#1564]
See weird stepping in capacity vs cycle number in [this tweet](https://twitter.com/saranshchopra7/status/1413014358901149698)

**Comment by rtimms** [comment]
Could be numerical though, the scale is very small (note the *1e-5 in the capacity plot)

**Comment by tinosulzer** [comment]
It's definitely a problem with the eSOH algorithm for calculating capacity, since LLI is linear
