### ISSUE TITLE
Add Discharged energy [W.h] as variable

### ISSUE THREAD

**Issue by TomTranter** [pybamm-team/PyBaMM#1575]
**Summary**
Add Discharged energy [W.h] as variable

 **Motivation**
Like discharged capacity but using current * voltage. Useful for performance metrics and minimal overhead

**Comment by tinosulzer** [comment]
Took a look at how you started this. You don't need to create a new `pybamm.Variable` for discharged energy, just calculate it as a post-processing step

**Comment by TomTranter** [comment]
Ok - is there an official way to do this? Or you just mean manually with the entries

**Comment by tinosulzer** [comment]
add it to this function somewhere https://github.com/pybamm-team/PyBaMM/blob/51ee22aece7389434750a7f49ed1252fe4a3a9de/pybamm/models/full_battery_models/base_battery_model.py#L828

**Comment by tinosulzer** [comment]
My bad, you do need an additional variable
