### ISSUE TITLE
Switch to calendar versioning

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#1583]
Look into automating some of the updates for releases

**Comment by brosaplanella** [comment]
Which format of calendar versioning do we want to use? [Here](https://calver.org/) are different examples. Should we do YY.MM.micro? Or just YY.MM?

**Comment by tinosulzer** [comment]
I don't think we need micro. Realistically we are not going to start pushing bug fix releases. We can always add micro later if necessary

**Comment by tinosulzer** [comment]
21.08 slightly better I think

**Comment by tinosulzer** [comment]
tbh I'm now on the fence about 2021.08 haha

**Comment by brosaplanella** [comment]
I prefer 21.08 or 21.8 as 2021.08 is a bit too long IMO. There is the question of what you want to do when we hit year 2100, but I think we won't have to answer it hahaha
