### ISSUE TITLE
Update reference to scipy docs

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/PyBaMM#1584]
Update scipy reference in `intersphinx_mapping`. Currently getting this error 
```
Warning, treated as error:
failed to reach any of the inventories with the following issues:
intersphinx inventory 'http://docs.scipy.org/doc/scipy/reference/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 404 Client Error: Not Found for url: https://docs.scipy.org/doc/scipy/reference/objects.inv
Checking if docs can be built.
FAILED
ERROR: InvocationError for command /home/runner/work/PyBaMM/PyBaMM/.tox/doctests/bin/python run-tests.py --doctest (exited with code 2)```

**Comment by tinosulzer** [comment]
intersphinx inventory has moved: http://matplotlib.org/objects.inv -> https://matplotlib.org/objects.inv
intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
intersphinx inventory has moved: http://docs.scipy.org/doc/numpy/objects.inv -> https://numpy.org/doc/stable/objects.inv
intersphinx inventory has moved: http://www.sphinx-doc.org/en/stable/objects.inv -> https://www.sphinx-doc.org/en/master/objects.inv
