### ISSUE TITLE
Simulate the battery model with power (current*voltage) as input

### ISSUE THREAD

**Issue by yunliubc** [pybamm-team/PyBaMM#1593]
I am new to the PyBaMM. I wondering how to simulate the battery model using power as input. In the tutorial,  the "Current function [A]" is used as input. If it is possible to use power as input to simulate the battery model. Thanks.

**Comment by tinosulzer** [comment]
```python3
import pybamm
experiment = pybamm.Experiment(["Discharge at 4W until 3.3 V"])
model = pybamm.lithium_ion.DFN()
sim = pybamm.Simulation(model, experiment=experiment)
sim.solve()
sim.plot()
```
