### ISSUE TITLE
Changable parameters 

### ISSUE THREAD

**Issue by Scottmar93** [pybamm-team/PyBaMM#161]
**Summary**
Add ability to have parameter values that change without recreating the tree. 

- Add an extra subclass of symbol `ChangableParameter`. 
- Do not insert any values for `ChangableParameters` when we `params.process(model)` 
- During `params.process(model)` replace each `ChangableParameter` by `changable_parameters[ChangableParameters]` (a dict with keys that are the changable paramerters).
- add an extra optional input to `model.concatenated_rhs.evaluate(t, y, changable_params)` which is a dict of the changed parameters with their values which will update the `changable_parameters` dict. 
- create a model.set_param() which takes in a dict of parameter values and puts them into the correct location in the changable_params vector

 **Motivation**
 Allows parameters to be changed easily without rebuilding the tree. Efficiently changing parameter values is a requirement of the control community. 

Time dependent functions could also be implemented within this approach. 

**Questions** 
It would be possible to have this as the default approach for setting all parameters. We should consider this as it means someone doesn't need to rebuild the discretisation if they realise afterwards that they want to change a parameter value. I also don't think that this will slow thing down to any great extent. We would also only pass in the parameters values that are changed an update the parameters dict. 
What are peoples thought on this?

**Comment by martinjrobins** [comment]
after meeting, descided to 
1. When Parameter is replaced by Scalar, the Scalar node inherits the name
2. add a function to Symbol that iterates through the tree and changes all Scalar nodes to a new value

**Comment by tinosulzer** [comment]
Sounds good. We will just need to be careful that scalars don't get accidentally labelled as constant by `is_constant`, in which case they might accidentally get converted to vectors and the name lost (e.g. [here](https://github.com/tinosulzer/PyBaMM/blob/9f504cdd70ba867d5b33a0095ab42f541ef81ad6/pybamm/discretisations/discretisation.py#L255)):
```python3
if new_symbol.is_constant():
      value = new_symbol.evaluate()
      return pybamm.Vector(value)
```
