### ISSUE TITLE
Update jax version

### ISSUE THREAD

**Issue by brosaplanella** [pybamm-team/PyBaMM#1625]
**Describe the bug**
When updating jax to most recent version (from 0.2.12 to 0.2.19) an error appears. This is on line 1027 of `jax_bdf_solver.py`:
```python3
def is_float(c):
    return dtypes.issubdtype(dtypes.dtype(c), jnp.inexact)
```
The issue is that `dtypes.dtype` does not exist so I get
```bash
  File "/home/ferranbrosa/PyBaMM/pybamm/solvers/jax_bdf_solver.py", line 1027, in is_float
    return dtypes.issubdtype(dtypes.dtype(c), jnp.inexact)
AttributeError: module 'jax.dtypes' has no attribute 'dtype'
```

This issue requires editing the interface of `jax_bdf_solver.py` to match that of [https://github.com/google/jax/blob/main/jax/experimental/ode.py](https://github.com/google/jax/blob/main/jax/experimental/ode.py)

**To Reproduce**
Steps to reproduce the behaviour:
1. Update jax to 0.2.19
2. Run `test_jax_solver.py`

**Comment by priyanshuone6** [comment]
I tried using jax and jaxlib with all the recently released versions and I am getting this error
```python
File "/home/runner/work/PyBaMM/PyBaMM/pybamm/solvers/jax_bdf_solver.py", line 68, in <module>
    @jax.partial(jax.custom_vjp, nondiff_argnums=(0, 1, 2, 3))
AttributeError: module 'jax' has no attribute 'partial'
```
It passes all the tests except for Python 3.9

See https://github.com/priyanshuone6/PyBaMM/actions/runs/2058307644

**Comment by brosaplanella** [comment]
What should we do with this? We are now quite behind in terms of jax versions, is that an issue?
