### ISSUE TITLE
The simulation terminated before the lower cut-off voltage reached

### ISSUE THREAD

**Issue by Leonhardup** [pybamm-team/PyBaMM#1637]
When I changed the C-rate, the  terminal voltage can not reach the lower cut-off voltage but the simulation terminated before the setting solve time. 

![image](https://user-images.githubusercontent.com/89958739/131781410-be42084d-9ba2-4ee6-b80f-85026a5e884e.png)
 
any ideas about this issues?

**Comment by Leonhardup** [comment]
the lower cut-off voltage is 2.5 V, but the voltage terminated above 3.0V.
![image](https://user-images.githubusercontent.com/89958739/131781604-11955a66-8d90-42dd-80e4-c394f2bfae9b.png)

**Comment by tinosulzer** [comment]
Probably similar to #1632 
Can you print `sim.solution.termination`?

**Comment by Leonhardup** [comment]
> Probably similar to #1632
> Can you print `sim.solution.termination`?

Hello, tinosulzer! I printed the sim.solution.termination as "Termination:event: Maximum positive particle surface concentration".
Do you have some ideas on my issue?

**Comment by tinosulzer** [comment]
At this high C-rate (for an energy cell which is Chen2020) the simulation stops before the cut-off voltage is reached because the positive particles fill up first. But if you update to the latest version (on the develop branch) it might give you a different result

**Comment by Leonhardup** [comment]
> At this high C-rate (for an energy cell which is Chen2020) the simulation stops before the cut-off voltage is reached because the positive particles fill up first. But if you update to the latest version (on the develop branch) it might give you a different result

Great, you mean it can be addressed by updating the latest Pybamm version?

**Comment by tinosulzer** [comment]
Possibly, but the pypi release is not working right now, so you will have to clone the repository and install from source

**Comment by Leonhardup** [comment]
> Possibly, but the pypi release is not working right now, so you will have to clone the repository and install from source

Thank you! I have cloned the repository by desktop, and how can I install from source?

**Comment by tinosulzer** [comment]
https://pybamm.readthedocs.io/en/latest/install/install-from-source.html

**Comment by tinosulzer** [comment]
any luck @Leonhardup ?

**Comment by Leonhardup** [comment]
> any luck @Leonhardup ?

Hello, Tinosulzer! I have a problem in installing the latest version Pybamm from source in macOS . The CMake got wrong with "Bad CMake executable "". Is it installed or settings contain the correct path (cmake.cmakePath)?" When could  the latest pybamm be released?

**Comment by tinosulzer** [comment]
Which step is this?

**Comment by Leonhardup** [comment]
> Which step is this?

Manual installing the build-time requirements, doesn't it use VS code?

**Comment by tinosulzer** [comment]
If you did `brew install sundials` and installed pybind11 you don't need to do that step. Try just moving on to `tox -e dev`

**Comment by tinosulzer** [comment]
Can you try updating to the latest version that was just released on pypi?

**Comment by Leonhardup** [comment]
> Can you try updating to the latest version that was just released on pypi?
Thanks for you attention! Is there a get-pip.py file to install the latest version?

**Comment by Leonhardup** [comment]
> Can you try updating to the latest version that was just released on pypi?

![image](https://user-images.githubusercontent.com/89958739/133329526-c71f7941-6341-4705-a0e5-6e7f558ac15f.png)
Is it successfully installed?

**Comment by tinosulzer** [comment]
What does `pip show pybamm` give you?

**Comment by Leonhardup** [comment]
> What does `pip show pybamm` give you?

![image](https://user-images.githubusercontent.com/89958739/133331048-af953e1b-6852-4b34-8766-403e10cd4420.png)
It is 21.8 version. Right?

**Comment by tinosulzer** [comment]
Yes. Does it reach cut-off voltage now?

**Comment by Leonhardup** [comment]
> Yes. Does it reach cut-off voltage now?

Yes, it can reach the lower cut-off voltage, but at some C-rate, the discharge terminal curve is a little weird, as the picture shows, the C-rate is 2C. Do you know why?
![image](https://user-images.githubusercontent.com/89958739/133343185-6432d483-eb23-4344-8cda-dc5760736f6c.png)

**Comment by tinosulzer** [comment]
This is probably the point where the electrolyte was depleted, can you plot "Electrolyte concentration"

**Comment by Leonhardup** [comment]
> This is probably the point where the electrolyte was depleted, can you plot "Electrolyte concentration"

Hello, Tinosulzer! As for a single particle model, whose parameters set do you think should be the best for simulation?

**Comment by tinosulzer** [comment]
You need to choose the appropriate parameter set to match your experimental data. If you don't have any experimental data then Chen2020 is a good place to start. 

It sounds like this issue is fixed, I'm going to close it but can reopen if you have more questions
