### ISSUE TITLE
Automate baseline in vcpkg

### ISSUE THREAD

**Issue by priyanshuone6** [pybamm-team/PyBaMM#1646]
Automatically update the baseline in vcpkg-configuration.json with the latest commit id from https://github.com/pybamm-team/sundials-vcpkg-registry

**Comment by priyanshuone6** [comment]
@tinosulzer I have created the workflow and the script to update the baseline, in which folder should I place the script?

**Comment by tinosulzer** [comment]
maybe in `.github`?

**Comment by priyanshuone6** [comment]
And the tests?

**Comment by priyanshuone6** [comment]
Should I add everything in scripts

**Comment by tinosulzer** [comment]
Can you make a draft PR? Not sure exactly what is in the script

**Comment by tinosulzer** [comment]
I think where you've put it is good
