### ISSUE TITLE
Key error for cycling_ageing example

### ISSUE THREAD

**Issue by PippaVossen** [pybamm-team/PyBaMM#1648]
**Describe the bug**
When running the example script ``` cycling_ageing.py ``` a key error is raised where ``` 'Lithium metal partial molar volume [m3.mol-1]' not found ```

How can I solve this issue?

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to ``` PyBaMM/examples/scripts/cycling_ageing.py ```
2. Run the file
3. See error below

```
File "C:\Users\pippa\Research\Code\cycling_ageing.py", line 67, in <module>
    sim.solve(solver=pb.CasadiSolver(mode="safe"))
    
KeyError: "'Lithium metal partial molar volume [m3.mol-1]' not found. Best matches are ['Inner SEI partial molar volume [m3.mol-1]', 'Outer SEI partial molar volume [m3.mol-1]', 'Lithium interstitial reference concentration [mol.m-3]']"
```

**Additional context**
A similar issue has been raised for the example script 'calendar_ageing.py' (view the discussion [here](https://github.com/pybamm-team/PyBaMM/issues/1610)), here it seemed to be a version issue between the ``` main ``` and ``` develop ``` branches. However, for me, the examples in both branches raise the same Key Error.

**Comment by tinosulzer** [comment]
Which version are you using?

**Comment by PippaVossen** [comment]
![image](https://user-images.githubusercontent.com/62235657/132696026-5dfb425f-f006-4449-acc8-fc398d4a3036.png)

**Comment by tinosulzer** [comment]
This script should work with v0.4.0: https://github.com/pybamm-team/PyBaMM/blob/v0.4.0/examples/scripts/cycling_ageing_yang.py
