### ISSUE TITLE
Allow  running of simulations of Li metal batteries with DFN

### ISSUE THREAD

**Issue by molel-gt** [pybamm-team/PyBaMM#1659]
**Summary**
Expose li_metal.DFN model for all-solid-state battery and remove stub that prevents running of simulations for DFN Half Cell.

 **Motivation**
 Why are we doing this? What use cases does it support? What is the expected outcome?

**Additional context**

**Comment by tinosulzer** [comment]
This was fixed in #1514, just not for experiments. `DFN({"working electrode": "positive"})` should be used instead.
