### ISSUE TITLE
Temperature dependence in SEI models

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#1695]
- For the EC reaction limited, reaction limited, and interstitial diffusion limited, multiply the exponent by the following factor (dimensionless 1/T):
```python
T = variables["Negative electrode temperature"]
prefactor = 1 / (1 + self.param.Theta * T)
```
- Add arrhenius dependency to diffusivity in ec reaction limited and solvent diffusion limited (I don't know what the arrhenius factor should be)
- Arrhenius dependence for the conductivity of the SEI in electron migration limited

**Comment by soma2000-lang** [comment]
Working on this issue@tinosulzer

**Comment by soma2000-lang** [comment]
@tinosulzer  I will be submitting a proposal for the idea "Documentation" ,for GSOC22 under pybamm.
I have a doubt about how to know what the arrhenius dependency should be.
It would be great to be mentored by you and  other mentors

**Comment by soma2000-lang** [comment]
@tinosulzer Can you please tell me where SEI model file is, I am having difficulty in finding them.

**Comment by tinosulzer** [comment]
https://github.com/pybamm-team/PyBaMM/blob/develop/pybamm/models/submodels/interface/sei/sei_growth.py

**Comment by soma2000-lang** [comment]
@tinosulzer  thanks
