### ISSUE TITLE
P2D electrochemical simulation of Battery 

### ISSUE THREAD

**Issue by soumyadeeproy12** [pybamm-team/PyBaMM#1698]
Hey Authors/developers, 

I was just wondering if PyBaMM has it's own P2D model based function for battery electrochemical modeling. Right now, in COMSOL it's just very much inbuilt feature and if similar kind of can be built inside the PyBaMM, it would make engineer's life a lot easier. Right now, I'm trying to design similar model with PyBaMM only, if it happens to be there already, then please guide me to it, otherwise it can be a very useful feature.

**Comment by tinosulzer** [comment]
Yes, this is the same as the DFN (Doyle-Fuller-Newman) model in pybamm, just under a different name
