### ISSUE TITLE
Error when running DFN half-cell without a lithium plating parameter set

### ISSUE THREAD

**Issue by brosaplanella** [pybamm-team/PyBaMM#1719]
- PyBaMM version - `$ python -m pip show pybamm`: 21.9
- Python version - `$ python --version`: any

**Describe the bug**
At the moment, if you try to use the PyBaMM half-cell model with a parameter set that doesn't include lithium plating (like the default one) it throws a rather non-informative error:
```bash
KeyError: KeyError("'Typical plated lithium concentration [mol.m-3]' not found. Best matches are ['Typical electrolyte concentration [mol.m-3]', 'Bulk solvent concentration [mol.m-3]', 'Lithium interstitial reference concentration [mol.m-3]']")
```

It would be good if the error was more informative.

This was identified by @sklein-ise in #1717.

**Comment by brosaplanella** [comment]
Then this would be a very good first issue. @sklein-ise let us know if you want to give it a go as well.

**Comment by tinosulzer** [comment]
Default parameter set for a half-cell model is now "Xu2019"

**Comment by chenzhao-py** [comment]
Hello,

Could you please revisit to this issue? what should we do for half cell when we have customized parameter sets?

**Comment by tinosulzer** [comment]
Either copy any missing parameters from [Xu2019](https://github.com/pybamm-team/PyBaMM/blob/develop/pybamm/input/parameters/lithium_ion/Xu2019.py) or use very high values so that the overpotential from the lithium metal anode is zero
```python
{
        "Negative electrode OCP [V]": 0.0,
        "Negative electrode conductivity [S.m-1]": 1e7,
        "Typical plated lithium concentration [mol.m-3]": 76900.0,
        "Exchange-current density for plating [A.m-2]": 1000,
        "Negative electrode thickness [m]": 1e-5,
    }
   ```
