### ISSUE TITLE
Make summary variables an attribute of the model

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/PyBaMM#1726]
At the moment the simulation stores some summary variables, but these are hardcoded into [solution](https://github.com/pybamm-team/PyBaMM/blob/develop/pybamm/solvers/solution.py#L796). It would be nice if the list of summary variables were defined on the model so that different models could have different summary variables, or users could define their own list/add their own variables. Might need some checks (e.g. need to be scalars).

**Comment by tinosulzer** [comment]
When doing so, also need to check that every variable in the list is also a variable of the model
