### ISSUE TITLE
solid phase phase tortuosity is calculated with bruggeman coefficient of electrolyte

### ISSUE THREAD

**Issue by dion-w** [pybamm-team/PyBaMM#1734]
- PyBaMM version - `$ python -m pip show pybamm`: not sure, since i "git fetch" from github repo to hardrive now and then, last git fetch was on 24th of september 2021.
- Python version - `$ python --version`: 3.9.7

**Describe the bug**
In the file bruggeman-tortuosity a clear distinction between Electrolyte and Electrode is made via an if-elif statement. Yet in both parts of the statement the bruggeman coefficient of the electrolyte phase is used (compare line 41 with line 51).

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'pybamm/models/submodels/tortuosity/bruggeman_tortuosity.py'
2. Compare "if" statement starting at line 31 and the "elif" statement starting at line 42. Line 41 and 51 are the same but they shouldn't be. They both calculate tortuosities with their correct respective volume fraction but use the bruggeman coefficient of the electrolyte ("param.b_e_n"). This way the tortuosity of the electrode (line 51) is calculated by putting the active material volume fraction to the power of the bruggeman coefficient of the electrolyte phase. Instead the tortuosity of the electrode should be put to the power of the bruggeman coefficient of the electrode phase.

**Expected behaviour**
I expected the tortuosity of electrode and electrolyte to be scaled differently by their bruggeman coefficients but this is not the case.

**Additional context**
Error can be fixed by 

- replacing "param.b_e_n" in line 47 by "param.b_s_n" and
- replacing "param.b_e_p" in line 51 by "param.b_s_p"

**Comment by tinosulzer** [comment]
Yes, good catch thanks. If you could open a PR for this alongside #1714 that would be great.
