### ISSUE TITLE
Specific Energy calculation from DFN model

### ISSUE THREAD

**Issue by soumyadeeproy12** [pybamm-team/PyBaMM#1744]
Does DFN model solution give specific energy calculation for each data points in PyBamm?

**Comment by tinosulzer** [comment]
What do you mean by "data points" here?

**Comment by manjunathnilugal** [comment]
@tinosulzer , I think he is asking about the specific energy calculation of the  cell at every voltage data points, i.e
de/dt = v * i(_applied_), for the specific time window.
@soumyadeeproy12 , Kindly correct if I am wrong

**Comment by tinosulzer** [comment]
Fixed by #1969

**Comment by soumyadeeproy12** [comment]
Hey 
I've done the ```model = pybamm.lithium_ion.DFN("calculate discharge energy" =='true')``` . Now I want to see the data of discharge, I meant data for the simulated model.
