### ISSUE TITLE
listing/printing default values used

### ISSUE THREAD

**Issue by synjon-symthe** [pybamm-team/PyBaMM#1756]
Hi PyBaMMers:

I am a new user of PyBaMM.  I was looking at some of the example tutorials and I see that of the process parameters/geometry are set as default. Is there a place where these default values are listed?  I would be helpful to newbies like me who are just getting started.

Thanks

Synjon

**Comment by synjon-symthe** [comment]
Thanks, Valentin.  I was able to get an output of all parameters with print(param). I will try out your method as well. Can any of these values be over-ridden by using the appropriate string  - for example to change the default ambient temperature to 300K does one do
parameter_values["Ambient temperature [K]"]=300

My apologies for asking these seemingly easy question.
Synjon
Thanks

**Comment by tinosulzer** [comment]
Yes, that is correct
