### ISSUE TITLE
Add cycle number and charge/discharge tags in solution data

### ISSUE THREAD

**Issue by pogechi** [pybamm-team/PyBaMM#1758]
**Summary**
Automatically provide information on cycle number and whether the data describe charge / discharge

 **Motivation**
After running an experiment, some data post-processing is needed to append information on cycle number and charge/discharge, which can be useful for further data analysis. These features could be automatically extracted and included in sol.data

**Additional context**
 Using Pandas and Numpy, I have added a couple of lines to add these features after importing the data into a DataFrame, although I do realize they may not fully describe all existing use cases for more complex charge/discharge cycles:

`df["Charge/Discharge"] = np.where(df["Current [A]"] >=0, "D", "C")`
`df["Cycle number"] = np.ceil(df["Charge/Discharge"].ne(df["Charge/Discharge"].shift()).cumsum() / 2).astype("int32")`

**Comment by pogechi** [comment]
> The way `solution.data` is constructed is not super straightforward, it has to evaluate pybamm symbols (variables). We could add a variable which is the sign of the current. Adding a variable for cycle number is harder

Understood, thank you for the quick feedback! Cycle number is visible when running a simulation, could that be appended somehow to the final data? The workaround I have found is easy to implement in the scenario I deal with, but I understand a general solution may be less straightforward.

**Comment by tinosulzer** [comment]
It can't be appended to `solution.data`, it would be too hacky and cause weird errors elsewhere if someone tried to use it like other variables. But post-processing using `solution.cycles` is easy for a general solution. For example, you can use a for loop, something like
```python
df_all = ... # initialize df
for cycle_number, cycle_data in enumerate(solution.cycles):
   df = ... # construct new df from cycle_data
   df["Cycle number"] = cycle_number + 1 # set the cycle number starting at 1
   df_all = ... # append new df
```
In practice I find that the point of labeling cycles is to be able to easily split them; `solution.cycles` is already split for you. What is the use case for having all the data in a single `df` with cycle numbers labelled?

**Comment by pogechi** [comment]
> It can't be appended to `solution.data`, it would be too hacky and cause weird errors elsewhere if someone tried to use it like other variables. But post-processing using `solution.cycles` is easy for a general solution. For example, you can use a for loop, something like
> 
> ```python
> df_all = ... # initialize df
> for cycle_number, cycle_data in enumerate(solution.cycles):
>    df = ... # construct new df from cycle_data
>    df["Cycle number"] = cycle_number + 1 # set the cycle number starting at 1
>    df_all = ... # append new df
> ```
> 
> In practice I find that the point of labeling cycles is to be able to easily split them; `solution.cycles` is already split for you. What is the use case for having all the data in a single `df` with cycle numbers labelled?

I agree the solutions you have listed are useful for analysing the data and are definitely applicable in my case. 

What I'm trying to get at, is to have the final data coming from, e.g., an ageing simulation, to resemble as much as possible data coming from a battery cycler, where usually cycle number and charge/discharge labels are present in the raw file. 

I saw that the cycle number is shown when the simulation is running and thought it could be easy to include that among the other variables right off the bat.

Thank you anyway for the helpful remarks!
