### ISSUE TITLE
Prada2013 LFP Cell data

### ISSUE THREAD

**Issue by rmahbub** [pybamm-team/PyBaMM#1811]
I am a little confused if the active material fraction is correct in the CSV file of LFP positive electrode (Prada 2013). For example, for Prada2013 (A123 M1A LFP Cell) positive active material fraction is 0.28 and porosity fraction is 0.12 in the csv file. Lain2019 in his paper says that the cathode composition in M1A cell is active:binder:carbon=79:11:10. Can you comment on this mismatch

**Comment by tinosulzer** [comment]
The values there are fitted to the data from the Severson 2019 Nature Energy paper. We should change them to the ones from the Lain paper. Can you open a PR doing this?
