### ISSUE TITLE
Update Issue templates

### ISSUE THREAD

**Issue by priyanshuone6** [pybamm-team/PyBaMM#1823]
Update existing Issue templates with GitHub Issue forms
Demo - https://github.com/github/docs/issues/new?assignees=&labels=content&template=improve-existing-docs.yaml

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

**Comment by oneamanish** [comment]
see my pull req.

**Comment by Vaibhav-Chopra-GT** [comment]
Can I work on this issue

**Comment by priyanshuone6** [comment]
Of course, thank you!

**Comment by priyanshuone6** [comment]
@Vaibhav-Chopra-GT The issue template of PyBaMM would be very similar to that of liionpack (See https://github.com/pybamm-team/liionpack/tree/main/.github/ISSUE_TEMPLATE)
