### ISSUE TITLE
idklu solver for `convert_to_casadi=True`

### ISSUE THREAD

**Issue by martinjrobins** [pybamm-team/PyBaMM#1863]
**Summary**

The current idklu solver goes back to python whenever it needs to calculate the rhs, algebraic or event equations. It also runs very slow when using `convert_to_casadi=True`. This issue aims to develop a new idklu solver that directly calls casadi functions from C++, with ideally no memory copying to/from casadi arrays

 **Motivation**

We want to get the superior event handling capabilities of the ida solvers with efficient casadi evaluation of equations

**Comment by martinjrobins** [comment]
this largely seems to be working ok now and scaling as expected. Its faster than the casadi solver with events, but there are still some things to do to speed it up further:
- serialising the casadi functions takes a fair bit of time, need to do this in the solver setup, not the solve itself
- we're allocating memory for return vectors in the solve, again this could be done in solver setup
- also we initialise ida_mem and everything every time, could do this once when solver is created, or only on the 1st solve etc
- need to play around with ida sundials settings: create an options dict to pass to the solver to choose various things. A major addition here would be to look at the iterative solvers

**Comment by tinosulzer** [comment]
> we're allocating memory for return vectors in the solve, again this could be done in solver setup

On this subject, an idea to consider is to have the option to calculate some scalar variables (voltage would be the main one but could be anything) at each time step, and then not store the `y` vector.

**Comment by tinosulzer** [comment]
> A major addition here would be to look at the iterative solvers

Iterative solvers only start to outperform direct solvers at relatively large matrix sizes, right? (don't know how large)

**Comment by martinjrobins** [comment]
Yes, iterative solvers can give speed benefits at the very large matrix sizes, as long as you have a decent preconditioner (i.e. a good approximation to the jacobian that you can solve easily).

**Comment by martinjrobins** [comment]
This is largely finished, see pr #2002, here is my todo list for subsequent issues:
- [ ] we're allocating memory for return vectors in the solve, this could be done in solver setup
- [ ] we initialise ida_mem and everything every time, could do this once when solver is created, or only on the 1st solve etc
- [ ] create an options dict to pass to the solver, e.g. option to print solver stats,  don't/do use jacobian
- [ ] add option to use iterative solvers
- [ ] add option to use other linear solvers in ida
- [ ] add option to use dense jacobian
- [ ] benchmarks for all of the above solver options
- [ ] investigate if we need to densify the rhs_algebraic casadi evaluation, could it return a sparse vector?
- [ ] investigate if constructing a new casadi function for the residual (rather than doing it manually in c++) is faster
- [ ] investigate if constructing a new casadi function for the sensitivity calculations (rather than doing it manually in c++) is faster
- [ ] we calculate consistent initial conditions at the start of the idklu solve, so we might not need to do it in the BaseSolver setup
