### ISSUE TITLE
test numba to speed up `convert_to_python=True`

### ISSUE THREAD

**Issue by martinjrobins** [pybamm-team/PyBaMM#1864]
**Summary**

Might be faster using `convert_to_python` if we use numba to compile it....? would help with the idklu solver. The other option to speed this one up is #1863. But this is easier so I want to give this one a go first

 **Motivation**

Trying to speed up the ida solver so we can use its superior event handling

**Comment by martinjrobins** [comment]
some minima support for csr matrix for numba, see https://github.com/numba/numba-scipy/issues/29

**Comment by martinjrobins** [comment]
could try this: http://csr.lenskit.org/en/stable/

**Comment by kratman** [comment]
@martinjrobins Is this relevant anymore?
