### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by Saransh-cpp** [pybamm-team/PyBaMM#1882]
The tests are failing with an error -
```
File "/tmp/pip-build-env-uklwrsnk/overlay/lib/python3.9/site-packages/numpy/distutils/command/build_ext.py", line 380, in build_extension
      extra_cflags = ext.extra_c_compile_args or []
  AttributeError: 'Extension' object has no attribute 'extra_c_compile_args'
  ----------------------------------------
  ERROR: Failed building wheel for scikits.odes
Failed to build scikits.odes
ERROR: Could not build wheels for scikits.odes, which is required to install pyproject.toml-based projects
```

I tried looking it up and found an issue (https://github.com/bmcage/odes/issues/130) in the `odes` repository related to the `distutils` module of `numpy`. The latest `numpy` [release](https://github.com/numpy/numpy/releases/tag/v1.22.0) has a "Compatibility note" section that says -
### Distutils forces strict floating point model on clang
NumPy now sets the -ftrapping-math option on clang to enforce correct
floating point error handling for universal functions. Clang defaults to
non-IEEE and C99 conform behaviour otherwise. This change (using the
equivalent but newer -ffp-exception-behavior=strict) was attempted in
NumPy 1.21, but was effectively never used.

I am not sure if this is the root problem and I couldn't find a fix or any related issue on GitHub.

**Comment by priyanshuone6** [comment]
This might be relevant https://github.com/pybamm-team/PyBaMM/pull/1355

**Comment by tinosulzer** [comment]
Thanks for investigating, I commented on the issue asking if we should just skip scikit-odes tests for now (python 3.7 is still working, so we could just do the coverage using that)
