### ISSUE TITLE
Numbering issue in `CONTRIBUTING.md

### ISSUE THREAD

**Issue by Vaibhav-Chopra-GT** [pybamm-team/PyBaMM#1941]
### PyBaMM Version

develope

### Python Version

--

### Describe the bug

There is a numbering issue in `CONTRIBUTING.md`

![Screenshot 2022-02-16 232824](https://user-images.githubusercontent.com/92637595/154326908-c07bfa9f-e417-42c0-a84e-da42a6cf42d5.png)

### Additional context

This should be an easy fix can I work on this?

**Comment by soma2000-lang** [comment]
Working on this issue

**Comment by priyanshuone6** [comment]
Yes, go ahead
