### ISSUE TITLE
Automatic release fails to check date

### ISSUE THREAD

**Issue by brosaplanella** [pybamm-team/PyBaMM#1953]
The automatic GitHub release action failed because the date check returned that `day < 20`. See [this action](https://github.com/pybamm-team/PyBaMM/runs/5362924154?check_suite_focus=true) for more details.

**Comment by priyanshuone6** [comment]
This is weird as [this](https://github.com/pybamm-team/PyBaMM/runs/5362924154?check_suite_focus=true#step:4:10) line returns 28 which should skip the if condition

**Comment by priyanshuone6** [comment]
I'll look into this, for now I am manually creating the release
