### ISSUE TITLE
automatic differentiation

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/PyBaMM#197]
Automatically compute the jacobian for use in the solver. This speeds up sundials, and gives better convergence etc.  One option is to use `autograd`. This has the benefit of being able to handle `numpy` functions, but the cost is that you have to import `autograd.numpy` instead of just `numpy` (as mentioned in #189). Since we already have the expression tree, we could write something ourselves to take the derivative of the expression tree (defining derivatives of all the standard functions and use things like `pybamm.cos` instead of `np.cos` etc), but maybe this is a lot of effort if there are already tools out there which can do it for us?

**Comment by tinosulzer** [comment]
@rtimms - [this line](https://github.com/pybamm-team/PyBaMM/blob/5d74b18c6447f6ff675f301325bb8d692f7b5f2f/pybamm/expression_tree/binary_operators.py#L322) is killing speed (doing a deepcopy at each evaluation to find the orphans), should be removed
