### ISSUE TITLE
Remove zero-concentration cut-off event from DFN

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#1986]
- add `cutoff_event` kwarg (boolean, default False) to the full electrolyte model
- in `set_events` in the full electrolyte model, don't add the event if `cutoff_event` is `False`
- make `True` for the SPMe (for cut-off, see discussion in #1982 )
- make the cut-off tolerance smaller when `cutoff_event` is True

Easy issue, assuming the models still work without the event

**Comment by brosaplanella** [comment]
I think the lithium plating still might need some fixes to ensure that `c_e` doesn't go negative in the reaction.

**Comment by tinosulzer** [comment]
Ah yeah and the `log(c_e)` in the electrolyte potential too?

**Comment by dion-w** [comment]
Can i work on this? 

Also since it's my first time working with other people on a public repo: is there a timespan where results are expected? I want to see this problem resolved and would work on it in the next few weeks.

**Comment by tinosulzer** [comment]
Yes, go for it. There is no expected timespan, it is just down to whoever is motivated to do it first

**Comment by dion-w** [comment]
I found a rather neat solution for this. It involves exactly what is mentioned in #1982 . In `base_electrolyte_diffusion` heaviside functions are introduced for the c_e variable setting every value zero to 1e-8. This way the jacobians won't have NaN-values, the calculation is therefore faster and a lot of issues mentioned in #1992 don't happen. I guess these were edge case for the exact szenario that a variable becomes zero. I will soon perform the tests and create a PR on this.

**Comment by brosaplanella** [comment]
I think the standard DFN should work just by dropping the zero concentration event, so that might be a good benchmark to see if these changes are required.
