### ISSUE TITLE
Creating output instead of throwing SolverError

### ISSUE THREAD

**Issue by dion-w** [pybamm-team/PyBaMM#1992]
### Description

The feature consist of small changes in casadi_solver.py which involve creating output from a simuation if the maximum number of decreased steps is reached. A warning will be created instead of an error and the simulation will terminate normally.

### Motivation

Especially when setting up a parameter study and simulations being solved for a lot of timesteps it always bugged me when i got the pybamm.SolverError `For more timesteps try solving the model up to this time only or reducing dt_max (currently, dt_max={}).`
This meant that thousands of timesteps would have to be simulated again because no output was created. The issue is even more severe when you try to do a large parallelised parameter study where one terminated simulation could terminate a whole branch of simulations which were meant to be solved in sequence.

### Possible Implementation

the basic idea involves changes in the casadi_solver. This is merely an example of how to handle the error and could be extended to other solvers. I attached a screenshot where you can see which file i added as well as next to the line numbers where i changed something in the code.
![casadi_solver_changes](https://user-images.githubusercontent.com/91852142/159560689-d8f28a57-7c6a-4ff3-b18b-7c9db11339cf.png)

### Additional context

This issue is related to issue #1986 . After i removed the "electrolyte zero-cut off" in the DFN as mentioned in #1982 two things happened:

- for high currents: when before the simulation terminated due to the electrolyte zero cut-off, it now terminated due to a maximum/minimum voltage event. So everythings fine. Physically speaking the voltage loss in the electrolyte was high enough to meet the final cut-off voltage.
-  for low currents: the simulations has a problem to reach the maximum/minimum voltage altogether. Even when increasing the max_step_decrease_count in the Casadi solver, the solver came to a point where it would do timestep sizes of miliseconds until it finally broke but saved no output. For this case i came up with the idea to change the pybamm.SolverError to a warning and create the output thas was acquired until the respective timestep.

**Comment by tinosulzer** [comment]
That is a good idea

**Comment by dion-w** [comment]
i'm trying this right now but this way i get the error that my solution object has no timesteps (`AttributeError: 'Solution' object has no attribute "_t"'`). Maybe it's because "termination_due_to_small_dt" is not an event? As i see in the code up to now, every termination is caused by an event and i see some special preparations were done after afterwards to prepare the solution object.

**Comment by dion-w** [comment]
I found a solution, testing it now and will hopefully soon create a pr for this. So you may add me as assignee on this issue.

**Comment by tinosulzer** [comment]
Fixed by #2350
