### ISSUE TITLE
Add more doctests to PyBaMM

### ISSUE THREAD

**Issue by Saransh-cpp** [pybamm-team/PyBaMM#1994]
### Description

It would be nice to have examples in docstrings that are tested periodically. For example, the `Simulation` class could have something like this -

```
>>> spm = pybamm.lithium_ion.SPM()
<some output>
>>> sim = pybamm.Simulation(spm)
<some output>
>>> sim.solve([0, 10, 2])
<some output>
```

### Motivation

Would make minor examples available in the documentation itself and would make sure that the docs are not outdated.

**Comment by parthxtripathi** [comment]
Hey @Saransh-cpp , Can i work on this issue?

**Comment by Saransh-cpp** [comment]
Yes! Go ahead!

**Comment by tinosulzer** [comment]
Close or keep open @Saransh-cpp ?

**Comment by Saransh-cpp** [comment]
With time I have realized that maybe doctests are not that feasible for PyBaMM. Most of PyBaMM's functionality is designed to integrate together (if I am not wrong), which makes it a bit tough to write standalone (and short) doctests. For instance, writing doctests for `solve` would require building a model first. Also, the doctests added after this issue was created do not test anything substantial, so I think it should be okay to close this issue (?)

**Comment by tinosulzer** [comment]
Yeah, I agree
