### ISSUE TITLE
Deprecation message for `reaction rate`

### ISSUE THREAD

**Issue by brosaplanella** [pybamm-team/PyBaMM#2021]
At the moment, if the parameter dictionary contains a parameter containing `reaction rate` it throws an error as this was deprecated. However, if you manually introduce this variable again in the definition (to use it as an input, for example) the error comes up again even if the code works fine. Given that this was introduced about two years ago, it can probably be safely removed. However, this is not the only deprecation error so might be worth reconsidering them all.

The deprecation message is in [l374 of parameter_values.py](https://github.com/pybamm-team/PyBaMM/blame/develop/pybamm/parameters/parameter_values.py).

**Comment by tinosulzer** [comment]
Yeah, we should be removing deprecation messages after `n` releases, but we don't have an `n` or an automated process for doing so yet
