### ISSUE TITLE
Move submodels and `build_model` to `BaseModel`

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/PyBaMM#2056]
Refactor to move general code about submodels to `BaseModel` instead of `BaseBatteryModel`. This would allow people to write their own models that are composed of their own submodels. This would be a step to allowing more general models in pybamm and would also be super useful for training. Being able to write your own submodels and see how they interact would help with learning how all the battery submodels fit together. 

I think this would mainly be moving `build_model` and the methods it calls from `BaseBatteryModel` to `BaseModel`. Things like `set_voltage_variables()` would obviously need to stay in `BaseBatteryModel`. 

The only thing I haven't considered is if this is compatible with just defining `rhs` etc. explicitly? I think it is.

Thoughts??

**Comment by TomTranter** [comment]
Thanks @rtimms, as discussed I think this would help people to understand submodels. Do you think moving to a class in-between the two would help keep the code more modular, something like ComponentModel?

**Comment by TomTranter** [comment]
in v.0.4.0 there were submodel tests. It would be good to re-instate these and also make them buildable so that they can be run as standalone models with solution and latexified equations
