### ISSUE TITLE
[Bug]: Sympy version

### ISSUE THREAD

**Issue by TomTranter** [pybamm-team/PyBaMM#2059]
### PyBaMM Version

develop

### Python Version

3.9

### Describe the bug

When installing pybamm sympy is pinned to version 1.9 causing issues with liionpack and use of lcapy to draw circuits which wants to upgrade to 1.10

### Steps to Reproduce

pip install pybamm
pip install liionpack

**Comment by TomTranter** [comment]
@priyanshuone6 any idea why we're pinned at 1.9?

**Comment by priyanshuone6** [comment]
No apparent reason, we should make it >=1.8
