### ISSUE TITLE
Couldn't find program: 'bash'

### ISSUE THREAD

**Issue by Tangzl922** [pybamm-team/PyBaMM#2088]
Hi,
when I run the tutorial file for parameter management I got this error
![image](https://user-images.githubusercontent.com/73125328/172340765-61863c05-843c-429b-bf31-53646b130e3d.png)

I also read this issue https://github.com/pybamm-team/PyBaMM/issues/1697 and tried to use pybamm.parameters_cli.edit_parameter, but this still doesn't work.
![image](https://user-images.githubusercontent.com/73125328/172341334-0c8fd3e2-e0c3-4932-9bf1-ecbc7a18e042.png)
![image](https://user-images.githubusercontent.com/73125328/172342007-be77af65-a2ca-403f-b3c3-31c63c9d8352.png)

Here is my parameter path, maybe helpful for you. And my version is 22.5.
![image](https://user-images.githubusercontent.com/73125328/172341658-7e9833d5-29ce-46b5-8125-bf0bee29407e.png)

Regards

**Comment by brosaplanella** [comment]
The `parameters_cli` functions are not supported in Windows. You can still define the folder structure manually for the parameters to work.

I will transfer this to a discussion for the record.
