### ISSUE TITLE
example notebook: Run a pre-defined model

### ISSUE THREAD

**Issue by martinjrobins** [pybamm-team/PyBaMM#209]
see #199

**Comment by martinjrobins** [comment]
@tinosulzer @Scottmar93 @rtimms 

Would help here if I knew what sort of outputs/visualisations would be standard for battery modelling?

**Comment by tinosulzer** [comment]
The main ones are voltage (and current if it's interesting i.e. not just constant, temperature if it's in the model) as a function of time.
Then usually other spatially-dependent variables (concentration, interfacial current) as functions of x (or particle concentration as a function of r in the SPM/SPMe) at fixed t. A slider plot where you can vary t would be ideal for the notebooks.
I don't know the standard way of plotting particle concentration when it varies in x, r and t.

**Comment by rtimms** [comment]
for particle conc. can do a 2D contour plot in r and x, with a slider for time (or for a fixed time). some people just plot the surface concentration as a function of time, with a separate line for each particle on the same graph, but this can get messy!

**Comment by Scottmar93** [comment]
Also averaged quantities against time. This is useful for comparing SPMe with the averaged quantities from DFN.
