### ISSUE TITLE
Battery aging experiment within different SOC ranges.

### ISSUE THREAD

**Issue by zhunxinren** [pybamm-team/PyBaMM#2103]
### Description

Cycle the battery within different SOC ranges with the accelerated aging tests. For example, cycle the battery within 20%-80% for the aging test.

### Motivation

It is widely known that the battery ages at different rates under different SOC ranges. This feature will help to further investigate the aging mechanisms when the cycling SOC is different.

**Comment by rtimms** [comment]
See [this slack post](https://pybamm.slack.com/archives/CJ19X0JCF/p1650896004915399)

**Comment by Sourabh-Jadhav-2** [comment]
I am not able to open this post

**Comment by rtimms** [comment]
Lots of discussions related to this, e.g. [here](https://github.com/pybamm-team/PyBaMM/discussions/2936). Closing.
