### ISSUE TITLE
Charging current controlled depends upon the battery temperature

### ISSUE THREAD

**Issue by Jadhav-Sourabh** [pybamm-team/PyBaMM#2136]
### Description

Please add a feature for the charging, advanced charging method, in which the charging current is changed depending upon the battery temperature

### Motivation

[Uploading CT_CV_algorithm.pdf…]()
Please see the attached research paper

**Comment by tinosulzer** [comment]
The link you shared doesn't work

**Comment by Sourabh-Jadhav-2** [comment]
> The link you shared doesn't work

https://ieeexplore.ieee.org/abstract/document/9070505

**Comment by tinosulzer** [comment]
This looks maybe doable, but I doubt it will be a priority for any of the existing developers so you would need to do it yourself if you want it done any time soon

**Comment by Sourabh-Jadhav-2** [comment]
> This looks maybe doable, but I doubt it will be a priority for any of the existing developers so you would need to do it yourself if you want it done any time soon

I am doing it, but I just give a suggestion to you as a battery engineer.

**Comment by tinosulzer** [comment]
Closing due to lack of updates, feel free to reopen if still active
