### ISSUE TITLE
Raise error or warning when one of the state variables gets too large

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#2138]
We should identify if a state variable gets too large (e.g. 1e10) as this indicates that either the model has been badly non-dimensionalized, or the model is wrong, or the parameters are wrong. This would give a clearer error message for cases like #2124 
Should this be an error or warning? Maybe a logger error (doesn't cause the code to fail)?

**Comment by brosaplanella** [comment]
Warning is probably best

**Comment by tinosulzer** [comment]
How about an error, but with a setting for the max allowed value that the user can change? I think it is quite serious if `y` gets that large, and should be treated as such, but with some flexibility to allow larger values by changing the setting.

**Comment by brosaplanella** [comment]
That sounds reasonable. Are you thinking of a setting like defining the smoothness of `max` and similar functions? That would be useful I think.

**Comment by tinosulzer** [comment]
Yeah, see #2139
