### ISSUE TITLE
[Bug]: SOC of battery

### ISSUE THREAD

**Issue by ngvhien** [pybamm-team/PyBaMM#2187]
### PyBaMM Version

22.6

### Python Version

3.9.12

### Describe the bug

Hi everyone. Currently, I want to calculate SOC of battery from PyBaMM . Is there someone can let me know about this problem. Thanks so much
Regards,

### Steps to Reproduce

SOC 

### Relevant log output

```shell
SOC
```

**Comment by tinosulzer** [comment]
The easiest way to do this currently is to calculate it based on `solution["Discharge capacity [A.h]"].data / parameter_values["Nominal cell capacity [A.h]"]`
