### ISSUE TITLE
Check coord_sys of SpatialVariable

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/PyBaMM#2220]
When creating a `SpatialVariable` check the coordinate system against `KNOWN_COORD_SYS` defined [here](https://github.com/pybamm-team/PyBaMM/blob/develop/pybamm/expression_tree/independent_variable.py#L8).

**Comment by brosaplanella** [comment]
You beat me hahaha. The docstring also needs fixing.

**Comment by rtimms** [comment]
Also, add a setter for `coord_sys` is `SubMesh` to perform this check for the meshes too.

**Comment by kratman** [comment]
Is this solved by #3394 and #3114? This seems like a duplicate

**Comment by agriyakhetarpal** [comment]
Yes, Ferran mentioned in https://github.com/pybamm-team/PyBaMM/issues/3114#issuecomment-1648160595 that #3394 should close both issues. We should probably close this one and keep the newer one open.
