### ISSUE TITLE
[Bug]: Particle size distribution concentration plot x axis may be incorrectly labelled or calculated

### ISSUE THREAD

**Issue by TomTranter** [pybamm-team/PyBaMM#2225]
### PyBaMM Version

22.7

### Python Version

3.9

### Describe the bug

![image](https://user-images.githubusercontent.com/7068741/184094961-fc860b2f-48ed-4d73-bef2-fea86978756b.png)

### Steps to Reproduce

```
import pybamm
model = pybamm.lithium_ion.MPM()
sim = pybamm.Simulation(model)
sim.solve([0, 3600])
sim.plot([
    "X-averaged negative particle concentration distribution",
    "X-averaged positive particle concentration distribution",
    "Terminal voltage [V]",
])
```

**Comment by iatzak** [comment]
In [line 365 of the `ProcessedVariable` class](https://github.com/pybamm-team/PyBaMM/blob/develop/pybamm/solvers/processed_variable.py#L365), there is a conditional regarding the `first_length_scale` of such r-R plots, hard-coding it to 1. I couldn't find out where r is scaled with R, as the comment there says.

Removing the conditional causes the value `1e-5` to get assigned to `first_length_scale` for the r-R plots of your example, giving

![image](https://user-images.githubusercontent.com/112731474/217099268-b1334d01-8fa3-4d8b-b858-87ef6ac83b94.png)

Do you think this is the way to go? Apart from that, could you assign me to this issue?

**Comment by tinosulzer** [comment]
Yes this looks like the way to go, thanks!
