### ISSUE TITLE
Temperature data from running simulation[Bug]: 

### ISSUE THREAD

**Issue by Sourabh-Jadhav-2** [pybamm-team/PyBaMM#2259]
### PyBaMM Version

22.5

### Python Version

3.8

### Describe the bug

How to get temperature feedback from a running simulation? so that we will use for current function to modify future current steps

### Steps to Reproduce

**

**Comment by tinosulzer** [comment]
How is this different from #2136 ?

**Comment by Sourabh-Jadhav-2** [comment]
I saw one notebook explaining about user defined input current function with time, so I will temperature instead of time only that's why I asked

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tinosulzer** [comment]
You want current to be an explicit function of temperature? Something like `I = 1 + (T-298)/10` or whatever?

**Comment by Sourabh-Jadhav-2** [comment]
No, I will use temperature feedback as a indicator to change c rate. Example: cell temperature is going beyond 40 Celsius then c rate will decrease to less than 1C. So that we will maintain cell Temperature within safe limit.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tinosulzer** [comment]
That sounds like the same thing as you posted in #2136

**Comment by Jadhav-Sourabh** [comment]
I solved that problem in different way, I want some suggestions from you expert for the improvement

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
