### ISSUE TITLE
Post-process model variables

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#227]
**Summary**
 After solving a model, post-process the variables to objects that can be evaluated as functions of `x` and `t`, rather than `t` and `y`, and without having to loop through indices.
For example, a new class `ProcessedVariable` that has an attribute `entries` which is the variables evaluated at all the discrete values of `t` and `y` from the solver, and a method `evaluate(x, t)` that interpolates appropriately.

 **Motivation**
Easier plotting and comparison of variables, e.g. as suggested by @martinjrobins in #209 . Will also help #69 for example.

**Comment by martinjrobins** [comment]
This would be good. Could also allow `x` or `t` to be vectors or scalars so you could get the value at a particular x over all time points, or the value at a particular t over all space points

**Comment by tinosulzer** [comment]
Should `ProcessedVariable` be part of the expression tree (inherit from `Symbol`) or be something completely separate?

**Comment by martinjrobins** [comment]
I think separate. It's `evaluate` has a different meaning to `Symbol`, so I don't think it can inherit from it

**Comment by tinosulzer** [comment]
It might make sense to overload the `__call__` function for the `ProcessedVariable` class, instead of using `.evaluate()`. Thoughts @martinjrobins ?

**Comment by martinjrobins** [comment]
yea, I'd be happy with either really. `evaluate` has the advantage that its consistent with the expression tree, but I think the __call__ looks nicer for user-facing code. I'd probably lean towards the __call__.

**Comment by tinosulzer** [comment]
Cool, seems useful as a way to highlight that this is a different `evaluate` to the tree evaluate as well
