### ISSUE TITLE
Adding feature to output individual electrode expansion

### ISSUE THREAD

**Issue by sravanpannala** [pybamm-team/PyBaMM#2281]
### Description

The model will output positive and and negative electrode thickness in addition to the overall cell thickness it currently outputs.

### Motivation

Currently, the mechanical model outputs only the overall cell thickness. In many cases, especially while studying degradation, it is useful to observe and analyze individual electrode thicknesses i.e. positive and negative electrode thickness.

### Possible Implementation

In the `_get_mechanical_results(self, variables)` function of `base_mechanics.py` we can add additional code so that we can get individual electrode thicknesses. I've already tried out the implementation and it is very simple.
```
        if self.domain+" electrode thickness change [m]" not in variables:
            electrode_thickness_change = 0
        else:
            electrode_thickness_change = variables[self.domain+" electrode thickness change [m]"]
        electrode_thickness_change += self.param.n_electrodes_parallel * v_change * L0
return {
            self.domain+" electrode thickness change [m]": electrode_thickness_change,
        }
```

**Comment by tinosulzer** [comment]
How's this going @sravanpannala ?

**Comment by tinosulzer** [comment]
@mbonkile is also interested in this feature

**Comment by sravanpannala** [comment]
I'll try to work on it this weekend. Just for confirmation, I've to implement this on a fresh fork, right? And then run all the unit tests?

**Comment by rtimms** [comment]
@sravanpannala any update on this? Yes, implement on your own fork and then make a PR.
