### ISSUE TITLE
Use `@cache` and `@cache_property` from `functools` for memoization

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#2288]
See https://docs.python.org/3/library/functools.html

We are currently doing this manually using try-except blocks with `AttributeError` ([example](https://github.com/pybamm-team/PyBaMM/blob/8c4b3d60d5980748ba8a673be50aa140eb57cb63/pybamm/expression_tree/symbol.py#L907-L916)). Using the decorators from functools would be cleaner

This is different functionality from using `@property` with a setter and getter - those should not be changed.

**Comment by tinosulzer** [comment]
See #2289 for an example of `@cached_property`

**Comment by agriyakhetarpal** [comment]
Hi @tinosulzer, I'd be happy to work on this!

**Comment by tinosulzer** [comment]
Great!

**Comment by agriyakhetarpal** [comment]
Apologies for the delay(s), I'll be working on this in this week!
