### ISSUE TITLE
RuntimeError: .../casadi/core/plugin_interface.hpp:417: Plugin 'newton' is not found.

### ISSUE THREAD

**Issue by e2sdji** [pybamm-team/PyBaMM#2317]
I am a beginner Python battery worker. I encountered this problem today and  can't think of a way to solve it. 
![69a9732b3691bc71f0ae7d44bef896a](https://user-images.githubusercontent.com/114319396/192123693-b2719329-a850-4eb6-bf00-386ba8f9baf3.jpg)

**Comment by tinosulzer** [comment]
Does this work?
```python3
x = MX.sym('x',2); # Two states

# Expression for ODE right-hand side
z = 1-x[1]**2
rhs = vertcat(z*x[0]-x[1],x[0])

ode = {}         # ODE declaration
ode['x']   = x   # states
ode['ode'] = rhs # right-hand side

# Construct a Function that integrates over 4s
F = integrator('F','cvodes',ode,{'tf':4})

# Start from x=[0;1]
res = F(x0=[0,1])

print(res["xf"])

# Sensitivity wrt initial state
res = F(x0=x)
S = Function('S',[x],[jacobian(res["xf"],x)])
print(S([0,1]))
```

**Comment by e2sdji** [comment]
Thank you very much for your answer. I just found out the problem,just now. The casadi installed by pip is vulnerable. I downloaded it from the official website to solve the problem.
Thank you !!!!!

**Comment by tinosulzer** [comment]
> Thank you very much for your answer. I just found out the problem,just now. The casadi installed by pip is vulnerable. I downloaded it from the official website to solve the problem.
Thank you !!!!!

**Comment by w1ndfall** [comment]
I met the same problem, but I found the installation method of casadi on the official website and also used pip. May I ask how did you install casadi on the official website
