### ISSUE TITLE
ModuleNotFoundError: No module named 'casadi.casadi'

### ISSUE THREAD

**Issue by e2sdji** [pybamm-team/PyBaMM#2318]
It was successfully run once before, but such an error occurred after opening jupyter notebook again.

Hope to get answers，thank you.
![微信图片_20220925203933](https://user-images.githubusercontent.com/114319396/192144062-f073d299-eafd-4dfb-8327-a9c6d5c04858.jpg)
![b2b51e96c653ee83619cad5737e2caa](https://user-images.githubusercontent.com/114319396/192144077-033c603e-52f7-401e-951d-b7cba60c5595.jpg)

**Comment by tinosulzer** [comment]
This sounds like a python install issue on your end, not a pybamm bug. See maybe https://stackoverflow.com/questions/37085665/in-which-conda-environment-is-jupyter-executing
