### ISSUE TITLE
SEI transfer coefficient

### ISSUE THREAD

**Issue by brosaplanella** [pybamm-team/PyBaMM#2338]
The SEI transfer coefficient for `reaction limited` and `EC reaction limited` have the transfer coefficient hardcoded to 0.5. This value is a modelling assumption (see [Safari et al. 2009](https://iopscience.iop.org/article/10.1149/1.3043429/pdf)), so I think we should allow to define it in the parameter values so it can be changed.

**Comment by tinosulzer** [comment]
Sure. Let's handle it the same way as symmetric/asymmetric BV. Add new SEI options "reaction limited (asymmetric)" and "EC reaction limited (asymmetric)" which require the transfer coefficient to be defined.

**Comment by brosaplanella** [comment]
Shall I leave the option `"reaction limited"` (which defaults to the symmetric) with a deprecation warning? Or just introduce a breaking change?

**Comment by tinosulzer** [comment]
Definitely have a deprecation warning if it changes. I'm not sure it needs to be changed though?
