### ISSUE TITLE
Remove tutorials from readthedocs

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#2347]
they're getting out of date, and I don't think anyone is using them

**Comment by allisara** [comment]
Could you assign me to this issue?

**Comment by tinosulzer** [comment]
How's this going @allisara ? Need any help?

**Comment by agriyakhetarpal** [comment]
Since progress has not been made yet, could I take this up?

**Comment by tinosulzer** [comment]
Sure, go for it

**Comment by agriyakhetarpal** [comment]
Sure, which tutorials have to be removed in specific? The current documentation links to the examples which enlist the Jupyter notebooks, below them are the tutorials for adding models and solvers under the Contributing section

**Comment by tinosulzer** [comment]
These https://github.com/pybamm-team/PyBaMM/tree/develop/docs/tutorials and references to them
