### ISSUE TITLE
Add "temperature" argument to experiment

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#2358]
Simulation should then update the parameter values ("Ambient temperature [K]" and "Initial temperature [K]", not "Reference temperature [K]"), with the given temperature

**Comment by Niiola** [comment]
can i get more explanation on this project and also i would love to be assigned this task

**Comment by tinosulzer** [comment]
1. In the  `Experiment` (https://github.com/pybamm-team/PyBaMM/blob/develop/pybamm/experiments/experiment.py) class, add a new attribute `temperature` which is `None` by default but can be provided
2. In the  `Simulation` (https://github.com/pybamm-team/PyBaMM/blob/develop/pybamm/simulation.py) class `__init__`, if `experiment.temperature` is not `None`, update ambient and initial temperature in the parameter values with the given temperature.

**Comment by Scottmar93** [comment]
I also think temperature control is super useful to have in the experiment class. 

@tinosulzer what's your view on the complexity of allowing the ambient temperature to be controllable on the step level? e.g. 
```python
   experiment = pybamm.Experiment(
    [
        (
            "Discharge at C/10 for 10 hours or until 3.3 V at 25oC",
            "Rest for 1 hour at 35oC",
            "Charge at 100 A until 4.1 V at 35oC (1 second period)",
            "Hold at 4.1 V until 5 A at 35oC (1 seconds period)",
            "Rest for 1 hour at 25oC",
        ),
    ]
)
```
This would give the experiment class a similar level of control as most battery cyclers.

**Comment by tinosulzer** [comment]
This would be super easy, the hardest part would probably be reading the string to extract the temperature, e.g. adding a new field "T" for the operating conditions. Once that is done, it's just a matter of updating the parameter values for each step before processing the model [here](https://github.com/pybamm-team/PyBaMM/blob/8478e9a6168c4a3e6b0720be07c6ad6c6dae5fe6/pybamm/simulation.py#L267)

**Comment by Scottmar93** [comment]
Nice! That is great to hear. 

Is this something worth doing within this issue or separately? Can perhaps be done separately with this issue setting a global temperature and any temperature set on a step overwriting it.

**Comment by tinosulzer** [comment]
I don't mind, whichever you prefer

**Comment by tinosulzer** [comment]
Feel free to take over this issue too unless @Niiola has made progress?

**Comment by Scottmar93** [comment]
Happy to do as @Niiola wishes 😄

**Comment by Niiola** [comment]
You can go ahead
