### ISSUE TITLE
Consistent initial conditions

### ISSUE THREAD

**Issue by Scottmar93** [pybamm-team/PyBaMM#236]
@tinosulzer did you need to implement a consistent initial conditions finder (initial newton solve on the algebraic equations) for lead-acid? For DFN the solver raises the error:
```
[IDA ERROR]  IDASolve
  At t = 0 and h = 9.53674e-11, the error test failed repeatedly or with |h| = hmin.
```

**Comment by tinosulzer** [comment]
yes, in [dae_solver.py](https://github.com/pybamm-team/PyBaMM/blob/cf3179079505f5d7ce0a776bf8b9af4c87e00b3a/pybamm/solvers/dae_solver.py#L74)
