### ISSUE TITLE
Move initial soc out of solve

### ISSUE THREAD

**Issue by abillscmu** [pybamm-team/PyBaMM#2372]
### Description

It would be nice if it was in its own method, which was then called by either solve or build.

### Motivation

Necessary to get initial soc for Julia solvers

### Possible Implementation

just move it to its own method, then call that method in build/solve

**Comment by abillscmu** [comment]
I just want to access it from build

**Comment by tinosulzer** [comment]
Yes, it's easy. We need to also keep it in `solve` though, no good reason to break backwards compatibility here
