### ISSUE TITLE
Dimensional models

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#2418]
Some basic profiling reveals that implementing the models in a dimensional way provides no slow-down compared to dimensionless. Since dimensionless models are a big barrier to entry, we should reformat the models to be entirely dimensional. Further benchmarking and testing will be needed.

Note: scaling variables is still a good idea for the condition number of the solver, but this can be done directly in the solver

**Comment by tinosulzer** [comment]
We currently have a lot of duplicate variables (dimensionless/dimensional).
Q: Should we just get rid of the dimensionless ones?

**Comment by tinosulzer** [comment]
Would be good to revive #406 when implementing this to add an additional layer of testing

**Comment by brosaplanella** [comment]
> We currently have a lot of duplicate variables (dimensionless/dimensional). Q: Should we just get rid of the dimensionless ones?

I think so, I would just keep those that have actually some sort of physical meaning beyond being the dimensionless form of something (e.g. dimensionless particle concentrations / stoichiometry).
