### ISSUE TITLE
`import pybamm` could be faster

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#2436]
Doing some basic profiling, a lot (25%) of time is spent initializing the entry points in `parameter_sets.py`. Can this be made faster @awadell1 ? Or only initialized if/when it's first called?

**Comment by awadell1** [comment]
Maybe. How much time is spent in `__init__`? And how much on the `.load()` call?

https://github.com/pybamm-team/PyBaMM/blob/develop/pybamm/parameters/parameter_sets.py

**Comment by tinosulzer** [comment]
roughly 0.5s in the `__init__` of a total 2s time for `import pybamm`, all in the `.load()` call

**Comment by awadell1** [comment]
Oh damn; almost certainly, then. `__init__` can just fetch the list of names and calling `.load()` can be delayed until each parameter set is first accessed in `__getitem__`.
