### ISSUE TITLE
Remove `.diff`?

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#2495]
It's not used in any of the models, now that we have removed composite/first-order lead-acid models.
Removing would also allow removing `autograd` dependency

**Comment by brosaplanella** [comment]
What was it for originally?

**Comment by tinosulzer** [comment]
Symbolic differentiation e.g. `(c**2).diff(c)` returns `2*c`

**Comment by tinosulzer** [comment]
Yes, OCV (computing `dUdT`) was an early intended use case, before I found out everyone just gives `dUdT` explicitly in practice

**Comment by tinosulzer** [comment]
In the lead-acid models, it was used to compute the first-order term of the Taylor expansion in the asymptotic expansion (e.g. `j0(c).diff(c)`). SPMe circumvents this by just using the composite term

**Comment by brosaplanella** [comment]
The only case where that would be useful that I can think is in GITT, where you need U'(c). However, in practice, that's hard to calculate so you probably want to manually prescribe it.

**Comment by tinosulzer** [comment]
Ok yeah, let's keep it
