### ISSUE TITLE
Add dimensional outputs to SPM, SPMe, DFN

### ISSUE THREAD

**Issue by Scottmar93** [pybamm-team/PyBaMM#250]
Does anyone have a good idea how to do this? It would be good to discuss on Monday. 

A couple of things to note: 
- we can either output a separate dictionary with dimensional output variables or somehow include dimensional variables into the current output dictionary (avoiding any name clashes with a "Dimensionless... at start of variable names).
- If the dimensional output variables are entered within the submodels then we would need to be careful that the scalings used are consistent across chemistries. 
- we could maybe add a dimensionalise function for each chemistry which searches through variables and finds the correct scalings to apply (This may be more complex than its worth though). 

 **Motivation**
Dimensional variables are needed in practice.

**Comment by martinjrobins** [comment]
wouldn't the dimensional outputs go in `model.variables` along with all the other needed output variables?

**Comment by Scottmar93** [comment]
Following meeting we will insert dimensional variables into the `model.variables` dictionary and include the units of the variable in the name.
