### ISSUE TITLE
Use `n_Li` or `Q_Li` as the input for electrode SOH calculation?

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#2507]
`n_Li` is the total moles of cyclable lithium
`Q_Li = n_Li * F / 3600` is the total capacity of cyclable lithium

`n_Li` is better because it's what's in the Mohtat reference paper. `Q_Li` is better because it has the same units as Q_n, Q_p, Q and so doesn't require the factor of F/3600 to convert.

I would lean towards switching to `Q_Li`.

**Comment by brosaplanella** [comment]
You mean as an internal Python variable or as an external "plotting" variable?

**Comment by tinosulzer** [comment]
For the variable we pass in the `inputs` dictionary.
We can have both as plotting variables

**Comment by brosaplanella** [comment]
Then I am happy with either of them, so if you prefer `Q_Li` I vote for it too.

**Comment by tinosulzer** [comment]
Done in #2508
