### ISSUE TITLE
Slow tests

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#251]
Running all the tests is starting to take a while (~1 minute on my desktop) and will only get slower as we add convergence tests etc.
Are there any standard practices to get around this? Would only be for bypassing the slower tests locally, IMO there's no problem with travis checks taking a while at this scale

**Comment by martinjrobins** [comment]
standard practice is just to divide up the tests into types, for example separate out the fast, continuous tests from the rest. Could have two folders in tests, `tests/continuous` and `tests/daily` and only run the latter on a daily cronjob basis on travis?
