### ISSUE TITLE
Boolean operator not defined for Symbols (can't use if-else statements when defining expressions)

### ISSUE THREAD

**Issue by Ma2922** [pybamm-team/PyBaMM#2520]
### PyBaMM Version

22.9

### Python Version

3.9

### Describe the bug

I want to write a piecewise function , but there is an error:
     18 def Ds_p(sto,T):
---> 19     if T>293.15:
     20         if sto<0.8:
     21             diff=1.0*10**(-11)*(6-5*sto)
    659 def __bool__(self):
--> 660     raise NotImplementedError("Boolean operator not defined for Symbols.")

NotImplementedError: Boolean operator not defined for Symbols.

### Steps to Reproduce

def Ds_p(sto,T):
    if T>293.15:
        if sto<0.8:
            diff=1.0*10**(-11)*(6-5*sto)
        else:
            diff=2.3362*10**(-11)
    return diff
params["Positive electrode diffusivity [m2.s-1]"]=Ds_p

**Comment by tinosulzer** [comment]
You can't use if-else statements when defining expressions. You have to use heavisides i.e. `(T > 293.15) * ((sto<0.8) * 1.010**(-11) * (6-5*sto) + (sto <= 0.8) * 2.3362180**(-11))` instead

Could you open a PR updating the error message to explain this?

**Comment by Ma2922** [comment]
thank you very much for solving my problem.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Valentin ***@***.***&gt;; 
发送时间: 2022年12月5日(星期一) 凌晨1:49
收件人: ***@***.***&gt;; 
抄送: "BIT ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pybamm-team/PyBaMM] Boolean operator not defined for Symbols  (Issue #2520)





 
You can't use if-else statements when defining expressions. You have to use heavisides i.e. (T &gt; 293.15) * ((sto<0.8) * 1.010**(-11) * (6-5*sto) + (sto <= 0.8) * 2.3362180**(-11)) instead
 
Could you open a PR updating the error message to explain this?

**Comment by tinosulzer** [comment]
@Ma2922 it would be nice if you could open a PR updating the error message to make it clearer, in case anyone else comes across this problem

**Comment by ayeankit** [comment]
hey @tinosulzer , Is this still open? I would like to work on it.

**Comment by tinosulzer** [comment]
Yes, you can work on it

**Comment by ayeankit** [comment]
Hey @tinosulzer , Can you please tell more about this issue and where to implement it?

**Comment by tinosulzer** [comment]
This error message: https://github.com/pybamm-team/PyBaMM/blob/14040748098322c82c8cd10998b4a57df14a00ce/pybamm/expression_tree/symbol.py#L649

needs to change to:

"Boolean operator not defined for Symbols. You might be seeing this message because you are trying to specify an if statement based on the value of a symbol, e.g. 
```python
if x < 0:
    y = 1
else:
   y = 2
```

In this case, use heaviside functions instead:
```python
y = 1 * (x < 0) + 2 * (x >= 0)
```
"

That's the end of the error message. But if you want to do more, you could also implement this function in `binary_operators.py`:

```python3
def if_else(condition, value_if_true, value_if_false):
    return value_if_true * condition + value_if_false * (1 - condition)
```

with associated tests and documentation

**Comment by HarshvirSandhu** [comment]
Hello @tinosulzer 
I would like to work on this issue

**Comment by arjxn-py** [comment]
Sure @HarshvirSandhu, feel free to take this up.
Assigned you for the time being
