### ISSUE TITLE
"Throughput capacity [A.h]" is different for sol.cycles[0] and sol.cycles[0].steps[0]

### ISSUE THREAD

**Issue by valentinsulzer** [pybamm-team/PyBaMM#2528]
### Discussed in https://github.com/pybamm-team/PyBaMM/discussions/2523

<div type='discussions-op-text'>

<sup>Originally posted by **RuiheLi** December  5, 2022</sup>
Dear PyBaMM,

I am using PyBaMM 22.9 and Python 3.9.6.

I find when using that set_initial_conditions_from, "Throughput capacity [A.h]" is different for sol.cycles[0] and sol.cycles[0].steps[0] for a later solution. Figure below:
![image](https://user-images.githubusercontent.com/84007676/205644495-558eabbe-1f36-4dd5-9935-44f131704896.png)

Script below:

```
import pybamm 
import matplotlib as mpl
fs=17;
font = {'family' : 'DejaVu Sans','size'   : fs}
mpl.rc('font', **font)
V_max = 4.0;  V_min = 2.7; 
model_0 = pybamm.lithium_ion.DFN(options={
    "calculate discharge energy":"true", },)
exp_AGE_text = [(f"Discharge at 1 C until {V_min} V", 
    f"Charge at 1 C until {V_max} V", ),  ]
Experiment    = pybamm.Experiment( exp_AGE_text * 1)
Para_0 = pybamm.ParameterValues("OKane2022" )

Sim_0= pybamm.Simulation(
    model_0,
    experiment = Experiment, 
    parameter_values=Para_0, 
    solver = pybamm.CasadiSolver(),)
Sol_0 = Sim_0.solve(calc_esoh=False,) 

model_1 = model_0.set_initial_conditions_from(Sol_0, inplace=False)
Sim_1= pybamm.Simulation(
    model_1,
    experiment = Experiment, 
    parameter_values=Para_0, 
    solver = pybamm.CasadiSolver(),)
Sol_1 = Sim_1.solve(calc_esoh=False,) 

model_2 = model_0.set_initial_conditions_from(Sol_1, inplace=False)
Sim_2= pybamm.Simulation(
    model_2,
    experiment = Experiment, 
    parameter_values=Para_0, 
    solver = pybamm.CasadiSolver(),)
Sol_2 = Sim_2.solve(calc_esoh=False,) 

label = ["Sol_0","Sol_1","Sol_2",] 
output_variables3 = [
    "Throughput energy [W.h]",
    "Throughput capacity [A.h]", 
    "Terminal voltage [V]", 
]
quick_plot = pybamm.QuickPlot(
    [Sol_0,Sol_1,Sol_2,], output_variables3,label,variable_limits='fixed',
    time_unit='hours',n_rows=1) #figsize = (18,12),
quick_plot.dynamic_plot()
label = ["Sol_2 whole","Sol_2 cycles","Sol_2 steps",] 
quick_plot = pybamm.QuickPlot(
    [Sol_2,Sol_2.cycles[0],Sol_2.cycles[0].steps[0]], output_variables3,label,variable_limits='fixed',
    time_unit='hours',n_rows=1) #figsize = (18,12),
quick_plot.dynamic_plot()
```

Do you have any ideas on this? Big thanks!

</div>

**Comment by tinosulzer** [comment]
To solve this properly will require reformatting how we do `ExplicitTimeIntegral`, which in turn will depend on other improvements to the backend that we are working on. In the meantime, what you could do is set this to `remove_independent_variables_from_rhs=False` in your branch https://github.com/pybamm-team/PyBaMM/blob/b072d22f1344f062fc84ca44e0c540873669b6f7/pybamm/discretisations/discretisation.py#L102 (but note that it might take longer to solve the model as a result)

**Comment by brosaplanella** [comment]
Possibly related to this, I encountered a similar issue in a much simpler problem (free fall problem)
```python3
# Create model
model = pybamm.BaseModel()
u = pybamm.Variable("u")
v = pybamm.Variable("v")
model.rhs = {u: v, v: -1}
model.initial_conditions = {u: 2, v: 0}
model.variables = {"u": u, "v": v}

# Discretise using default discretisation
disc = pybamm.Discretisation()
disc.process_model(model);

# Solve 
t_eval = np.linspace(0, 5, 30)
ode_solver = pybamm.ScipySolver()
solution = ode_solver.solve(model, t_eval)

# Plot
solution.plot(["u", "v"])
```

It seems that after the first step, the variable `u` is set to zero and then evolves according to the equation.

![image](https://github.com/pybamm-team/PyBaMM/assets/28443643/3401215a-570b-42ff-9a70-9e0fd4b10c0a)
