### ISSUE TITLE
Simplify Concatenation (and subsequent bug)

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#253]
**Describe the bug**
The model wasn't being simplified as no simplification was implemented for a `NumpyConcatenation`, when this is added there is a dimension error with matrices being multiplied. It seems that the original tree in the model was
```
Matrix (9,8) * (vector (8,) * Matrix(8,9)  ---> Matrix(9,8) * Matrix(8,9) ---> Matrix(9,9)
```
but this gets changed to 
```
(Matrix (9,8) * vector (8,)) * Matrix(8,9)  ---> Vector(9,) * Matrix(8,9) ---> Error
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to branch `issue-253-simplify-bug`
2. Run `python3 -m tests.test_models.test_lead_acid.test_lead_acid_newman_tiedemann`
3. ipdb starts in `MatrixMultiplication.evaluate()`, type `self.children[0].evaluate(t,y).shape` (returns (9,)), `self.children[0].evaluate(t,y).shape` (returns (8,9))

**Comment by martinjrobins** [comment]
@tinosulzer, do you mean the original tree was

```
Matrix (9,8)   ( vector (8,) @ Matrix(8,9) )
```

But `vector (8,) @ Matrix(8,9)` gives `vector(9,)`?

**Comment by tinosulzer** [comment]
Sorry that wasn't clear, there is a mix of matrix multiplications and elementwise multiplications:
original:
```
Matrix (9,8) @ (vector (8,) * Matrix(8,9))  ---> Matrix(9,8) @ Matrix(8,9) ---> Matrix(9,9)
```
after simplification:
```
(Matrix (9,8) @ vector (8,)) * Matrix(8,9)  ---> Vector(9,) * Matrix(8,9) ---> Error
```

**Comment by martinjrobins** [comment]
but `vector (8,)` is a row vector, so  `vector (8,) * Matrix(8,9)`  shouldn't work? should be `vector (8,1)`?

```
In [1]: import numpy as np

In [2]: v = np.ones(8)

In [3]: m = np.ones((8,9))

In [4]: v*m
---------------------------------------------------------------------------
ValueError    Traceback (most recent call last) <ipython-input-4-c1d8335750dc> in <module>
----> 1 v*m

ValueError: operands could not be broadcast together with shapes (8,) (8,9)
```

**Comment by martinjrobins** [comment]
so if you were to expand out the brackets in `m2@(v*m)`, what would you get mathematically? I'm not sure..

**Comment by tinosulzer** [comment]
It looks like the `*` operator does matrix multiplication by default for scipy matrices, so we should use `A.multiply(B)` instead:
```
In [13]: sparse.coo.coo_matrix((8,9))*sparse.coo.coo_matrix((8,9))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-c73b5d00c9d5> in <module>()
----> 1 sparse.coo.coo_matrix((8,9))*sparse.coo.coo_matrix((8,9))

~/.local/lib/python3.6/site-packages/scipy/sparse/base.py in __mul__(self, other)
    476         if issparse(other):
    477             if self.shape[1] != other.shape[0]:
--> 478                 raise ValueError('dimension mismatch')
    479             return self._mul_sparse_matrix(other)
    480 

ValueError: dimension mismatch

In [14]: sparse.coo.coo_matrix((8,9))*sparse.coo.coo_matrix((9,8))
Out[14]: 
<8x8 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in Compressed Sparse Row format>

In [15]: sparse.coo.coo_matrix((8,9))@sparse.coo.coo_matrix((9,8))
Out[15]: 
<8x8 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in Compressed Sparse Row format>

In [16]: sparse.coo.coo_matrix((8,9))@sparse.coo.coo_matrix((8,9))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-ce8641f5818e> in <module>()
----> 1 sparse.coo.coo_matrix((8,9))@sparse.coo.coo_matrix((8,9))

~/.local/lib/python3.6/site-packages/scipy/sparse/base.py in __matmul__(self, other)
    557             raise ValueError("Scalar operands are not allowed, "
    558                              "use '*' instead")
--> 559         return self.__mul__(other)
    560 
    561     def __rmatmul__(self, other):

~/.local/lib/python3.6/site-packages/scipy/sparse/base.py in __mul__(self, other)
    476         if issparse(other):
    477             if self.shape[1] != other.shape[0]:
--> 478                 raise ValueError('dimension mismatch')
    479             return self._mul_sparse_matrix(other)
    480 

ValueError: dimension mismatch

In [17]: sparse.coo.coo_matrix((8,9)).multiply(sparse.coo.coo_matrix((8,9)))
Out[17]: 
<8x9 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in Compressed Sparse Row format>
```

**Comment by martinjrobins** [comment]
ok. But this doesn't relate to this bug? probably better to open that as a separate issue

**Comment by tinosulzer** [comment]
> so if you were to expand out the brackets in `m2@(v*m)`, what would you get mathematically? I'm not sure..

It looks like this isn't possible in general

> ok. But this doesn't relate to this bug? probably better to open that as a separate issue

Ok will open separate issue and hope nothing breaks ...  We might be ok because the original case should actually be
```
div(D(c)*grad(c)) 
---> Matrix (9,8) @ (vector (8,) * (Matrix(8,9) @ vector(9,)))  
---> Matrix (9,8) @ (vector (8,) * vector(8,))
---> Matrix(9,8) @ vector(8,) 
---> vector(9,)
```

**Comment by martinjrobins** [comment]
I've fixed the bug so that `m2@(v*m).simplify()` will not try to expand the brackets around the *, but still getting dimension errors for the model tests. I've had a look at the model equations, but they are too long to see what the problem is. How did you manage to find the problem earlier @tinosulzer, any tips?

**Comment by tinosulzer** [comment]
Try putting a try-except block around the operation that is giving a dimension error, then you can have a look at what the children evaluate to and why it's giving an error

**Comment by martinjrobins** [comment]
ok, think I might have figured out the problem, when I fixed the issue you described above with the sparse multiplication the error message became much more meaningful. The statevector is being put in during the solve as a row vector, rather than a column vector, so at some point there is something like:

`vector(99,) * sparse_matrix(99,100)`

this was getting treated like a matrix multiplication, which is fine, but then I fixed it so that it was treated as a broadcasting scalar multiply, it started complaining the dimensions didn't agree, which is also right, it should be

`vector(99,1) * sparse_matrix(99,100)`

Does that sound right?

**Comment by tinosulzer** [comment]
That sounds right but even with the sparse multiplication fixed there are no errors like this on the non-simplified model, and I am guessing that this is because there are never any vector-matrix multiplications, only matrix-vector (e.g. grad(c) or div(grad(c)) or vector-vector (e.g. c*grad(c))

**Comment by martinjrobins** [comment]
I think the problem is that there are things like:
```
vector(99,) * ( sparse_matrix(99,100) @ statevector(99,) )
```

if you just evaluate that, you do the inner matrix-vector multiply which gives you a vector, then multiply that by the outer vector. All good. But if you try to simplify by doing the `vector(99,) * sparse_matrix(99,100)` to give you a `sparse_matrix(99,100)`,  then you run into problems

I've pushed a hacky fix to `pybamm.Multiplication` which takes into account 1d numpy vectors, and a few other misc fixes that arose after that one. All the tests pass now, which is good. Is the original bug you found in this issue fixed?

**Comment by tinosulzer** [comment]
Have added (but not tested) simplification of `DomainConcatenation`, which required removing the line in `symbol.simplify` that removed domain (`DomainConcatenation` needs to know the domains).
Good news is it runs and simplifies the tree, bad news is we don't get much speed gain :confounded: 

In `dae_solver.py`:
```
In [2]: %timeit concatenated_rhs.evaluate(0,y0)                                                                                                                                                             
1.72 ms ± 14.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [3]: %timeit model.concatenated_rhs.evaluate(0,y0)                                                                                                                                                       
1.93 ms ± 85.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

**Comment by tinosulzer** [comment]
It could be the reshapes in `Multiplication` slowing things down in the simplified tree (more reshapes needing to happen there than in the original tree)

**Comment by martinjrobins** [comment]
that is a shame :( I've been doing the simplify for domain concatentation as well, without the domain information, this should pass all the tests now.
