### ISSUE TITLE
Resistance[Bug]: 

### ISSUE THREAD

**Issue by Jadhav-Sourabh** [pybamm-team/PyBaMM#2601]
### PyBaMM Version

NA

### Python Version

NA

### Describe the bug

How pybamm is calculating the resistance value (this is not a Local ECM resistance)???
Please share the reference.

Thank you.

### Steps to Reproduce

NA

**Comment by tinosulzer** [comment]
Which resistance value are you referring to?

**Comment by Jadhav-Sourabh** [comment]
When you solve the model and try to plot the result by entering
`sim.plot(['Resistance [Ohm]'])`

I just want to know How pybamm is calculating this value. Need a reference or formula.
________________________________
