### ISSUE TITLE
Interface docs need updating

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/PyBaMM#2607]
The [docs for the interface submodels](https://pybamm.readthedocs.io/en/latest/source/models/submodels/interface/index.html) should match the folder structure [here](https://github.com/pybamm-team/PyBaMM/tree/develop/pybamm/models/submodels/interface).

**Comment by dikwickley** [comment]
hello @rtimms I would like to work on this issue, can you please assign it to me?

**Comment by rtimms** [comment]
Thanks @dikwickley ! Let me know if you have any questions.

**Comment by Yash-Sajwan24** [comment]
Hello, @rtimms 
I would like to work on this issue, can you please assign it to me? I am a beginner and looking forward to contributing.

**Comment by Yash-Sajwan24** [comment]
Can you please specify the order as most of the names of folders do not match with the doc?

**Comment by rtimms** [comment]
Thanks @Yash-Sajwan24!

The docs should follow the folder structure, e.g. 

- BaseInterface
- TotalInterfacialCurrent
- Open Circuit Potential 
    - BaseOpenCircuitPotential
    - CurrentSigmoidOpenCircuitPotential
    - SingleOpenCircuitPotential
- Kinetics
    - ...
- ...   

@dikwickley @Yash-Sajwan24 can you coordinate between yourselves who is going to work on this to avoid duplication of effort?

**Comment by Yash-Sajwan24** [comment]
I still don't get it .☹️ 
![Screenshot 2023-01-25 195706](https://user-images.githubusercontent.com/52412969/214589533-23941e6f-02cd-42e9-8858-891cb636bb3e.png)
![Screenshot 2023-01-25 195720](https://user-images.githubusercontent.com/52412969/214589539-c582cf83-9861-47f7-9068-2f10313e7d6f.png)

**Comment by rtimms** [comment]
The [interface docs](https://github.com/pybamm-team/PyBaMM/tree/develop/docs/source/models/submodels/interface) need to be modified to match the file structure in the [interface submodel directory](https://github.com/pybamm-team/PyBaMM/tree/develop/pybamm/models/submodels/interface). You will need to add extra folders and .rst files.

Take a look at how the [electrode docs](https://github.com/pybamm-team/PyBaMM/tree/develop/docs/source/models/submodels/electrode) are set up based on the [electrode submodels directory](https://github.com/pybamm-team/PyBaMM/tree/develop/docs/source/models/submodels/electrode).

**Comment by dikwickley** [comment]
@rtimms i have made a new interface folder and have completed kinetics and Interface Utilisation.
Here is the demo: https://dikwickley-pybamm.readthedocs.io/en/latest/source/models/submodels/interface2/
let me know if it's okay

**Comment by rtimms** [comment]
Looks good, thanks! Please open a PR

**Comment by dikwickley** [comment]
@rtimms please review the PR. if there are any other modules that require documentation updates let me know. thanks :)
