### ISSUE TITLE
Hackathon 29th March 2023 in Oxford

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#2631]
We will be hosting an in-person hackathon on 29th March in Oxford.

I﻿n this hackathon, you will have the opportunity to learn how to contribute to PyBaMM, while working on real examples under the expert guidance of members the PyBaMM team. The hackathon will also include an introduction on how to contribute to the project (more details of the agenda will be published closer to the date). Each participant should bring their own laptop and have PyBaMM installed from source (see details [here](https://pybamm.readthedocs.io/en/latest/source/user_guide/installation/install-from-source.html)). L﻿unch and tea&coffee will be provided.

This workshop is supported by The Faraday Institution `"Multi-Scale Modelling" project [EP/S003053/1 grant number FIRG025].

Important n﻿ote: this hackathon is not an introductory course on how to use PyBaMM. E﻿xperience with Python and PyBaMM is required, and basic experience with git is strongly recommended.

**Comment by tinosulzer** [comment]
To do:
- [ ] add this to readme
- [ ] add banner to website

**Comment by tinosulzer** [comment]
Thanks! Fixed in both places

**Comment by brosaplanella** [comment]
Hackathon took place and went very well, we can now close this issue.
