### ISSUE TITLE
use massively parallel sundials solvers for running many solves with different input parameters

### ISSUE THREAD

**Issue by martinjrobins** [pybamm-team/PyBaMM#2644]
### Description

Sundials has a few "massively parallel" solvers that can solve many independent models in parallel on a GPU (SUNLinSol_OneMklDense and SUNLinSol_MagmaDense for dense systesm, SUNLinSol_cuSolverSp_batchQR for sparse). These could be used for parameter sweeps, data generation or inference.

See also #2217 

### Motivation

enable the use of GPUs to solver a large number of PyBaMM models in parallel

**Comment by tinosulzer** [comment]
Nice, tagging @pghege who is interested in applications for GPUs in this area
