### ISSUE TITLE
Fix broken URLs

### ISSUE THREAD

**Issue by Saransh-cpp** [pybamm-team/PyBaMM#2660]
URL checker was down temporarily but #2659 brings it back up again.

At the moment, there are a lot of broken URLs - https://github.com/pybamm-team/PyBaMM/actions/runs/4090861650/jobs/7054568267 - which should be fixed.

Most of them originate from the documentation revamp, some of them are false alarms, and some of them are from external repositories/sources.

**Comment by jeromtom** [comment]
Started working on it #2656

**Comment by jeromtom** [comment]
@Saransh-cpp 
How do we know where these links were used?
Then we can replace it with the correct link like in #2656

**Comment by Saransh-cpp** [comment]
You can use the search feature of your IDE (VSCode has a great search functionality).

Alternatively, you can use CLI tools like `grep` (UNIX) and `findstr` (Windows). For example -
```
cd PyBaMM
grep -nr the/url/you/want/to/search     # -r -> recursive, -n -> print line numbers
```

Something similar should work for `findstr` as well.

**Comment by jeromtom** [comment]
Thank you for that. Used `findstr` and found the file location of missing links which can be viewed from [Google Sheet-PyBaMM Link Fixes](https://docs.google.com/spreadsheets/d/16ZapQc9CE0XzdqT_ck_mtRR1jOxSDoE27oRlWMNEKfM/edit?usp=sharing)
