### ISSUE TITLE
Running integration tests locally 

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/PyBaMM#2674]
To run integration tests locally using `run-tests.py` I have to do `python run-tests.py --unit --folder integration` but would expect to be able to just do `python run-tests.py --folder integration` (i.e. I shouldn't need unit **and** folder). Is this the intended behaviour? 

It would also be handy to be able to just do `python run-tests.py --integration`

**Comment by ayeankit** [comment]
Hello, @rtimms I would like to work on this issue, can you please assign it to me?

**Comment by rtimms** [comment]
thanks @ayeankit !

**Comment by ayeankit** [comment]
@rtimms I have raised the PR. Please review it.

**Comment by rtimms** [comment]
fixed by #2696
