### ISSUE TITLE
Solver setup goes to infinite calculation at 42 seconds no matter the drive cycle

### ISSUE THREAD

**Issue by cyasing** [pybamm-team/PyBaMM#2689]
I wrote a program to convert power to current at every time step using simple ohm's law for a battery pack with resistances in terminals and busbar with PyBaMM. I simulate just a single time step between each  update, but no matter how I change the drive cycle (averaging two time samples, omitting alternate samples, etc.), it seems that the process never proceeds further after "Start solver set-up" or while descritization. I have to terminate it manually.

What can be the possible reasons? I monitored some parameters like current, voltage, power, temperature, sei length, and concentration for each cell and time step, but nothing seems out of order.

Discretisation error:

![1E](https://user-images.githubusercontent.com/59028917/218732017-d4e77ce0-c5fb-416d-8ef7-e80f9aed6c10.png)

Solver error:

![x2](https://user-images.githubusercontent.com/59028917/218732381-c3ad4834-5cfe-4491-97d1-a413b57474e6.png)
![x3](https://user-images.githubusercontent.com/59028917/218732391-dbee28f2-ae18-4d9e-8e14-18e2d285a338.png)

_Originally posted by @cyasing in https://github.com/pybamm-team/PyBaMM/discussions/2688_

**Comment by cyasing** [comment]
I wrote a program to convert power to current at every time step using simple ohm's law for a battery pack with resistances in terminals and busbar with PyBaMM. I simulate just a single time step between each  update, but no matter how I change the drive cycle (averaging two time samples, omitting alternate samples, etc.), it seems that the process never proceeds further after "Start solver set-up" or while descritization. I have to terminate it manually.

**Comment by cyasing** [comment]
Can I instead send the whole script? Only if you're okay with it.

**Comment by tinosulzer** [comment]
You can, but it decreases the chance of your issue being fixed. See https://stackoverflow.com/help/minimal-reproducible-example

**Comment by cyasing** [comment]
Right. I did it in two different ways: 
1. mrc_half.py uses a research paper's equations (based on ohm's law)
2. (mrc_half_net.py) uses two functions of netlist_utils in liionpack for resolving the array of cells (did not import liionpack), then proceeded as normal.

Both end up stopping at different points (91-92 and 56-57 respectively), somehow both crossed the 42-43 mark. I am attaching them both here, along with the data:
[mrcs.zip](https://github.com/pybamm-team/PyBaMM/files/10754974/mrcs.zip)

**Comment by cyasing** [comment]
@tinosulzer Anything of note that you found?
