### ISSUE TITLE
Urgent: Update project size

### ISSUE THREAD

**Issue by henrykironde** [pybamm-team/PyBaMM#2692]
You have a project that has both 175 and 350 ((. Please use either 175 or 350, not both.  

> a 175h project, but can also be extended to a 350h project

**Comment by henrykironde** [comment]
@rtimms @tinosulzer @Saransh-cpp  @priyanshuone6

**Comment by tinosulzer** [comment]
We are discussing it and will update tomorrow

**Comment by henrykironde** [comment]
Thanks @tinosulzer. Just to give you some context, I am supposed to report back to Google today about the updates that were requested. The hr metric is used when selecting for budgeting purposes. I will go ahead and inform them that the last updates will be finalized by tomorrow.

**Comment by brosaplanella** [comment]
We have now updated the project duration to a single one.
