### ISSUE TITLE
node to edge and boundary value functions

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#271]
Use matrix operations instead of functions to implement these. 

In particular, we should be able to define a single matrix that calculates a boundary value and concatenates it to the existing state vector

**Comment by rtimms** [comment]
This will help with speeding up jacobian in #197 as autograd has an `elementwise_grad` which gives the diagonal of the jacobian *if* the jacobian is diagonal, e.g.

```
In [29]: x = 2 * np.ones(3)                                                                                                                                                                                 

In [30]: def f(x): 
    ...:     return x ** 2 
    ...:                                                                                                                                                                                                    

In [31]: autograd.jacobian(f)(x)                                                                                                                                                                            
Out[31]: 
array([[4., 0., 0.],
       [0., 4., 0.],
       [0., 0., 4.]])

In [32]: autograd.elementwise_grad(f)(x)                                                                                                                                                                    
Out[32]: array([4., 4., 4.])
```
If we know all our functions behave this way, then we can just make a sparse diag as the result

**Comment by tinosulzer** [comment]
Great - do you fancy giving it a go?

**Comment by rtimms** [comment]
Yep, I’m not here tomorrow, but can have a go next week!

**Comment by rtimms** [comment]
I've changed `compute_diffusivity` to be a matrix multiplication, but now we can end up with matrix multiplication in the denominator e.g. in `MacInnesStefanMaxwell` the term `pybamm.grad(c_e) / c_e` now goes to `pybamm.grad(c_e) / (M @ c_e)`. This is of the right size, but matrix multiplication in the denominator gives an error in `simplify_multiplication_division`. I'm having a little trouble understanding exactly how this is working. @tinosulzer @martinjrobins would you be able to help please?

**Comment by tinosulzer** [comment]
Would it work if you changed `pybamm.grad(c_e) / c_e`  to `pybamm.grad(log(c_e))` as a workaround ?

**Comment by tinosulzer** [comment]
^ apparently that doesn't work.

@martinjrobins was there any particular reason why we couldn't have a matrix multiplication in the denominator?

**Comment by martinjrobins** [comment]
I assumed that there shouldn't be any matrices / vectors on the
denominator. Is this not the case?

**Comment by tinosulzer** [comment]
If we use matrix-multiplication instead of a `Function` for calculating diffusivities (node to edge), then a matrix multiplication appears in the denominator:
```
disc.process_symbol(grad(c) / c) ---> (M1 @ c) / (M2 @ c)
```
where both `M1` and `M2` have size (n-1, n) (`n=len(c)`)

We could also just rewrite the model: `1/c * grad(c)` instead of `grad(c)/c` - @rtimms  can you see if that works?

**Comment by martinjrobins** [comment]
ok. So I guess the divide in this case is an element-wise divide, so this is valid? Perhaps I should allow mat-muls on the denominator then?

**Comment by tinosulzer** [comment]
yeah, in this case it's elementwise, so this kind of mat-mul can be allowed

**Comment by rtimms** [comment]
yep, changing to `1/c * grad(c)` works! still some other errors to with shapes on other tests which I'll investigate tomorrow

**Comment by rtimms** [comment]
@martinjrobins  @tinosulzer this has caused some more issues to come up with simplifying mat-muls, e.g. 

```
ipdb> model.concatenated_rhs.children[4].children[1].children[0].children[0].children[0].children[0].children[0]                                                                                            
MatrixMultiplication(-0x787c479f73fec89a, @, children=['Sparse Matrix (100, 99)', 'Sparse Matrix (99, 100) @ -domain concatenation ** Bruggeman coefficient * Sparse Matrix (99, 100) @ domain concatenation'], domain=['negative electrode', 'separator', 'positive electrode'])
ipdb> model.concatenated_rhs.children[4].children[1].children[0].children[0].children[0].children[0].children[0].simplify()                                                                                 
MatrixMultiplication(-0x143222ae39357139, @, children=['Sparse Matrix (100, 100)', '-y[104:204] ** 1.5 * Sparse Matrix (99, 100) @ y[4:104]'], domain=[])
ipdb> model.concatenated_rhs.children[4].children[1].children[0].children[0].children[0].children[0].children[0].evaluate(0,y0)                                                                             
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
ipdb> model.concatenated_rhs.children[4].children[1].children[0].children[0].children[0].children[0].children[0].simplify().evaluate(0,y0)                                                                  
*** ValueError: operands could not be broadcast together with shapes (100,1) (99,1)
```

here something like `A @ ((B @ u) * (C @ v))` is getting simplified to `(A @ B) @ (u * (C@v))`

**Comment by martinjrobins** [comment]
`A @ ((B @ u) * (C @ v))` shouldn't be simplified due to the `*` . I can write a test for this, are u and v StateVectors?

**Comment by rtimms** [comment]
Yup, u and v are StateVectors. Thanks!

**Comment by martinjrobins** [comment]
this is now fixed in PR #302

**Comment by tinosulzer** [comment]
how is this going @rtimms ?

**Comment by rtimms** [comment]
@tinosulzer have just pushed the matmul version of boundary value and node to edge. they appear to work apart from a few shape issues (see #301). hopefully this should be OK after that is fixed.
