### ISSUE TITLE
Open Discussion for different detailed Issues template

### ISSUE THREAD

**Issue by jaskiratsingh2000** [pybamm-team/PyBaMM#2712]
### Description

I have been coming across various issuyes and most of the issues lack proper descripton about what and where to do the implementation. Therefore this is the open ended discussion where I or anyone can share the templates for the different issues.

**Comment by Saransh-cpp** [comment]
The existing issue templates look good to me. I don't think we can add issue templates for every possible type of issue a user might face. What we can do is maybe label the issues better -
- cleanup
- docs
- dependencies (or upstream)
- installation
- performance
- research
- tests (or CI)
- ...
