### ISSUE TITLE
Rename `one_plus_dlnf_dlnc` to `thermodynamic_factor`

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#2726]
Maybe for a separate (small) issue, should we rename this to `thermodynamic_factor`? It is not much longer, and more informative.

_Originally posted by @brosaplanella in https://github.com/pybamm-team/PyBaMM/pull/2419#discussion_r1116150328_

**Comment by tinosulzer** [comment]
Changes to be made:
- everywhere `one_plus_dlnf_dlnc` appears, replace it with `thermodynamic_factor`
- everywhere "1 + dlnf/dlnc" appears, replace it with "Thermodynamic factor"
- add specific check and deprecation message [here](https://github.com/pybamm-team/PyBaMM/blob/develop/pybamm/parameters/parameter_values.py#L297) if `values = "1 + dlnf/dlnc"`

**Comment by ayeankit** [comment]
Hello @tinosulzer , Can I work this issue?

**Comment by jeromtom** [comment]
I am working on this issue with my PR #2727, and it might take some more time. I would like this issue to be assigned to me. Thank you.
