### ISSUE TITLE
[Bug]: Class Variable returns None when getting the print_name attribute instead of the name

### ISSUE THREAD

**Issue by chmabaur** [pybamm-team/PyBaMM#2762]
### PyBaMM Version

23.2

### Python Version

3.9.13

### Describe the bug

var1 = pybamm.Variable('Var1', print_name=None)
type(var1.print_name)
Out[49]: NoneType

This is an issue for model.latexify() function, as it returns an error if the print_name of a variable is of None type:

  Cell In[51], line 1
    model.latexify()

  File ~\AppData\Local\Programs\Python\Environments\gen-env\lib\site-packages\pybamm\models\base_model.py:1050 in latexify
    return Latexify(self, filename, newline).latexify()

  File ~\AppData\Local\Programs\Python\Environments\gen-env\lib\site-packages\pybamm\expression_tree\operations\latexify.py:246 in latexify
    var_symbol = sympy.Symbol(var.print_name)

  File ~\AppData\Local\Programs\Python\Environments\gen-env\lib\site-packages\sympy\core\symbol.py:296 in __new__
    return Symbol.__xnew_cached_(cls, name, **assumptions)

  File ~\AppData\Local\Programs\Python\Environments\gen-env\lib\site-packages\sympy\core\cache.py:70 in wrapper
    retval = cfunc(*args, **kwargs)

  File ~\AppData\Local\Programs\Python\Environments\gen-env\lib\site-packages\sympy\core\symbol.py:326 in __xnew_cached_
    return Symbol.__xnew__(cls, name, **assumptions)

  File ~\AppData\Local\Programs\Python\Environments\gen-env\lib\site-packages\sympy\core\symbol.py:301 in __xnew__
    raise TypeError("name should be a string, not %s" % repr(type(name)))

TypeError: name should be a string, not <class 'NoneType'>

According to the documentation of the Variable class, type(var1.print_name) should print the variable name 'Var1' instead of None, and I thus assume this is a bug.

### Steps to Reproduce

import pybamm

var1 = pybamm.Variable('Var1', print_name=None)
type(var1.print_name)
Out[49]: NoneType

**Comment by brosaplanella** [comment]
Note that `print_name` needs to be defined by the user when creating a new variable. In the example you have set it to be `None` and that's what the code is returning. Can you provide some more detail?

**Comment by chmabaur** [comment]
Well it may be a bit picky, but according to the documentation, my example should print 'Var1' instead of None, see print screen of the documentation. The main issue is however https://github.com/pybamm-team/PyBaMM/issues/2763 [bug](https://github.com/pybamm-team/PyBaMM/issues?q=is%3Aissue+is%3Aopen+label%3Abug)Something isn't working
#2763
![image](https://user-images.githubusercontent.com/127507466/224338783-42f9671d-2191-4cf0-90bc-1c133a38de5c.png)

**Comment by brosaplanella** [comment]
Fair point! Not sure if this is intended and the docs are old, or if it is an actual bug. I will summon @tinosulzer and @priyanshuone6 as they will know better.
