### ISSUE TITLE
[Bug]: Latexify

### ISSUE THREAD

**Issue by chmabaur** [pybamm-team/PyBaMM#2763]
### PyBaMM Version

23.2

### Python Version

3.9.13

### Describe the bug

Latexify does not work on an SPMe with a thermal submodel.

### Steps to Reproduce

import pybamm
model = pybamm.lithium_ion.SPMe({"thermal": "lumped"})
model.latexify()

### Relevant log output

```shell
model.latexify()
Traceback (most recent call last):

  Cell In[3], line 1
    model.latexify()

  File ~\AppData\Local\Programs\Python\Environments\gen-env\lib\site-packages\pybamm\models\base_model.py:1050 in latexify
    return Latexify(self, filename, newline).latexify()

  File ~\AppData\Local\Programs\Python\Environments\gen-env\lib\site-packages\pybamm\expression_tree\operations\latexify.py:245 in latexify
    var_symbol = sympy.Symbol(var.print_name)

  File ~\AppData\Local\Programs\Python\Environments\gen-env\lib\site-packages\sympy\core\symbol.py:296 in __new__
    return Symbol.__xnew_cached_(cls, name, **assumptions)

  File ~\AppData\Local\Programs\Python\Environments\gen-env\lib\site-packages\sympy\core\cache.py:70 in wrapper
    retval = cfunc(*args, **kwargs)

  File ~\AppData\Local\Programs\Python\Environments\gen-env\lib\site-packages\sympy\core\symbol.py:326 in __xnew_cached_
    return Symbol.__xnew__(cls, name, **assumptions)

  File ~\AppData\Local\Programs\Python\Environments\gen-env\lib\site-packages\sympy\core\symbol.py:301 in __xnew__
    raise TypeError("name should be a string, not %s" % repr(type(name)))

TypeError: name should be a string, not <class 'NoneType'>
```

**Comment by brosaplanella** [comment]
It seems that the variable causing trouble is `'Volume-averaged cell temperature [K]'`. Irrespective of what happens with #2762, this variable should be given a nice print name, like `\bar{T}`. This is a good issue to get started with PyBaMM, do you want to give it a go? Basically you need to define the `print_name` where the variable is defined:

https://github.com/pybamm-team/PyBaMM/blob/307836008f61d70b1afed537eea9aa7818b25f2e/pybamm/models/submodels/thermal/lumped.py#L38

However, it would also be good to:
1. Ensure other thermal models work too.
2. Add tests to check that.
