### ISSUE TITLE
[Bug]: Short discharge pulse in drive cycle partially ignored

### ISSUE THREAD

**Issue by DavidMStraub** [pybamm-team/PyBaMM#2789]
### PyBaMM Version

v23.2

### Python Version

3.8.10

### Describe the bug

I am simulating a drive cycle with a 1C discharge for a couple of minutes, followed by a rest phase, followed by a 10 second 1C discharge (beginning of a typical HPPC test). I am using a drive cycle rather than an Experiment as I am fitting to experimental data.

I noticed that, during the short pulse, the predicted voltage is not as expected and traced it back to the absence of any diffusive contribution; in fact the concentration in the electrodes does not change during the pulse. So it looks like part of the simulation (diffusion equation) ignores the presence of the pulse.

### Steps to Reproduce

(Edit: modified the MWE to make it occur even with safe Casadi solver)

MWE:

```python
import matplotlib.pyplot as plt
import numpy as np
import pybamm

model = pybamm.lithium_ion.SPM()
Q = model.default_parameter_values["Nominal cell capacity [A.h]"]

time = np.arange(0, 1100, 2, float)
current = 0 * time
current[(time <= 500)] = Q
current[(time >= 1000) & (time <= 1010)] = Q

param = model.default_parameter_values.copy()
param["Current function [A]"] = pybamm.Interpolant(
    time, current, model.timescale * pybamm.t
)

sim = pybamm.Simulation(
    model,
    parameter_values=param,
    solver=pybamm.CasadiSolver(atol=1e-3, rtol=1e-3, mode="safe"),
)
sol = sim.solve()
```

Plot:

```python
plt.plot(time, current)
plt.plot(sol["Time [s]"].entries, sol["Current [A]"].entries, ls="--")
plt.show()

for domain in ["positive", "negative"]:
    plt.plot(
        sol["Time [s]"].entries, sol[f"Average {domain} particle concentration"].entries
    )
plt.show()
```

Output: 

![image](https://user-images.githubusercontent.com/10965193/226384782-7d5174d1-e216-435a-aa39-343f3050df4e.png)

So while the current correctly shows the short peak, it has no impact on concentration.

Note that by playing with the length of the discharge and rest phases, one can make the issue appear and disappear.

**Comment by martinjrobins** [comment]
Hi @DavidMStraub. I'm guessing that the solver is stepping over these discontinuities in your current function interpolant. We try to detect discontinuities in the equations given to a model, but we don't try and detect discontinuities in interpolants. You can manually add discontinuity events to your model like so:

```python
model.events.append(pybamm.Event("current_disc1", 500 / model.timescale , pybamm.EventType.DISCONTINUITY))
model.events.append(pybamm.Event("current_disc2", 1000 / model.timescale, pybamm.EventType.DISCONTINUITY))
model.events.append(pybamm.Event("current_disc3", 1010 / model.timescale, pybamm.EventType.DISCONTINUITY))
```

Do this before passing your `model` to the `pybamm.Simulation` contructor. Let me know if this fixes your problem.

**Comment by martinjrobins** [comment]
This looks like a bug in the fast casadi solver, I can have a look at this and try to work out what is going on. In the meantime, have you tried the IDAKLU solver, or the "slow" CasadiSolver? Both of these treat events and sensitivities differently, so you might have more success with these

**Comment by DavidMStraub** [comment]
Thanks!

Actually Using `mode="safe"` in the last example does not solve the error, same for `"fast with events"`. I have not tried out IDAKLU yet but this might be a good opportunity. I need to follow [these instructions](https://pybamm.readthedocs.io/en/v0.2.3/install/install-klu.html), correct?

**Comment by DavidMStraub** [comment]
Sorry, I realized I was on a developer install, but installing the wheel `IDAKLUSolver` works out of the box.

**Comment by DavidMStraub** [comment]
So with IDAKLU the above example works (the step in concentration is present) even without manually adding the events.

I do run into another (unrelated) issue though: calling

```python
sol["Terminal voltage [V]"].sensitivities
```
raises a `KeyError` because the `"all"` key is missing, but actually

```python
sol["Terminal voltage [V]"].solution_sensitivities["Negative particle radius [m]"]
```
does work...

**Comment by DavidMStraub** [comment]
(I should note that my IDAKLU experiments are done with PyBaMM v22.12 rather than v23.2.

**Comment by martinjrobins** [comment]
two bugs to fix then ;) But I'm glad the IDAKLU solver is workable for you, the way it treats events is much superior to the casadi solver. Eventually we're likely to make the idaklu solver the default pybamm solver.
