### ISSUE TITLE
python.version and .readthedocs.yml are deprecated

### ISSUE THREAD

**Issue by agriyakhetarpal** [pybamm-team/PyBaMM#2804]
Use `build.tools.python` and `.readthedocs.yaml` instead — ([1](https://docs.readthedocs.io/en/stable/config-file/v2.html#python-version),[2](https://docs.readthedocs.io/en/stable/config-file/index.html#configuration-file))

This does not break the build, but should be an easy fix for anyone who may want to take it up

**Comment by arjxn-py** [comment]
I would like to work on this issue.
I would be glad if you could further specify a bit more.

**Comment by arjxn-py** [comment]
Kudos @agriyakhetarpal, your explanation is a big help.
Thanks @Saransh-cpp for assigning the issue.
