### ISSUE TITLE
adding `nbQA` support for example notebooks

### ISSUE THREAD

**Issue by agriyakhetarpal** [pybamm-team/PyBaMM#2813]
### Description

[nbQA](https://nbqa.readthedocs.io/en/latest/examples.html#command-line-examples) now includes support for `ruff` to format Jupyter notebooks and already has integration for `black`, so we can add it for both (or even just`ruff` would be fine)

### Motivation

We already use `ruff` as a pre-commit hook

### Possible Implementation

in `.pre-commit-config.yaml`

### Additional context

From "Does Ruff support Jupyter notebooks? -- https://beta.ruff.rs/docs/faq/#does-ruff-support-jupyter-notebooks"

**Comment by arjxn-py** [comment]
I went through the resources you have attached & I want to give it a try.
Furthermore I feel that I might have doubts while working on it which I'll be clearing here itself.

**Comment by Saransh-cpp** [comment]
@arjxn-py this is more of a discussion at this moment. We want to see how the notebooks will evolve during GSoC and then decide if we want these pre-commits or not.

**Comment by arjxn-py** [comment]
Got it @Saransh-cpp.

**Comment by Saransh-cpp** [comment]
@agriyakhetarpal I think this aligns with your GSoC project? Feel free to pick this up. @arjxn-py can also pick this up as it relates to the infrastructure project as well.

**Comment by arjxn-py** [comment]
Happy to take this up.

**Comment by agriyakhetarpal** [comment]
That's nice. I discussed embedding the example notebooks on readthedocs during today's meeting (which is why I was waiting on this), so I will be restructuring some parts of the documentation in a PR soon — @arjxn-py I would recommend starting with this after that gets merged

**Comment by Saransh-cpp** [comment]
@arjxn-py it would be nice to add some pre-commits for notebooks once #3043 is merged. You can maybe pick this up once the option dependencies PR is merged.
