### ISSUE TITLE
Try using towncrier for changelog

### ISSUE THREAD

**Issue by valentinsulzer** [pybamm-team/PyBaMM#2885]
https://towncrier.readthedocs.io/en/stable/

This might be easier to use than manually changing the changelog file. Could be done as part of the documentation gsoc project

**Comment by jeromtom** [comment]
Sure, we can do this as a stretch goal. The changelog is in md (markdown format), we need to change it to rst (reStructured Text) before using towncrier.

**Comment by arunavabasu-03** [comment]
can i work on this ??

**Comment by tinosulzer** [comment]
sure

**Comment by tinosulzer** [comment]
@arunavabasu-03 are you still working on this?

**Comment by arunavabasu-03** [comment]
> @tinosulzer , we have to do this with `jinija templateing` or `<version>.md` file for every release .

Can you pls clarify this @tinosulzer ?
