### ISSUE TITLE
Scheduled benchmarks failing - "Permission denied to tlestang"

### ISSUE THREAD

**Issue by Saransh-cpp** [pybamm-team/PyBaMM#2915]
The scheduled benchmark workflow is unable to push the results to the `pybamm-bench` repository and errors out with the following logs -
```
[main 71a72bc] Add new results
 2 files changed, 121 insertions(+), 100 deletions(-)
 create mode 100644 results/GitHubRunner/521c5f4a-virtualenv-py3.8-casadi-cmake-numpy-wget-LD_LIBRARY_PATH_home_runner_.local_lib.json
remote: Permission to pybamm-team/pybamm-bench.git denied to tlestang.
fatal: unable to access 'https://github.com/pybamm-team/pybamm-bench/': The requested URL returned error: 403
```
I am guessing this is caused by the re-organization of GitHub roles that we recently had. I can see 3 repository secrets that are required for pushing the results -
- BENCH_PAT
- PUSH_BENCH_EMAIL
- PUSH_BENCH_NAME

These secrets should be swapped with a maintainer's PAT, email, and name (someone who has direct push access to `pybamm-bench` - maybe @tinosulzer or @brosaplanella).

**Comment by tinosulzer** [comment]
Happy to give my details, how do I find what those are?

**Comment by Saransh-cpp** [comment]
A Personal Access Token can be generated through [GitHub](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token), and I am guessing it must have the write permission enabled (will be asked while you are creating the token). The email and name should be the ones that are associated with your GitHub account.

The values of repository secrets can be overridden here - https://github.com/pybamm-team/PyBaMM/settings/secrets/actions

**Comment by tinosulzer** [comment]
I updated them. Not sure I gave the correct permissions but let's see (I gave read and write access for contents of pybamm-bench only)

**Comment by Saransh-cpp** [comment]
Worked - https://github.com/pybamm-team/PyBaMM/actions/runs/4867968390 🎉
