### ISSUE TITLE
[Bug]: Installing SuiteSparse and SUNDIALS with `tox -e pybamm-requires` will fail silently in some cases

### ISSUE THREAD

**Issue by agriyakhetarpal** [pybamm-team/PyBaMM#2968]
### PyBaMM Version

23.4.1

### Python Version

3.8–3.11

### Describe the bug

In cases where the `pybamm-requires` environment created by `tox`, i.e., with the `tox -e pybamm-requires` command, fails to install `SUNDIALS` with `scripts/install_KLU_sundials.py`, it does not display a failure message and rather will still succeed – a log output of `pybamm-requires: commands succeeded, congratulations :)` gets displayed in the `Install SuiteSparse and SUNDIALS` step on the workflows, even if the configuration for SuiteSparse and SUNDIALS was not setup properly with `CMake`.

This does, subsequently, fail the next step that starts the unit tests with `tox -e unit`, but the intended behaviour is that it should fail directly on the previous step itself (which means it is currently failing silently).

In the current failures: I feel it has something to do with either the caching of the `cmake` arguments or the `BLAS` library not getting installed, but I am unsure of the actual reason(s).

### Steps to Reproduce

In the GitHub Actions runner on PR #2923 (more details below)

### Relevant log output

Some logs are available in the `Installing SuiteSparse and SUNDIALS` step in the actions (in decreasing order of recency): 

https://github.com/pybamm-team/PyBaMM/actions/runs/5015359206/jobs/8990878089
https://github.com/pybamm-team/PyBaMM/actions/runs/4892736342/jobs/8734863741
https://github.com/pybamm-team/PyBaMM/actions/runs/4886496365/jobs/8721917003
https://github.com/pybamm-team/PyBaMM/actions/runs/4885731974/jobs/8720171150

**Comment by Saransh-cpp** [comment]
@agriyakhetarpal could you try merging the [`sundials-ret-code`](https://github.com/pybamm-team/PyBaMM/tree/sundials-ret-code) branch in your PR once?

**Comment by agriyakhetarpal** [comment]
Yes, testing this locally seems to fix this issue in particular – gives me an `InvocationError` with the `cmake` steps. I have pushed the changes to #2923
