### ISSUE TITLE
Splitting the required dependencies into optional dependencies

### ISSUE THREAD

**Issue by arjxn-py** [pybamm-team/PyBaMM#3035]
### Description

Currently pybamm is installing many dependencies we want to have a lite version of pybamm by splitting the required deps into optional deps

**Comment by Saransh-cpp** [comment]
Related to #2457

**Comment by Saransh-cpp** [comment]
Discussion from today's meeting -
- Making dependencies like `imageio` optional like `jupyter`
  - Adding multiple small optional tags like `[gif]` for `imageio`
  - Adding a single big tag to cover all the additional dependencies, like `[all_optional]`
  - Visualise dependencies using https://pypi.org/project/pipdeptree/ 

Maintainers can iteratively add here the dependencies which they think can be made optional.

**Comment by tinosulzer** [comment]
The following dependencies can be made optional without affecting 95% of functionality:
- pandas
- anytree
- autograd
- scikit-fem
- pybtex
- sympy

**Comment by agriyakhetarpal** [comment]
The dependency graph with `pipdeptree` is also related to the documentation project, I may pick that up later if that's okay?

**Comment by arjxn-py** [comment]
> The following dependencies can be made optional without affecting 95% of functionality

How should I go with grouping them further or should we have a single tag say `dev`?

**Comment by brosaplanella** [comment]
> The following dependencies can be made optional without affecting 95% of functionality:
> 
> * pandas

About pandas, I think the trickiest point will be that some parameter sets won't work without pandas (they use `read_csv`). One way around would be to hardcode the csv files in the Python script for the given parameter.

Just to clarify, I am not against pandas being optional, but I think it would be good to keep all parameters working with the basic PyBaMM.

**Comment by tinosulzer** [comment]
For pandas we could set the default to use the equivalent numpy function and then we would not need pandas

I would actually put tqdm and bpx in the easy bucket too

For the hard ones:
- scipy: impossible to get rid of if solving PDEs (it is used in the discretization)
- casadi: very hard to get rid of and would lead to performance regressions
- xarray: impossible to get rid of without having annoying-to-maintain try-excepts in the `ProcessedVariable` class

**Comment by Saransh-cpp** [comment]
> How should I go with grouping them further or should we have a single tag say dev?

There should be smaller groups, like `[plot]` for `matplotlib` and `imageio` and `[jax]` for `jax` and `jaxlib`, and a larger group, like `[optionals]` with every optional library included (maybe not the ones that are OS specific).

**Comment by tinosulzer** [comment]
I really like the way pandas handles and documents optional dependencies: https://pandas.pydata.org/docs/getting_started/install.html#optional-dependencies

So `pybamm[all]` would install everything.

I'm not sure whether zsh handles square brackets so we might need to encourage using quotes e.g. `pip install "pybamm[all]"` (as pandas does)

**Comment by arjxn-py** [comment]
Pandas handles this type of installation using [`pyproject.toml`](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/) introduced in [PEP 518](https://peps.python.org/pep-0518/) but our build-system is based on `setup.py` which I'd also need to figure out to migrate to `pyproject.toml`

**Comment by Saransh-cpp** [comment]
You don't necessarily need `pyproject.toml` to create optional dependencies. Migrating to `pyproject.toml` would be a bit tricky (we've tried once 🙂), but yes, very much appreciated. I'm not sure which build backend is used by `pandas` but you can look into `setuptools`, `scikit-build`, and `meson-py`.
