### ISSUE TITLE
Improve the `nox` CI

### ISSUE THREAD

**Issue by Saransh-cpp** [pybamm-team/PyBaMM#3048]
Once #3005 is merged, we can improve the `nox` CI a bit more -

- [x] refactoring the env variables (will have to check, but the current version has a lot of repetitions)
- [x] refactoring the installation step in a separate Python function and calling it in every session 
- [x] [adding default sessions](https://github.com/scikit-hep/vector/blob/12dc350c28b1bfc4d1fac3e008b8b082101ca9a5/noxfile.py#L9)
- [x] [adding a `pre-commit` session](https://github.com/scikit-hep/vector/blob/12dc350c28b1bfc4d1fac3e008b8b082101ca9a5/noxfile.py#L15-L19)
- [x] adding more informative commands in docs, like `nox -l`, `nox -p`
- [x] Cache nox environment for speedup
- [x] make `nox -s dev` run like `nox -s dev --verbose`
- [ ] add [docstrings for nox sessions](https://nox.thea.codes/en/stable/config.html#session-description)

cc : @arjxn-py @agriyakhetarpal

**Comment by agriyakhetarpal** [comment]
See also: [The Nox Cookbook](https://nox.thea.codes/en/stable/cookbook.html)
