### ISSUE TITLE
Raise error for unknown parameter sets

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/PyBaMM#3063]
Raise an error when you do e.g. `parameter_values = pybamm.ParameterValues("Junk")`. 

Need to replace `if isinstance(values, str) and values in pybamm.parameter_sets:` with `if isinstance(values, str) and values in pybamm.parameter_sets.keys():` [here](https://github.com/pybamm-team/PyBaMM/blob/develop/pybamm/parameters/parameter_values.py#L63) and raise an error if the name isn't found.

**Comment by tommaull** [comment]
please assign me!
