### ISSUE TITLE
Create copy of simulation with updated parameters

### ISSUE THREAD

**Issue by brosaplanella** [pybamm-team/PyBaMM#3113]
In pybamm-param we need to create a copy of a given simulation but changing some parameters (in that case, setting them to `[input]` so we can fit them to data). At the moment we do that locally, but just wanted to check if it would be a relevant feature to have in the `Simulation` class (even if it is as an internal method). What are people's thoughts?

This could also be included in a `copy` method for the `Simulation` class, which currently does not exist.

**Comment by tinosulzer** [comment]
This is a niche use case so closing
