### ISSUE TITLE
[Bug]: Coordinate systems of variables do not get checked against known

### ISSUE THREAD

**Issue by brosaplanella** [pybamm-team/PyBaMM#3114]
### PyBaMM Version

23.5

### Python Version

3.9.16

### Describe the bug

Currently the coordinate system of a variable is not checked against the known system. This means that if the wrong argument is passed (e.g. due to a typo) it will default to `"cartesian"` without throwing an error.

### Steps to Reproduce

The MWE would be very lengthy, but basically it can be checked that:

1. The only place where `KNOWN_COORD_SYS` is checked is to test meshes for the battery model (i.e. it does not actually check for wrong coordinate systems).
2. In `finite_volume.py` there is an else statement that means that anything not being cylindrical polar or spherical polar will default to cartesian, see

https://github.com/pybamm-team/PyBaMM/blob/fffe650253596f14b6918d9e57fdd912bc3cfbdc/pybamm/spatial_methods/finite_volume.py#L139-L150

**Comment by brosaplanella** [comment]
Ooops, that was already reported in #2220 (contains some additional info). Let's make sure we close both issues when we merge PR.

**Comment by RuiheLi** [comment]
Yes, I will. Will look into #2220. Thanks for the remind! @brosaplanella

**Comment by RuiheLi** [comment]
> Yes, I will. Will look into #2220. Thanks for the remind! @brosaplanella

Just checked the time of both issue, will look into both.

**Comment by rtimms** [comment]
closing, see #4600
