### ISSUE TITLE
[Bug]: benchmarks are failing

### ISSUE THREAD

**Issue by agriyakhetarpal** [pybamm-team/PyBaMM#3124]
### PyBaMM Version

23.5

### Python Version

all

### Describe the bug

The [scheduled benchmarks](https://github.com/pybamm-team/PyBaMM/actions/runs/5492426530) and the benchmarks on PRs are failing because the `asv` configuration fails to find `pybtex`, since it is not a core dependency but has been shifted to the `[cite]` extras group after #3044 was merged

### Steps to Reproduce

Via the `benchmarks_on_push.yml` and `periodic_benchmarks.yml` workflow files

**Comment by agriyakhetarpal** [comment]
I tried adding `pybtex` to the Python dependencies in https://github.com/pybamm-team/PyBaMM/commit/59fa13d4411b5973767eb8a3c56e9066ce768ad4, but that did not work—is there a way to install the extras from a built wheel file?

**Comment by Saransh-cpp** [comment]
You'll probably need to add `pybtex` in https://github.com/pybamm-team/PyBaMM/blob/develop/asv.conf.json
