### ISSUE TITLE
create calculate_sensitivities for experiment

### ISSUE THREAD

**Issue by Mrzhang-hub** [pybamm-team/PyBaMM#3133]
### Description

It seems now that pybamm does not support calculate_sensitivities method for experiment. However, when working on parameter estimation with gradient-based method, it is needed to access parameter sensitivities(partial derivative of terminal voltage to parameters) under certain charging/discharging experiment. So is it possible to add calculate_sensitivities for experiment? @brosaplanella  @tinosulzer

**Comment by tinosulzer** [comment]
I don't know how we would do this because we'd have to differentiate through the events (such as the voltage cut-offs), which as far as I know is not possible

**Comment by martinjrobins** [comment]
agree, I think in this case you would have to do the parameter estimation over each separate part of the experiment (i.e. between the events)
