### ISSUE TITLE
[Bug]: problem

### ISSUE THREAD

**Issue by ADSDAW** [pybamm-team/PyBaMM#3136]
### PyBaMM Version

1.1.5

### Python Version

3.7

### Describe the bug

cycle_life = sim.solution.event("Cycle count")[0].event_number

AttributeError: 'Solution' object has no attribute 'event'

How to solve this problem

### Steps to Reproduce

 i dont know

**Comment by tinosulzer** [comment]
Where did you find this syntax? There's never been a `solution.event`
