### ISSUE TITLE
Battery pack simulation

### ISSUE THREAD

**Issue by okmechak** [pybamm-team/PyBaMM#3147]
### Description

We propose an enhancement to PyBaMM that includes a new module. This module's purpose is to enable the creation of cell packs, which can be organized in parallel, in series, or as a combination of both. Furthermore, these packs can be nested, meaning a pack can contain other packs. This feature provides flexibility in creating diverse battery pack configurations. Additionally, it allows for the simulation of these intricate arrangements of battery packs, thereby broadening the scope of potential battery pack analyses.

### Motivation

This module would allow for the creation of cell packs, which can be arranged in parallel, in series and combination of both. Moreover, these packs could include other packs within them. This functionality would enable the creation of a wide variety of battery pack configurations and facilitate the simulation of these configurations. The module would also provide different definitions for the State of Charge (SOC) applicable to these various pack arrangements.

**Comment by rtimms** [comment]
Hey @okmechak, check out [liionpack](https://github.com/pybamm-team/liionpack), which aims to do exactly this. We're always looking for new contributors so please feel free to open an issue or discussion, or jump on our Slack to chat more.
