### ISSUE TITLE
Raise error if empty list passed to `QuickPlot`

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/PyBaMM#3172]
If you pass any empty list to `QuickPlot` you get the error:
```
  File "/Users/robertwtimms/Documents/PyBaMM/test.py", line 3, in <module>
    pybamm.QuickPlot([])
  File "/Users/robertwtimms/Documents/PyBaMM/pybamm/plotting/quick_plot.py", line 146, in __init__
    output_variables = models[0].default_quick_plot_variables
IndexError: list index out of range
```

It would be nicer to catch this with a more informative error earlier so you can check if you've made a silly mistake like I did where I wasn't appending solutions to a list.

Code to reproduce:
```python3
import pybamm

pybamm.QuickPlot([])
```

**Comment by tinosulzer** [comment]
Also it should work if a single variable is passed in as the plotting variable instead of a list
