### ISSUE TITLE
Remove particle size parameters: mean, standard deviation

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#3219]
They are defined in the `GeometricParameters` and `LithiumIonParameters`
https://github.com/pybamm-team/PyBaMM/blob/develop/pybamm/parameters/geometric_parameters.py#L113-L115
but not used by any of the models

Having them in is a bit confusing, since changing them does not affect the distribution, which is entirely controlled by `f_a_dist` https://github.com/pybamm-team/PyBaMM/blob/develop/pybamm/parameters/size_distribution_parameters.py#L77

A user might think that they can change the distribution by changing one of the mean/sd parameters, but they will have no effect

**Comment by tinosulzer** [comment]
Edit: `R_min` and `R_max` determine the geometry so should be kept

Very easy fix: remove the mean/sd parameters from `size_distribution_parameters.py`, and remove `.sd_a` in the (very few) places it appears. `R_mean` is never defined.

**Comment by jeromtom** [comment]
I don't think we can remove `sd_p` and `sd_n` as they are used in the calculations of `R_min` and `R_max` which like you said determine the geometry.

**Comment by Jay-sanjay** [comment]
@jeromtom  are you still working on this issue

**Comment by jeromtom** [comment]
Yes
