### ISSUE TITLE
Rename "positive electrode diffusivity" to "positive particle diffusivity"?

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#3229]
It's a better name, but a breaking change so maybe not worth it.
We can make it not breaking by returning "positive particle diffusivity" from `parameter_values["Positive electrode diffusivity"]` with a deprecation warning

**Comment by brosaplanella** [comment]
Non-breaking change with deprecation warning sounds good to me.

**Comment by rtimms** [comment]
Agreed.

**Comment by ejfdickinson** [comment]
"Positive electrode particle diffusivity" feels more correct albeit more verbose. What's a 'positive particle'..?

**Comment by tinosulzer** [comment]
I think "positive particle" is fairly self-explanatory, we already have a bunch of variables like "Positive particle concentration"
