### ISSUE TITLE
SPM negative electrode half cell model doesn't work

### ISSUE THREAD

**Issue by rb902** [pybamm-team/PyBaMM#3259]
Hi,

I was looking into setting up 2 half cell single particle models. The one for the positive electrode works perfectly:
```
positive_model = pybamm.lithium_ion.SPMe({"working electrode": "positive"})

#setting parameter values
positive_param = positive_model.default_parameter_values
positive_param["Current function [A]"] = "[input]"

# create simulation
positive_simulation = pybamm.Simulation(positive_model)

# pass the current as an input
positive_simulation.solve(t_eval, inputs={"Current function [A]": 1.6})

positive_simulation.plot()
```
but when I try the same for the negative electrode, this line of code doesn't work:
```
negative_model = pybamm.lithium_ion.SPMe({"working electrode": "negative"})
```
as it says:

ModelError: Missing variable for submodel 'positive electrode potential': 'Positive current collector potential [V]'.
Check the selected submodels provide all of the required variables.

since the full cell model works, I'm not sure what's going on.

**Comment by rtimms** [comment]
There is a PR open to resovle this https://github.com/pybamm-team/PyBaMM/pull/3198
