### ISSUE TITLE
MacOS Nox documentation build error

### ISSUE THREAD

**Issue by kratman** [pybamm-team/PyBaMM#3319]
While trying to build the documentation, I ran into an issue.

Running ```nox -s docs``` produces the following error:
```
Session docs raised exception AttributeError('__enter__')
```

The nox session for docs is the following:
```python
@nox.session(name="docs")
def build_docs(session):
    """Build the documentation and load it in a browser tab, rebuilding on changes."""
    envbindir = session.bin
    session.install("-e", ".[all,docs]")
    with session.chdir("docs/"):
        session.run(
            "sphinx-autobuild",
            "-j",
            "auto",
            "--open-browser",
            "-qT",
            ".",
            f"{envbindir}/../tmp/html",
        )
```
The AttributeError is caused by the "with" clause in the code above.

The error no longer occurs when I remove the "with" block as shown below:
```python
@nox.session(name="docs")
def build_docs(session):
    """Build the documentation and load it in a browser tab, rebuilding on changes."""
    envbindir = session.bin
    session.install("-e", ".[all,docs]")
    session.chdir("docs")
    session.run(
        "sphinx-autobuild",
        "-j",
        "auto",
        "--open-browser",
        "-qT",
        ".",
        f"{envbindir}/../tmp/html",
    )
```

Has anyone else encountered this problem? I have my change on a branch and can make a pull request. I am guessing it is an issue with the version of Nox I have installed. However, if this small change could help other users, then is there a strong reason not to do it? 

I attached some basic system information below, I can add more if required.

System information:
MacOS
Apple silicon (M1 Chip)
Python 3.9
PyBaMM 23.5
Nox 2021.10.1

**Comment by agriyakhetarpal** [comment]
Thanks for the MWE, I am able to reproduce the error—could you please update `nox` to a newer version (i.e., `nox==2023.4.22`)? The documentation builds successfully for me then.

**Comment by agriyakhetarpal** [comment]
The error comes from the older version of `nox` not having a context manager at its disposal configured with `session.chdir`syntax, which is present in the latest version and thus enables the use of the `with` keyword

**Comment by kratman** [comment]
Yes I will update my version of Nox and I am going to try to figure out why such an old version was installed for my Mac. The current version on Conda is 2023.4.22, but installing it this week from conda-forge downloaded 2021.10.1. Likely something from my initial environment setup.

Is there an interest in switching away from the "with" keyword so it is backwards compatible, or should I discard my branch?

**Comment by agriyakhetarpal** [comment]
It could be a nice thing to make it backwards-compatible: @Saransh-cpp, what do you think? For now, you could use the `sphinx-autobuild` command that it wraps to get the build working

**Comment by kratman** [comment]
Ok I will make the PR and then it can be closed if the change is not wanted.

**Comment by kratman** [comment]
@agriyakhetarpal Change done in #3322
