### ISSUE TITLE
[Bug]: Cannot solve the composite SiG-anode DFN model with an initial_soc

### ISSUE THREAD

**Issue by michelegalasso** [pybamm-team/PyBaMM#3321]
### PyBaMM Version

23.5

### Python Version

3.10.12

### Describe the bug

I am trying to use the composite SiG-anode DFM model by following the guide at [this link](https://docs.pybamm.org/en/latest/source/examples/notebooks/models/composite_particle.html). I can reproduce the steps of the guide, but when I introduce an initial_soc value I get the following error:

```KeyError: "'Negative electrode OCP [V]' not found. Use the dimensional version 'Primary: Negative electrode OCP [V]' instead."```

### Steps to Reproduce

```import pybamm
import numpy as np

# load parameter values
params = pybamm.ParameterValues('Chen2020_composite')

# set current equal to C/40
params['Current function [A]'] = params['Nominal cell capacity [A.h]'] / 40

# load battery model
model = pybamm.lithium_ion.DFN({
    'particle phases': ('2', '1'),
    'open-circuit potential': (('single', 'current sigmoid'), 'single')
})

# simulate
sim = pybamm.Simulation(model, parameter_values=params)
sim.solve(t_eval=np.arange(0, 50 * 3600, 60), initial_soc=0.2)```

### Relevant log output

```shell
KeyError: "'Negative electrode OCP [V]' not found. Use the dimensional version 'Primary: Negative electrode OCP [V]' instead."
```

**Comment by rtimms** [comment]
Thanks for bringing this up. This is a known issue, see https://github.com/pybamm-team/PyBaMM/issues/2682
