### ISSUE TITLE
[Bug]: Unable to obtain the right results of "{Domain} electrode thickness change [m]". 

### ISSUE THREAD

**Issue by bobonice** [pybamm-team/PyBaMM#3323]
### PyBaMM Version

v23.5

### Python Version

3.11

## Unable to obtain the right results of "{Domain} electrode thickness change [m]". 
For example, in the tutorial ["Validating_mechanical_models_Enertech_DFN.ipynb”](https://github.com/pybamm-team/PyBaMM/blob/develop/docs/source/examples/notebooks/models/Validating_mechanical_models_Enertech_DFN.ipynb) , the simulation and experimental results of 'thickness change [m]' in Figure 1 do not match at all. 

![image](https://github.com/pybamm-team/PyBaMM/assets/22030806/e566af1d-da97-4703-9313-116661b480f8)

It could be caused by the absence of dimension for the variable "**electrode_thickness_change**" in the [class BaseMechanics (base_mechanics.py)](https://github.com/pybamm-team/PyBaMM/blob/develop/pybamm/models/submodels/particle_mechanics/base_mechanics.py). In reference to the previous version, the bug could be fixed using the following code:

- change the code on line 58 to:
`L0 = domain_param.L`
`electrode_thickness_change = self.param.n_electrodes_parallel * v_change * L0`
**or**
- change the lines 96-97 to:
`neg_thickness_change = variables["Negative electrode thickness change [m]"] * self.param.n.L`
`pos_thickness_change = variables["Positive electrode thickness change [m]"] * self.param.p.L`

After applying the above change, the new Figure 1 in the tutorial "Validating_mechanical_models_Enertech_DFN.ipynb” would be like this:
![image](https://github.com/pybamm-team/PyBaMM/assets/22030806/eaa76afb-6e96-4d7a-9f49-f206d2c546f1)

### Steps to Reproduce

Perform the simulations which include the absolute thickness changes or run the code directly in the tutorial "Validating_mechanical_models_Enertech_DFN.ipynb”.

**Comment by rtimms** [comment]
Good catch, thanks. I prefer the first solution. Could you open a PR with the fix?

**Comment by bobonice** [comment]
Thank you for your prompt response and feedback. I have opened the [PR#3329.](https://github.com/pybamm-team/PyBaMM/pull/3329)

**Comment by brosaplanella** [comment]
This was fixed in #3329, so closing this issue
