### ISSUE TITLE
[Bug]: Using OKane2022 parameter set works with the K both upper and lower case

### ISSUE THREAD

**Issue by l-olisa** [pybamm-team/PyBaMM#3337]
### PyBaMM Version

23.5

### Python Version

3.11.5

### Describe the bug

When using params = pybamm.ParameterValues("OKane2022"), it works using both "Okane2022" and "OKane2022". For some group members the Okane2022 doesn't work (using same python and pybamm versions as above), and for others it does work (all using Windows).

### Steps to Reproduce

import pybamm

model_SEI = pybamm.lithium_ion.DFN(
     {"SEI": "solvent-diffusion limited",
     "SEI porosity change": "true", 
     })

params = pybamm.ParameterValues("OKane2022")

**Comment by l-olisa** [comment]
Double checked and the PyBaMM versions were different for the laptops that didn't work (23.4.11). When upgraded to 23.5, able to run both upper and lower cases of OKane2022.

**Comment by brosaplanella** [comment]
We followed this up and it was fixed in #3132 so closing this issue.
