### ISSUE TITLE
Add averaging to processed variable

### ISSUE THREAD

**Issue by Scottmar93** [pybamm-team/PyBaMM#334]
**Summary**
Add a function to average quantities within `ProcessedVariable`. Mesh is already stored in `ProcessedVariable` so this should be a simple addition and it gets rid of a whole bunch of "Average" outputs.  

 **Motivation**
It would be useful to have more averaged variables for testing but I don't want the output_variables list unnecessarily bloated.

**Comment by tinosulzer** [comment]
Issue with this is that the `Integrate` operator needs to be discretised

**Comment by tinosulzer** [comment]
I think the workflow for this should be that the variable to be averaged should be added to the list of variables before the model is built and solved. This can be done in a script, for example:
```python3
model = pybamm.lithium_ion.DFN()
variable = model.variables["example variable"]
model.variables["X-averaged example variable"] = pybamm.x_average(variable)
...
```
Closing but feel free to reopen if different functionality is needed
