### ISSUE TITLE
Explicit Dirichlet and Newman boundary conditions

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#335]
I've had a change of heart and now think we should explicitly state boundary conditions on `Variable` objects (or concatenations of variables). @jamiemfoster  and @ikorotkin  what do you guys think of this, would it help for control volumes?
e.g.
```
model.Dirichlet_bcs = {c: {"left": 0}}
model.Newman_bcs = {c: {"right": 0}}
```
to replace
```
N = pybamm.grad(c)
model.boundary_conditions = {c: {"left": 0}, N: {"right": 0}}
```

**Pros**
- Easier to implement spatial methods: e.g. for finite volumes, we always add a ghost node when discretising the gradient, either to satisfy dirichlet or newman bcs. 
- More in line with UFL (for Fenics/Firedrake)
- Flux-like variables (e.g. current density) always have the same shape (not different shapes depending on the boundary conditions, as is currently the case)

**Cons**
- Slightly more verbose 
- A bit less obvious what the boundary condition should be in some cases (but in most cases, it's no-flux so fine)

**Comment by jamiemfoster** [comment]
I'm totally down with this change. In my eyes the suggested things makes
things a more intuitive, which I am all for.

Cheers,
Jamie.

-------------------------------------------------
Jamie M. Foster,
School of Mathematics and Physics,
University of Portsmouth,
Portsmouth, Hampshire, UK (PO1 2UP).
Phone: +44 02392 846 356 (internal: 6356)
Email: jamie.michael.foster@gmail.com
URL: http://ms.mcmaster.ca/~jmfoster/
-------------------------------------------------
