### ISSUE TITLE
Fix the URL checker

### ISSUE THREAD

**Issue by Saransh-cpp** [pybamm-team/PyBaMM#3386]
lychee is failing here at the moment -

https://github.com/pybamm-team/PyBaMM/blob/7eb5879c264e26b02a71b0ced8ef11a5f092e451/CONTRIBUTING.md?plain=1#L188

We could use a different material to reference glob pattern?

**Comment by Agnik7** [comment]
Hi @Saransh-cpp I am participating in Hacktoberfest and would love to work on this issue!! Kindly assign this to me.

**Comment by Saransh-cpp** [comment]
Hi, go ahead!

**Comment by Agnik7** [comment]
@Saransh-cpp I have one query. I need to work and then send the PR to the `develop` branch right?

**Comment by Saransh-cpp** [comment]
Yes. You can also refer to the [Contributing Guide](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md) for detailed steps.

**Comment by Agnik7** [comment]
Ok thanks

**Comment by Agnik7** [comment]
@Saransh-cpp I have created a PR #3393 . Requesting for your review. Thanks!!
