### ISSUE TITLE
Add a link checker step in the doctests jobs and fix broken links that appear

### ISSUE THREAD

**Issue by agriyakhetarpal** [pybamm-team/PyBaMM#3387]
Currently, we use Lychee to check for broken links, but we ignore a lot of Sphinx-related links because of referencing files internally. `Sphinx` provides a [`linkcheck`](https://www.sphinx-doc.org/en/master/usage/builders/index.html#sphinx.builders.linkcheck.CheckExternalLinksBuilder) builder for this purpose that can be invoked in CI for checking links (either through a new `nox` session, or within the `docs` session using posargs, or just calling the command directly).

It might make sense to rename the Lychee workflow to something like `links.yml` and add a parallel job to run the above command instead of another step.

**Comment by RohitP2005** [comment]
hey @Saransh-cpp is the issue still open ?

**Comment by agriyakhetarpal** [comment]
Hi @RohitP2005, this is still open, thanks for your interest!

**Comment by RohitP2005** [comment]
Thanks, @agriyakhetarpal i will start my work
