### ISSUE TITLE
Doctests do not remove built files if they fail

### ISSUE THREAD

**Issue by agriyakhetarpal** [pybamm-team/PyBaMM#3389]
In `run-tests.py`, if the doctests fail locally for some reason, they do not delete the built files and cause problems upon invoking the doctests again. This is because `nbsphinx` duplicates some of the doctrees upon rebuilds (it is not meant to work with the doctests). The command should be fixed in order to delete the built files upon invoking the doctests, or just the .doctrees folder inside them so that the error logs can be retained.

**Comment by Agnik7** [comment]
Hi I would like to work on this issue. I am new to open-source, so I bit of guidance will be helpful.  Kindly assign it to me

**Comment by agriyakhetarpal** [comment]
Hi @Agnik7, thanks for the help! For more explanation, we have a method in `run-tests.py` defined like this, which runs these tests through the command line (`python run-tests.py --doctest` or `nox -s doctests`)

https://github.com/pybamm-team/PyBaMM/blob/develop/run-tests.py#L61-L97

The issue is with the `subprocess.Popen` instance, because the process remains open until the terminal window is closed even if the doctests. Therefore, the built files (inside the `docs/build/` folder) are not deleted. We should alter it to use `subprocess.check_call` or `subprocess.run` with `check=True`, as appropriate, such that it fails on receiving a non-zero exit code (the doctests are supposed to treat warnings as errors) and closes the process. Try commenting out this line `shutil.rmtree("docs/build")` and run the doctests again to debug this issue. The ideal functionality is that we should remove the `.doctrees/` folder inside `docs/build/` regardless of whether the doctests fail or pass so that the doctrees can be re-built.

It would be helpful to set up the project locally using the source installation instructions based on your platform or inside a Docker container (see https://docs.pybamm.org/en/latest/source/user_guide/installation), and then you may try building the documentation and running the doctests by reading through the contributor guide. @Saransh-cpp, could you please assign them this?

**Comment by shubhambhar007** [comment]
Hi @agriyakhetarpal @Saransh-cpp if no one is working on this could you please assign it to me ?Thanks :D

**Comment by agriyakhetarpal** [comment]
Hi @shubhambhar007, how is this issue coming along?

**Comment by shubhambhar007** [comment]
Hi @agriyakhetarpal ,apologies for the delay , was on call this month :(

Will raise the PR by tonight for review, max by tomorrow morning.

Thanks !!

**Comment by agriyakhetarpal** [comment]
No worries, thanks for the update!
