### ISSUE TITLE
Jax solver mode: only include output variables

### ISSUE THREAD

**Issue by BradyPlanden** [pybamm-team/PyBaMM#3395]
### Description

This continues #2796 for the JaxSolver. 

### Motivation

For parameter estimation, it is (computationally) benefitical to store only the required output variables. 

This issue also aims to provide functionality for jit-compiled parameter estimation or optimisation workflows. At the moment this isn't possible since the creation of the `ProcessedVariable` dict is completed with Casadi. Further discussion here: https://github.com/pybop-team/PyBOP/pull/25

**Comment by agriyakhetarpal** [comment]
Hi, @BradyPlanden – you had mentioned that #3658 should have closed this issue, but I think we forgot to do so. Should we close this now?

**Comment by BradyPlanden** [comment]
Yep, marking closed.
