### ISSUE TITLE
Add better error about the new "exchange-current density for lithium metal electrode [A.m-2]" parameter

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#3428]
It used to be "Exchange-current density for plating [A.m-2]", now renamed to "Exchange-current density for lithium metal electrode [A.m-2]". I understand why the change was made, but we should catch this in the `ParameterValues` class and throw an informative error

**Comment by tinosulzer** [comment]
This should be done before the final release 23.9

**Comment by agriyakhetarpal** [comment]
Happy to take this
