### ISSUE TITLE
Move all the extra configurations to `pyproject.toml`

### ISSUE THREAD

**Issue by Saransh-cpp** [pybamm-team/PyBaMM#3478]
Once #3301 is merged, we can move the configurations of pytest, ruff, and others to `pyproject.toml`

**Comment by agriyakhetarpal** [comment]
I was going to open this issue, you beat me to it! 😄

**Comment by agriyakhetarpal** [comment]
Some more tools whose configuration can be moved: `cibuildwheel`, `coverage.py`, and possibly `lychee`
