### ISSUE TITLE
[Bug]: Suface form effective conductivity in separator

### ISSUE THREAD

**Issue by Scottmar93** [pybamm-team/PyBaMM#3495]
### PyBaMM Version

23.5

### Python Version

23.5

### Describe the bug

On lines 81 and 85, of pybamm/models/submodels/electrolyte_conductivity/surface_potential_form/full_surface_form_conductivity.py
is seems that the separator porosity is used in the calculation of the effective conductivity in the separator instead of the separator transport efficiency. In the end, I think this is only an order of a few mV errors in the predicted voltage.

![image](https://github.com/pybamm-team/PyBaMM/assets/22661308/9580db52-1acf-44e2-8fa6-1d174ec13c9e)

### Steps to Reproduce

N/A

**Comment by rtimms** [comment]
@TomTranter any update on this?

**Comment by TomTranter** [comment]
Completely forgot about it
