### ISSUE TITLE
Theoretical energy integral is very slow

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#3506]
This for loop is killing us and should be vectorized: https://github.com/pybamm-team/PyBaMM/blob/33d21874fbc39fd81ff89a8cc5638f6a81f8c31d/pybamm/models/full_battery_models/lithium_ion/electrode_soh.py#L1007-L1011

**Comment by tinosulzer** [comment]
<img width="1013" alt="Screenshot 2023-11-08 at 6 48 21 PM" src="https://github.com/pybamm-team/PyBaMM/assets/20817509/1ccac7f3-b651-49b2-9bb1-4df8d7d80437">

**Comment by AbhishekChaudharii** [comment]
I tried vectorizing it but it seems that performing binary operations between NumPy arrays and `<class 'pybamm.parameters.parameter_values.ParameterValues'>`  might not be supported. 

Error :  `NotImplementedError: BinaryOperator not implemented for symbols of type <class 'numpy.ndarray'> and <class 'pybamm.expression_tree.scalar.Scalar'>`

**Comment by tinosulzer** [comment]
Ok I'll look into this
