### ISSUE TITLE
[Bug]: Default SPMe and DFN models/examples have no NE potential or overpotential 

### ISSUE THREAD

**Issue by tommaull** [pybamm-team/PyBaMM#3566]
### PyBaMM Version

lastest Dev and Main as of 27/11/23

### Python Version

3.9

### Describe the bug

![image](https://github.com/pybamm-team/PyBaMM/assets/101814207/700e2e26-5b93-4f84-94b8-ccd9000fd08c)

NE response is implausible - hovering around 0 potential, with no overpotential behaviours. 

### Steps to Reproduce

Run 23.9 Main, SPMe example. Observe NE behaviour.

**Comment by rtimms** [comment]
This is because we measure potential wrt the solid phase negative electrode potential at x=0, whereas I'm guessing what you're expecting is the potential measured wrt to a different reference, such as the electrolyte potential?

**Comment by rtimms** [comment]
See also https://github.com/pybamm-team/PyBaMM/discussions/3470 and https://github.com/pybamm-team/PyBaMM/discussions/3254
