### ISSUE TITLE
Style checker on PRs does not actually check anything

### ISSUE THREAD

**Issue by agriyakhetarpal** [pybamm-team/PyBaMM#3571]
### PyBaMM Version

develop

### Python Version

N/A

### Describe the bug

The style job in the `test_on_push.yml` workflow does not notice any files to lint/auto-format and therefore is passing silently.

### Steps to Reproduce

It can be noticed in the checks on any of the PRs, for example:

https://github.com/pybamm-team/PyBaMM/actions/runs/7009110613/job/19066860618?pr=3569#step:4:65

**Comment by kratman** [comment]
I think the command
```
pre-commit run ruff
```
skips.

The easiest fix would be to just do 
```
pre-commit run ruff --all
```

Though that only runs ruff, so maybe
```
pre-commit run --all
```
is better.

**Comment by kratman** [comment]
There are ways to get pre-commit to run on only changed files as well, but using ```--all``` is the easiest route

**Comment by agriyakhetarpal** [comment]
I would suggest running it on just the changed files in a PR. The style check is needed to pass for other checks to start, so it would be a nuisance if it fails due to issues in unchanged files.

**Comment by shubhambhar007** [comment]
@kratman @agriyakhetarpal I was exploring on this and came across this command for only the changed files in the PR.

`pre-commit run --files $(git diff --name-only HEAD^)
`

If it looks fine , can i please work on this issue ? 
Thanks :D

**Comment by kratman** [comment]
@shubhambhar007 Yep feel free to work on the issue.

**Comment by kratman** [comment]
I think we don't need the extra nox function. We just add the ```--all``` in the workflow. Nice and easy

**Comment by shubhambhar007** [comment]
@agriyakhetarpal any idea as to why this might not be working? 
We were initially trying with --all but then moved to this to make it run only for the diffs , it was working on my local and I also saw a few other PRs.

While --all may be slow but i think it is best to have it running slowly rather than nor running at all at times.

**Comment by kratman** [comment]
@shubhambhar007 the add probably only looks for locally changed files that were not committed while PRs have all changes committed. I think when I have seen this done on other projects they used a diff to a commit hash.

Running with --all is still orders of magnitude faster than the rest of our checks. All changes to style settings are supposed to have isolated commits to hide them from git blame, so I don't think there are really any downsides to using --all

**Comment by agriyakhetarpal** [comment]
> I think when I have seen this done on other projects they used a diff to a commit hash.

I guess it would be great to migrate to the pre-commit GitHub Action for this in the long term to get results that bear similarity with the pre-commit bot

**Comment by shubhambhar007** [comment]
@agriyakhetarpal got it, thanks :D 
Yes , i agree, safe side is using --all .
