### ISSUE TITLE
[Bug]: error

### ISSUE THREAD

**Issue by Jadhav-Sourabh** [pybamm-team/PyBaMM#3575]
### PyBaMM Version

23.9

### Python Version

3.11

### Describe the bug

Getting error while using 
1. Thermal model - x lumped
2. Dimensionality - 2
3. Current collector - potential pair
4. Parameters set - prada2013
5. Error saying - ` type error: initial conditions cannot contain 'variable' objects, but variable (-0x54de....., current variable [A], children=[], domains={}), found in initial conditions for 'current collector current density [A.m-2]' `

### Steps to Reproduce

Getting error while using 
1. Thermal model - x lumped
2. Dimensionality - 2
3. Current collector - potential pair
4. Parameters set - Prada 2013
5. Error saying - ` type error: initial conditions cannot contain 'variable' objects, but variable (-0x54de....., current variable [A], children=[], domains={}), found in initial conditions for 'current collector current density [A.m-2]' `

**Comment by kratman** [comment]
@Jadhav-Sourabh Is this issue still relevant? There is a new PyBaMM release as well
