### ISSUE TITLE
Visualising the mesh grid and importing its collocation points

### ISSUE THREAD

**Issue by aykharal** [pybamm-team/PyBaMM#3581]
### Description

Hi,

I am trying to develop a ML model to predict the lithium concentration in the electrodes. For that I need to visualize the mesh (in 2D) and want to extract the data of the mesh as well. I have ran simulations using PDE model and extracted the concentration data. However I need the data of collocation points, 'r' and 't' of the mesh along with the concentration data. Any help from the experts in this regard is highly appreciated?

### Motivation

Development of an ML model that predicts the lithium concentration and SOC in the electrodes. Also to see how the lithium concentration varies with the drive cycle.

**Comment by tinosulzer** [comment]
After building the simulation
```python3
import pybamm

model = pybamm.lithium_ion.DFN()
sim = pybamm.Simulation(model)
sim.build()
```
you can output `sim.mesh` e.g. `sim.mesh["positive particle"].nodes` gives you the center of the nodes for the positive particle
