### ISSUE TITLE
Skip PyBaMM-specific workflows and jobs on forks

### ISSUE THREAD

**Issue by agriyakhetarpal** [pybamm-team/PyBaMM#3592]
At this date, we currently skip certain workflows such as those to build and push Docker images and pushing to PyPI. The other workflows such as the reply bot, updating the license year, and benchmarks-related workflows or their jobs can be appropriately marked with the YAML syntax

```yaml
    if: github.repository_owner == 'pybamm-team'
```

or the alternate and better one

```yaml
    if: github.repository == 'pybamm-team/PyBaMM'
```

to run them just on the main repository. Issues and workflows are disabled on forks by default, but we should add the above checks since it would help developers whose forks are being used to actively contribute to the repository and therefore have workflows enabled.

Here's a list, by no means exhaustive:

1. `release_reminder.yml`: does not run much since it's on schedule, but uses write permissions, should be skipped for security reasons
2. `publish_pypi.yml`: the publishing job should be skipped on forks (tracked by #3569)
3. `run_benchmarks_over_history.yml`: the `publish-results` job will fail on forks due to the absence of a repo-scoped PAT
~~4. `update_license.yml`: relevant only for the PyBaMM repository~~ (already skipped)
5. `validation_benchmarks.yml`: runs on releases, requires secrets to be configured, the entire workflow should be skipped
6. `work_precision_sets.yml`: runs on releases, the entire workflow should be skipped
7. In `run_periodic_tests.yml`, i.e., the scheduled tests: we should skip the job written for the M-series runner

**Comment by jlauber18** [comment]
Hello, can I work on this?
