### ISSUE TITLE
More informative error extrapolation drive cycle

### ISSUE THREAD

**Issue by brosaplanella** [pybamm-team/PyBaMM#3612]
At the moment, if a drive cycle starts at `t=1` rather than `t=0` it throws a rather uninformative error (see below)

![fe445cd2-3667-45a0-8a78-0807173bf6c3](https://github.com/pybamm-team/PyBaMM/assets/28443643/855646bc-f297-45e3-b9c5-3b54da27a1b7)

The easiest way to address this would be:
- Give the interpolant a meaningful name at creation so at least it is clear which interpolant is causing the error https://github.com/pybamm-team/PyBaMM/blob/e0bec2b7c5468e1b448d04bedf42aa8a66d67516/pybamm/experiment/step/_steps_util.py#L123-L125
- (Optionally) Perform a check and if drive cycle starts at `t>0` throw a different, more specific error (or assume it's zero until first provided value, but I personally think this is dangerous).
- Add somewhere in the docs that drive cycles must start at `t=0`, added to #3392 already.

**Comment by jeromtom** [comment]
Would `Drive cycle start time` be an apt name?

**Comment by brosaplanella** [comment]
> Would `Drive cycle start time` be an apt name?

For the drive cycle name? I would call it something like "Current drive cycle" (or power/voltage whatever drives it).

**Comment by R-Yash** [comment]
@brosaplanella I want to work on this issue. Is it still open?

**Comment by brosaplanella** [comment]
@jeromtom are you working on it? Otherwise @R-Yash can take it

**Comment by jeromtom** [comment]
@brosaplanella, I had worked on this but could not commit the changes due to a fault in my environment setup.
@R-Yash, you can refer to the following to fix it.
![image](https://github.com/pybamm-team/PyBaMM/assets/83979298/ac17145b-46f7-4010-983c-26c2d340624b)
![image](https://github.com/pybamm-team/PyBaMM/assets/83979298/324cd69c-7fbb-466a-9555-5294ed66776b)

**Comment by R-Yash** [comment]
Thanks @jeromtom
