### ISSUE TITLE
[Bug]: SEI ('electron-migration limited') model

### ISSUE THREAD

**Issue by kawaMANMI** [pybamm-team/PyBaMM#3613]
### PyBaMM Version

23.9

### Python Version

3.10

### Describe the bug

I noticed that the SEI thickness decreases when the 'electron-migration limited' model (option) is used, which is unrealistic.

### Steps to Reproduce

```python3
import pybamm
import numpy as np
import matplotlib.pyplot as plt
exp_CCCV = pybamm.Experiment(
    [("Charge at C/10 until 4.2 V",
      "Rest for 10 hours",
      "Discharge at C/10 until 2.5 V",
      "Rest for 10 hours",
      )]
)
model = pybamm.lithium_ion.SPM(options={
    "SEI": "electron-migration limited",
    "SEI porosity change": "true",
},
    name="SPM-SEI")

solver = pybamm.CasadiSolver()
sim = pybamm.Simulation(model, experiment=exp_CCCV, solver=solver)
sol = sim.solve(initial_soc=0)
plt.plot(sol["Time [h]"].entries,
         sol['X-averaged negative total SEI thickness [m]'].entries, label='SEI thickness')
```

**Comment by kawaMANMI** [comment]
Just to provide more clarity, I have attached three figures here for the electro-migration limited model before correction, after correction, and the interstitial-diffusion limited model.  The corrected version follows a similar trend to the interstitial model. 
![interstitial-diffusion limited](https://github.com/pybamm-team/PyBaMM/assets/39382602/51967cb9-acc7-4338-9da2-5ec96bd372e4)
![electron_migration_Pybamm_Corrected](https://github.com/pybamm-team/PyBaMM/assets/39382602/f6fc9491-6e3b-4b28-ab8a-f6470a7c4a30)
![electron_migration_Pybamm](https://github.com/pybamm-team/PyBaMM/assets/39382602/4fc2202d-59cd-4a96-8749-50de7211ba34)

**Comment by brosaplanella** [comment]
For clarity, the current model is the bottom plot and Kawa's fix is the middle one.
