### ISSUE TITLE
Better error or handling when passing a str to Experiment

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/PyBaMM#3623]
`Experiment` expects `operating_conditions` to be a list of strings. If you just pass a string, e.g. `pybamm.Experiment("Discharge at 1C until 2.5V")` you get the error `ValueError: Operating conditions must contain keyword 'for' or 'until'.`. 

We should add a check to see if `operating_conditions` is list of strings or a str. If it's a str we should convert to a list, if not we should raise an error (see e.g. `check_input_validity` for `QuickPlot` [here](https://github.com/pybamm-team/PyBaMM/blob/903323efca7fef8f630924d114ce70dcf8a92363/pybamm/plotting/quick_plot.py#L250)).

**Comment by kratman** [comment]
Do we need to support both strings and lists? I see no reason why we can't require the user to always send a list(str), and just add a type hint.

**Comment by rtimms** [comment]
Yeah, happy with that. There are lots of places in PyBaMM where we aren't checking types. There is work to address this in some places, e.g. https://github.com/pybamm-team/PyBaMM/issues/3497

**Comment by prady0t** [comment]
Can I take this up?

**Comment by agriyakhetarpal** [comment]
Hi @prady0t, I see that you're assigned to #3524, how is that coming along?

**Comment by prady0t** [comment]
Ah yes I'm working on it. I need a bit of assistance though (I wrote a comment about it).

**Comment by prady0t** [comment]
I can work on two issues at once no big deal. 😸

**Comment by kratman** [comment]
We try to only assign new developers to 1 issue at a time. If you do end up working on this issue though, you should try the type hint approach. It would make it only a couple lines.

**Comment by prady0t** [comment]
Okay that's totally fine 👍🏼
