### ISSUE TITLE
[Bug]: example notebooks are failing

### ISSUE THREAD

**Issue by agriyakhetarpal** [pybamm-team/PyBaMM#3660]
### PyBaMM Version

`develop`

### Python Version

3.11

### Describe the bug

Due to an internal `nbmake` error – I think this was introduced by the changes #3492 since it failed twice there but was passing earlier. I don't think code formatting changes can cause such an error but I may be mistaken.

### Steps to Reproduce

Run example tests on recent PRs

### Relevant log output

https://github.com/pybamm-team/PyBaMM/actions/runs/7314706618/job/19929773727

**Comment by agriyakhetarpal** [comment]
I tested locally and they fail there as well, @Saransh-cpp @arjxn-py could you check too?

**Comment by Saransh-cpp** [comment]
I can reproduce this locally, but I get the exact same logs if I revert the `ruff format` commits. The logs are very hard to debug as almost all of them are originating from `nbmake` and not `pybamm`.

I think this is an `nbmake` issue, might get fixed after the holidays.

**Comment by agriyakhetarpal** [comment]
This is strange, they pass for me locally if I revert the ruff-format changes

**Comment by Saransh-cpp** [comment]
That's weird. I cleaned up my nox environments and did a fresh run, still failed with the same error. Maybe @arjxn-py can help with reproducing this.

**Comment by arjxn-py** [comment]
Yes, trying to reproduce it locally while `ruff` commits reverted right now. Getting back in sometime.

**Comment by agriyakhetarpal** [comment]
I think the problem is not with any individual notebook since running any of the failing notebooks separately does not cause an issue. The notebooks that are failing are different every time and I am able to reproduce it both before and after the `ruff format` changes now. 

The error trace is a bit difficult to debug, but it doesn't look like an error but rather a warning about garbage collection – maybe disabling these warnings through `pytest` can help
