### ISSUE TITLE
[Bug]: Error when calculate sensitivities about "Positive electrode diffusivity"

### ISSUE THREAD

**Issue by Mrzhang-hub** [pybamm-team/PyBaMM#3667]
### PyBaMM Version

23.9

### Python Version

3.9

### Describe the bug

At t = 0.0189966, mxstep steps taken before reaching tout.
At t = 0.0189966, mxstep steps taken before reaching tout.
At t = 0.0189966, mxstep steps taken before reaching tout.
At t = 0.0189966, mxstep steps taken before reaching tout.
At t = 0.0189966, mxstep steps taken before reaching tout.
At t = 0.0189966, mxstep steps taken before reaching tout.
Traceback (most recent call last):
  File "E:\Anaconda3\envs\DDPG-EMS\lib\site-packages\pybamm\solvers\casadi_solver.py", line 681, in _run_integrator
    casadi_sol = integrator(
  File "E:\Anaconda3\envs\DDPG-EMS\lib\site-packages\casadi\casadi.py", line 23390, in __call__
    return self.call(kwargs)
  File "E:\Anaconda3\envs\DDPG-EMS\lib\site-packages\casadi\casadi.py", line 20039, in call
    return _casadi.Function_call(self, *args)
RuntimeError: Error in Function::call for 'F' [CvodesInterface] at .../casadi/core/function.cpp:1401:
Error in Function::call for 'F' [CvodesInterface] at .../casadi/core/function.cpp:330:
.../casadi/interfaces/sundials/cvodes_interface.cpp:392: CVode returned "CV_TOO_MUCH_WORK". Consult CVODES documentation.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda3\envs\DDPG-EMS\lib\site-packages\pybamm\solvers\casadi_solver.py", line 250, in _integrate
    current_step_sol = self._run_integrator(
  File "E:\Anaconda3\envs\DDPG-EMS\lib\site-packages\pybamm\solvers\casadi_solver.py", line 687, in _run_integrator
    raise pybamm.SolverError(error.args[0])
pybamm.expression_tree.exceptions.SolverError: Error in Function::call for 'F' [CvodesInterface] at .../casadi/core/function.cpp:1401:
Error in Function::call for 'F' [CvodesInterface] at .../casadi/core/function.cpp:330:
.../casadi/interfaces/sundials/cvodes_interface.cpp:392: CVode returned "CV_TOO_MUCH_WORK". Consult CVODES documentation.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda3\envs\DDPG-EMS\lib\site-packages\pybamm\solvers\casadi_solver.py", line 285, in _integrate
    raise pybamm.SolverError(
pybamm.expression_tree.exceptions.SolverError: Maximum number of decreased steps occurred at t=0.0 (final SolverError: 'Error in Function::call for 'F' [CvodesInterface] at .../casadi/core/function.cpp:1401:
Error in Function::call for 'F' [CvodesInterface] at .../casadi/core/function.cpp:330:
.../casadi/interfaces/sundials/cvodes_interface.cpp:392: CVode returned "CV_TOO_MUCH_WORK". Consult CVODES documentation.'). For a full solution try reducing dt_max (currently, dt_max=600) and/or reducing the size of the time steps or period of the experiment. Set `return_solution_if_failed_early=True` to return the solution object up to the point where failure occured.

### Steps to Reproduce

import pybamm
import pandas as pd
import os
os.chdir(pybamm.__path__[0] + "/..")
model = pybamm.lithium_ion.SPMe()
param = pybamm.ParameterValues('Prada2013')
param.update({"Positive electrode diffusivity [m2.s-1]":'[input]'})
drive_cycle = pd.read_csv(
    "pybamm/input/drive_cycles/US06.csv", comment="#", header=None
).to_numpy()
t = drive_cycle[:, 0]
current_interpolant = pybamm.Interpolant(drive_cycle[:, 0], drive_cycle[:, 1], pybamm.t)
param['Current function [A]'] = current_interpolant
sim = pybamm.Simulation(model=model, parameter_values=param, solver=pybamm.CasadiSolver())
sol = sim.solve(t, inputs={"Positive electrode diffusivity [m2.s-1]": 5.9e-18}, calculate_sensitivities=True)
J = sol['Voltage [V]'].sensitivities["Positive electrode diffusivity [m2.s-1]"]

**Comment by kratman** [comment]
@Mrzhang-hub I tried to reproduce this without the changes to `"Positive electrode diffusivity [m2.s-1]"` and it ran without error.

Does this error only occur for you when you change parameters?
