### ISSUE TITLE
[Bug]: There is an error in the 'Getting Started' section when we click the link in the example notebooks

### ISSUE THREAD

**Issue by Abhishekjsr283204** [pybamm-team/PyBaMM#3668]
### PyBaMM Version

PyBaMM version

### Python Version

python version

### Describe the bug

![Screenshot_40 - Copy](https://github.com/pybamm-team/PyBaMM/assets/108180708/d7f5220f-6b25-4d82-8f05-34c77cc7a18e)
In this  above section
![Screenshot_2](https://github.com/pybamm-team/PyBaMM/assets/108180708/2027a444-cc4a-4253-b786-ddf89078f5d6)
This error we got when we clicked this

### Steps to Reproduce

![Screenshot_40 - Copy](https://github.com/pybamm-team/PyBaMM/assets/108180708/d7f5220f-6b25-4d82-8f05-34c77cc7a18e)
In this  above section
![Screenshot_2](https://github.com/pybamm-team/PyBaMM/assets/108180708/2027a444-cc4a-4253-b786-ddf89078f5d6)
This error we got when we clicked this

**Comment by agriyakhetarpal** [comment]
Hi @Abhishekjsr283204, the example notebooks have been moved to the [`docs/source/examples/` folder](https://github.com/pybamm-team/PyBaMM/tree/develop/docs/source/examples/notebooks) and the [PyBaMM website](https://pybamm.org) will be used to host the contents of the PyBaMM Wiki going forward. In specific, the page you are looking at is https://pybamm.org/gsoc/2023/, which has an updated link to the requested source. I hope this helps!

**Comment by Abhishekjsr283204** [comment]
okay got it thank you for response
