### ISSUE TITLE
Check if the solution exists before creating a GIF (`Simulation.create_gif` and `BatchStudy.create_gif`)

### ISSUE THREAD

**Issue by Saransh-cpp** [pybamm-team/PyBaMM#3725]
I liked how #3723 checks if the simulations have been solved before proceeding ahead to the plotting functionality. It would be nice to have similar checks in -

https://github.com/pybamm-team/PyBaMM/blob/c3def31a04df163769851733657d9b49b3700bca/pybamm/batch_study.py#L184-L187

and 

https://github.com/pybamm-team/PyBaMM/blob/c3def31a04df163769851733657d9b49b3700bca/pybamm/simulation.py#L1047-L1050

**Comment by prady0t** [comment]
Would like to take this on.

**Comment by R-Yash** [comment]
Hi @prady0t are you still working on this issue?

**Comment by prady0t** [comment]
yes

**Comment by prady0t** [comment]
@Saransh-cpp BatchStudy class doesn't have an attribute `solution` unlike Simulation. How to check for empty solutions there?

**Comment by Saransh-cpp** [comment]
You can check if the `self.sims` list is empty and throw an error if it is -

https://github.com/pybamm-team/PyBaMM/blob/c3def31a04df163769851733657d9b49b3700bca/pybamm/batch_study.py#L116

The simulations are being initialised and solved in the `solve()` method, so this would be a good indication of if the user has called the `solve()` method before calling the `create_gif()` method.

**Comment by prady0t** [comment]
why is 
https://github.com/pybamm-team/PyBaMM/blob/063a3830afd5547f7a78e283ae81058465cbdd3e/pybamm/batch_study.py#L116
declared outside `__init__` should'nt it be inside it?
