### ISSUE TITLE
Failing doctests in the CI

### ISSUE THREAD

**Issue by Saransh-cpp** [pybamm-team/PyBaMM#3781]
The doctests are failing on scheduled runs - https://github.com/pybamm-team/PyBaMM/actions/runs/7690636028/job/20954744741

I think the generated warnings are being treated as an error. The warning was un-suppressed in https://github.com/pybamm-team/PyBaMM/pull/3780.

cc: @agriyakhetarpal

**Comment by agriyakhetarpal** [comment]
Will take a look further today and fix it

**Comment by agriyakhetarpal** [comment]
Will take a look later today and fix it
