### ISSUE TITLE
[Bug]: The link to google colab from the tutorials on docs.pybamm.org does not work.

### ISSUE THREAD

**Issue by jonchapman1** [pybamm-team/PyBaMM#3817]
### PyBaMM Version

v24.1

### Python Version

NA

### Describe the bug

The link to google colab from the tutorials on docs.pybamm.org does not work.

It gives the error:
malformed GitHub path: missing 'blob' before branch name: pybamm-team/PyBaMM/tree/v24.1/docs/source/examples/notebooks/getting_started/tutorial-1-how-to-run-a-model.ipynb

### Steps to Reproduce

From
https://docs.pybamm.org/en/stable/source/examples/notebooks/getting_started/tutorial-1-how-to-run-a-model.html#
clink on 
 Open this notebook in Google Colab

**Comment by arjxn-py** [comment]
Thanks for opening this @jonchapman1, all the Colab badges are currently directing to bad URLs, missing `blob` before branch name in `v24.1`, looking into the fix
