### ISSUE TITLE
GSOC 2022 Electrochemical Impedance Spectroscopy (EIS) Status? 

### ISSUE THREAD

**Issue by mmichal9** [pybamm-team/PyBaMM#3852]
### Description

Hello there!

First of all thanks for creating pybamm, just getting started here but so far it is amazing! 

I have been looking through the options to simulate charge / discharge cycles and perform some additional measurements such as EIS. I looked through the documentation but so far there does not seem to be much available out of the box for EIS in pybamm. However then I found this project idea: [GSOC2022 ](https://pybamm.org/gsoc/2022/#electrochemical-impedance-spectroscopy-eis-modelling). Is there any work going on to integrating EIS into pybamm? If not can anyone recommend where to start ? 

### Motivation

Expend the scope of battery simulation

**Comment by rtimms** [comment]
I had a summer student work on this. They made good progress, but the repo is now very out of date https://github.com/rish31415/pybamm-eis
