### ISSUE TITLE
Coupling of P2D model and 3D thermal model

### ISSUE THREAD

**Issue by Santiagopeacely** [pybamm-team/PyBaMM#3875]
### Description

Coupling the one-dimensional electrochemical model and the three-dimensional thermal model can provide more accurate and comprehensive battery modeling and simulation results. This coupling can help us better understand and predict the behavior of battery systems, and optimize their performance.

### Motivation

1. The impact of thermal effect on battery performance: The thermal effect of a battery is an important aspect of electrochemical reactions and energy conversion. By coupling electrochemical and thermal models, we can consider the effects of thermal conduction, thermal diffusion, and heat sources (such as the exothermic effects of electrochemical reactions) on battery temperature. 
2. This helps to understand the importance of thermal management for battery performance, lifespan, and safety Temperature dependence of electrochemical reaction rate: The electrochemical reaction rate is usually affected by temperature. By coupling the electrochemical and thermal models, the influence of temperature on the electrochemical reaction rate can be considered, thus more accurately describing the electrochemical processes in the battery system
3. The influence of temperature distribution on electrochemical reactions: The temperature distribution inside the battery can affect the electrochemical reaction rate and ion transfer rate of the battery. By coupling electrochemical and thermal models, the influence of temperature distribution on electrochemical reactions can be considered to predict the performance and behavior of batteries
4. Optimizing battery design and operation strategies: By coupling one-dimensional electrochemical and three-dimensional thermal models, we can better optimize battery design and operation strategies. By considering thermal effects in the model, it is possible to more accurately predict the temperature distribution and heat generation of the battery, thereby guiding the optimization of heat dissipation design, improving energy conversion efficiency, and ensuring that the battery operates within a safe range.

### Possible Implementation

The current P2D model can accurately describe the electrochemical behavior of lithium-ion batteries, but due to the uneven heat generation of commercial soft pack batteries, the heat generation at the pole ear is significantly higher than others. Therefore, modifying the thermal model may more accurately describe the electrochemical behavior of the entire battery and better execute other submodules.

### Additional context

A specific reference was found as follows:
Gerver, R. E., & Meyers, J. P. (2011). Three-dimensional modeling of electrochemical performance and heat generation of lithium-ion batteries in tabbed planar configurations. Journal of The Electrochemical Society, 158(7), A835.

**Comment by kratman** [comment]
@Santiagopeacely Do you need anything else or can this ticket be closed?
