### ISSUE TITLE
Changes in battery stress caused by temperature

### ISSUE THREAD

**Issue by Santiagopeacely** [pybamm-team/PyBaMM#3880]
I want to do an electrochemical-thermal-mechanical stress model, currently in the case did not find the relevant content, I would like to seek help.
Thank you very much.

**Comment by tinosulzer** [comment]
If you set the options `{"thermal": "lumped", "loss of active material": "stress-driven"}` you will get both thermal and mechanical effects. They are coupled implicitly, not explicitly

**Comment by Santiagopeacely** [comment]
Thank you for your answer.&nbsp;Wishing you happiness every day
&nbsp;


L&nbsp;Y?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Eric G. ***@***.***&gt;; 
发送时间: 2024年3月20日(星期三) 凌晨0:54
收件人: ***@***.***&gt;; 
抄送: "L ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pybamm-team/PyBaMM] Changes in battery stress caused by temperature (Issue #3880)





 
If you set the options {"thermal": "lumped", "loss of active material": "stress-driven"} you will get both thermal and mechanical effects. They are coupled implicitly, not explicitly
