### ISSUE TITLE
How to obtain the radial stress distribution of particles in the swelling model

### ISSUE THREAD

**Issue by Santiagopeacely** [pybamm-team/PyBaMM#3881]
![image](https://github.com/pybamm-team/PyBaMM/assets/161728761/5aea859b-3069-4745-8203-46f031c06f05)
Hello,Sir
  I can only see the stress distribution along the particle surface in the variables of this model. I can not find one variable of the stress distribution inside the particle. Can this model obtain radial stress instead of surface radial stress?
  Looking forward to your answer, thank you very much!

**Comment by rtimms** [comment]
cc @weilongai

**Comment by weilongai** [comment]
I'm afraid there are no built-in variables for the radial stress inside particles in PyBaMM, but they can be easily calculated from lithium concentrations. See Eqs. (22-23) in [Journal of The Electrochemical Society, 154(10), A910-A916, 2007](https://iopscience.iop.org/article/10.1149/1.2759840)

**Comment by Santiagopeacely** [comment]
Thank you very much for your clarification. Wishing you success in your research and happiness every day！




L&nbsp;Y?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pybamm-team/PyBaMM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月11日(星期一) 晚上9:16
***@***.***&gt;;
抄送:&nbsp;"L ***@***.******@***.***&gt;;
主题:&nbsp;Re: [pybamm-team/PyBaMM] How to obtain the radial stress distribution of particles in the swelling model (Issue #3881)





 
I'm afraid there are no built-in variables for the radial stress inside particles in PyBaMM, but they can be easily calculated from lithium concentrations. See Eqs. (22-23) in Journal of The Electrochemical Society, 154(10), A910-A916, 2007

**Comment by kratman** [comment]
@Santiagopeacely It looks like you got an answer for this ticket, so I am going to close this for now. If there is anything more feel free to reopen the ticket.
