### ISSUE TITLE
[Bug]: Docker images: push to Docker Hub failed

### ISSUE THREAD

**Issue by agriyakhetarpal** [pybamm-team/PyBaMM#3889]
### PyBaMM Version

develop

### Python Version

N/A

### Describe the bug

The push to Docker Hub is failing due to a credentials issue, please see the following logs:

https://github.com/pybamm-team/PyBaMM/actions/runs/8253253728

### Steps to Reproduce

N/A

**Comment by agriyakhetarpal** [comment]
cc: @Saransh-cpp

(I suppose this is coming from the repository secrets)

**Comment by arjxn-py** [comment]
Thanks for opening this @agriyakhetarpal, I recently have converted PyBaMM's DockerHub account to an organisation which might have led to this failure.
I shall coordinate with @Saransh-cpp on slack regarding the same.

**Comment by Saransh-cpp** [comment]
Updated!
