### ISSUE TITLE
Update TestPyPi workflow

### ISSUE THREAD

**Issue by kratman** [pybamm-team/PyBaMM#3904]
Follow-up to #3358

The TestPyPi job still uses the token approach

**Comment by agriyakhetarpal** [comment]
This should be up-for-grabs if someone has the necessary five minutes, but I would say please feel free to take it yourself

**Comment by agriyakhetarpal** [comment]
This should be up-for-grabs if someone has the necessary five minutes, but please feel free to take it up yourself is what I would say

**Comment by kratman** [comment]
I will take this one @prady0t

**Comment by casualPhysics** [comment]
@kratman are you still on this? If not I can take it up?

**Comment by kratman** [comment]
@casualPhysics Yeah I am still going to do this task
