### ISSUE TITLE
[Bug]: Issue with Accessing Colab Notebooks from PyBaMM Tutorials Due to Malformed GitHub Path

### ISSUE THREAD

**Issue by lappemic** [pybamm-team/PyBaMM#3934]
### PyBaMM Version

24.1

### Python Version

3.11

### Describe the bug

Hello PyBaMM Team,

I've encountered an issue while trying to access the Colab notebooks provided in the PyBaMM documentation tutorials. Specifically, when attempting to open notebook links such as tutorial-1-how-to-run-a-model.ipynb from the "Getting Started" section through Google Colab, I receive the following error message:

```bash
Fehler beim Laden des Notebooks
Beim Laden dieses Notebooks ist ein Fehler aufgetreten. Achten Sie darauf, dass Sie Zugriff auf die Datei haben, und versuchen Sie es noch einmal. malformed GitHub path: missing 'blob' before branch name: pybamm-team/PyBaMM/tree/v24.1/docs/source/examples/notebooks/getting_started/tutorial-1-how-to-run-a-model.ipynb
````
It seems the error is due to a malformed GitHub path, specifically missing the 'blob' part in the URL structure required by Google Colab to properly render a notebook from a GitHub repository.

### Steps to Reproduce

1. Go to the PyBaMM documentation page for tutorials: e.g. [PyBaMM Tutorial 1](https://docs.pybamm.org/en/stable/source/examples/notebooks/getting_started/tutorial-1-how-to-run-a-model.html).
2. Click on any tutorial link intended to open in Google Colab.
3. The error message appears in Google Colab, preventing the notebook from loading.

**Possible Solution:**
Adjust the URL structure in the documentation links to include the 'blob' part before the branch name, ensuring compatibility with Google Colab's requirements for loading notebooks from GitHub.

For example, change the path from:
```
https://github.com/pybamm-team/PyBaMM/tree/v24.1/docs/source/examples/notebooks/getting_started/tutorial-1-how-to-run-a-model.ipynb
```

To:
```
https://github.com/pybamm-team/PyBaMM/blob/v24.1/docs/source/examples/notebooks/getting_started/tutorial-1-how-to-run-a-model.ipynb
```

Let me know if i can solve this issue for you.

Best regards,
Michael

**Comment by agriyakhetarpal** [comment]
Hi @lappemic, thank you for flagging this – this was actually reported very recently by someone else as well, and it has been fixed in the development branch already and will be available in the next release. We apologise for the inconvenience caused.
