### ISSUE TITLE
Unexpected voltage curve after modifying model parameters

### ISSUE THREAD

**Issue by mmichal9** [pybamm-team/PyBaMM#3957]
### PyBaMM Version

v24.1

### Python Version

3.12.1

### Describe the bug

I am looking into modifying the parameter set to experiment with different voltage limits.
As en example I have used the following: 

`model = pybamm.lithium_ion.DFN()
parameter_values = pybamm.ParameterValues("Mohtat2020")

min_v = 1.0
max_v = 5.0
parameter_values['Open-circuit voltage at 0% SOC [V]'] = min_v
parameter_values['Open-circuit voltage at 100% SOC [V]'] = max_v
parameter_values['Lower voltage cut-off [V]'] = min_v
parameter_values['Upper voltage cut-off [V]'] = max_v` 

When I run the experiment charging to maximum voltage I get unexpected voltage curve when exceeding default upper voltage cut-off value. Could you please advise where this might be coming from? Also could you please advise how can I modify the starting voltage? the simulation still starts at the default voltage level.

![image](https://github.com/pybamm-team/PyBaMM/assets/26767094/b0f8d2af-6dcc-44bf-a075-5b03cd40a218)

### Steps to Reproduce

run charging experiment until new max voltage

**Comment by kratman** [comment]
Hi @mmichal9, the voltage cutoffs are part of the parameterization of the model. To adjust that you would also need to change the open circuit potential and probably a few other parameters.

PyBaMM does not do much sanity checking when parameters are changed. It is sort of assumed that the cell models are fit and tested before they are used inside PyBaMM

**Comment by tinosulzer** [comment]
The easiest way to modify the starting voltage is to do e.g. `sim.solve(initial_soc="3.4V")`.

Regarding the behavior at the end of charge, it looks like you may be reaching the min or max stoichiometry of one of the electrodes, at which point the voltage goes to infinity. Can you plot "Negative electrode stoichiometry" and "Positive electrode stoichiometry" and "X-average negative electrode surface concentration" and "X-average positive electrode surface concentration"?

**Comment by mmichal9** [comment]
I have not found the bottom 2 parameters but the closest i seen was 'X-averaged negative particle surface concentration' and 'X-averaged positive particle surface concentration' please see the plots below:
![vc](https://github.com/pybamm-team/PyBaMM/assets/26767094/453bbb4c-781a-4369-8978-745f3c6c85c7)
![stoi](https://github.com/pybamm-team/PyBaMM/assets/26767094/2fa044e6-4a3b-4bff-8a36-782c33538622)

**Comment by kratman** [comment]
@mmichal9 Regarding the end of the curve, the open circuit potentials for Mohtat2020 look something like this:

![image](https://github.com/pybamm-team/PyBaMM/assets/10170302/965ecf3f-7afb-4c6c-b5e5-d4d252310ba6)

You can see that the upper and lower bounds of the voltage are limited by the potentials themselves. The black curve is the overall open circuit potential for the cell, and the voltage limits are set by the ends of that curve. When you try to go to voltages higher than the default maximum or lower than the default minimum, the OCP cannot reach those values.

You can use voltages between the default maximum and minimum, and using them is equivalent to changing the state of charge, but going outside the default range would require changing a lot more of the parameter set than just the voltage cutoffs.

**Comment by tinosulzer** [comment]
To add to Eric's comment, we force the OCV to go to plus or minus infinity close to 0 and 1:
https://github.com/pybamm-team/PyBaMM/blob/fe4ac31c6fa3aacc402433d1b8c97dceba5d583a/pybamm/parameters/lithium_ion_parameters.py#L623

This is to make sure that the stoichiometries can't leave the range (0,1) without the voltage cutoff getting triggered. If the stoichiometries were to leave that range, it would cause the solver to fail because of the `sqrt(c(1-c))` term in the exchange-current density.

**Comment by mmichal9** [comment]
Thank you for the support and the detailed explanation. I will look into the parameter sets in more detail son. For now will try to stick to the default.
