### ISSUE TITLE
[Bug]: pybamm.Simulation.set_parameters, pybamm.Simulation.set_up_and_parameterise_experiment and pybamm.Simulation.set_up_and_parameterise_model_for_experiment should be private (i.e. begin with underscore _) and not documented

### ISSUE THREAD

**Issue by hectormara** [pybamm-team/PyBaMM#3973]
### PyBaMM Version

23.9

### Python Version

3.11.7

### Describe the bug

It is a small issue for the training workshop on the 17th of April

### Steps to Reproduce

Read the scripts of Simulation

**Comment by agriyakhetarpal** [comment]
Hi, @hectormara – this issue is currently open in #3751 and there is a PR being worked on for it. Could you please pick a different item off the list and open a new issue (or better, edit the title and description for this one)?
