### ISSUE TITLE
[Bug]: Can't use "CustomStepExplicit" and "CustomStepImplicit" in v24.1

### ISSUE THREAD

**Issue by WoohyunJeong95** [pybamm-team/PyBaMM#3978]
### PyBaMM Version

24.1

### Python Version

3.11.5

### Describe the bug

Hi, I'm trying the code in https://docs.pybamm.org/en/latest/source/examples/notebooks/simulations_and_experiments/custom-experiments.html

I'd like to define custom step with "CustomStepExplicit" or "CustomStepImplicit", but it gives me this attribute error. 
![Uploading image.png…]()

I also tried the code with colab (https://colab.research.google.com/github/pybamm-team/PyBaMM/blob/develop/docs/source/examples/notebooks/simulations_and_experiments/custom-experiments.ipynb), but it does not work as well.

I'd really appreciate it if you could help me with this.

Thank you,
Woohyun

### Steps to Reproduce

import pybamm

def custom_step_power(variables):
    target_power = 4
    voltage = variables["Voltage [V]"]
    return target_power / voltage
step = pybamm.step.CustomStepExplicit(custom_step_power, duration=600)
sol = pybamm.Simulation(
    model, experiment=step, parameter_values=parameter_values
).solve()
pybamm.QuickPlot(sol, ["Current [A]", "Voltage [V]", "Power [W]"]).plot(0)

**Comment by agriyakhetarpal** [comment]
Hi, @WoohyunJeong95 – thanks for opening this issue. This feature to enable custom experiment steps was added in #3835 and is not released yet as a part of a stable version of PyBaMM. It will be available with PyBaMM v24.5 and its release candidates. If you wish to use the feature right away, you may install PyBaMM from sources or from the git trunk. An installation guide is available here, for this purpose: https://docs.pybamm.org/en/latest/source/user_guide/installation/index.html

**Comment by WoohyunJeong95** [comment]
Thank you! I appreciate it.
