### ISSUE TITLE
Making issue prior to PyBaMM developer training for test

### ISSUE THREAD

**Issue by MehrdadBabazadeh** [pybamm-team/PyBaMM#3980]
### Description

I suggest adding a graphical representation for documents and for developers.

### Motivation

To start contribution.

**Comment by tinosulzer** [comment]
Can you give more details about what you mean by a graphical representation?

**Comment by MehrdadBabazadeh** [comment]
> Can you give more details about what you mean by a graphical representation?

     Following long instructions either as a PyBaMM user or a first-time developer, going back and forth to different pages, and reading long instructions can be replaced by a simplified flow diagram (_**in some cases**_). If not possible, put some photos illustrating operations and steps of the procedures to follow in platforms (such as Github,...) to make it more visible to new users or developers.
Thanks
