### ISSUE TITLE
Add pandoc installation step to installation instructions

### ISSUE THREAD

**Issue by dc2917** [pybamm-team/PyBaMM#3984]
While the instruction to install pandoc is stated in the [contributing guidelines](https://docs.pybamm.org/en/stable/source/user_guide/contributing.html#testing-the-example-notebooks), it is not stated in the installation from source instructions. Given that the installation instructions [include running the tests](https://docs.pybamm.org/en/stable/source/user_guide/installation/install-from-source.html#running-the-tests), for which pandoc is required, an instruction to install pandoc should be explicit in these instructions.

**Comment by agriyakhetarpal** [comment]
Thanks for opening this, @dc2917 – it is very likely that this was missed earlier. Please feel free to make the necessary changes here!
