### ISSUE TITLE
visualise simulation results

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#40]
Add class(es)/function(s) to visualise the result of a simulation. Options:
- time vs variable plot for variables that are only functions of time (current, voltage, temperature, etc)
- Slider plot (space vs variable at a time definable by a slider) for variables that depend on space and time (concentration, etc)
- Export for plotting using external software (e.g. pgfplots, Paraview)
- others?

**Comment by martinjrobins** [comment]
should take in a `y` and `t`, plus an expression to plot (or `model.variables`) and do required plot
