### ISSUE TITLE
Add "Surface temperature" submodel

### ISSUE THREAD

**Issue by valentinsulzer** [pybamm-team/PyBaMM#4022]
This model accounts for the fact that the surface temperature of a cell in a thermal chamber is typically different from the "set"/"ambient" temperature of the chamber.

Suggested steps to do this below, but open to discussion:
- Add a submodel `SurfaceAmbientTemperature` which sets surface temperature equal to ambient temperature
- Add another submodel `SurfaceTemperatureODE` which implements the equation from [Mohan et al](https://d1wqtxts1xzle7.cloudfront.net/69868813/j.jpowsour.2014.01.09720210918-12240-190ns8h-libre.pdf?1632013230=&response-content-disposition=inline%3B+filename%3DA_lumped_parameter_electro_thermal_model.pdf&Expires=1713470219&Signature=VVdyggn0EMZaZUDAhblutOENZ6faE0Wua0uoq71ebx912paMfn2O2-lJq8SUK1nwkZf7v5jF65dIUF03R~IKZo5LXZdYEOb48oPshUycdG0h3K4EHPaGW07CNjd6e~UFP2JyNjUDMAnfP5oZHD~8cr5MRoTbNi8WTfcJ8SSdc1nyOr4uKy5xevjQKW3D0cvAbu9gSnbVZC52qdwM6jeobcJLAx7AhMetR3x1r2lHd6Jrrz-vznm1JeczXl6EzEzMgqr2tLOcKO7GLhlUVYIDhdGawR76FJHLBNyhAEPXtEMq7IUibswa~~2fdgZNTemj9lCjsExrmrri-xZhHFL5vQ__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA):
<img width="347" alt="Screenshot 2024-04-18 at 2 59 00 PM" src="https://github.com/pybamm-team/PyBaMM/assets/20817509/db0728a2-c986-46ff-800e-c5a38b294648">

- In that submodel, register a citation for that paper
- In all other thermal submodels, replace "ambient temperature" with "surface temperature"
- In `BaseBatteryModel`, add an option for "surface temperature" which can be "ambient" (default) or "ODE", then add an if statement for selecting the appropriate model
- Add a test for selecting the "ODE" option
- Add docs

**Comment by brosaplanella** [comment]
Would that be part of the thermal models or a new type of submodel?

**Comment by valentinsulzer** [comment]
New type of submodel so that it is compatible with any thermal model.
One difficulty will be calculating the `T_s-T_c/R_c` term (surface cooling i.e. ambient heating) for models other than the lumped thermal model. See https://github.com/pybamm-team/PyBaMM/pull/4021#discussion_r1571171874

**Comment by wasitahir** [comment]
@valentinsulzer can the surface temperature model used for other chemistry parameters e.g., Prada2013?
