### ISSUE TITLE
Add support for `pytest-doctestplus`

### ISSUE THREAD

**Issue by prady0t** [pybamm-team/PyBaMM#4031]
**Description**

Now that #3857 is merged, we can add support for `xdoctest` for testing doctests.
[Xdoctest](https://xdoctest.readthedocs.io/en/latest/) is a pytest equivalent to python's build-in `doctest`. See more : https://github.com/pybamm-team/PyBaMM/issues/3617#issuecomment-1854702640 

Related to : #3617

> [!NOTE]
> It was decided on 27/05/2024 to switch to `pytest-doctestplus` rather than `xdoctest`.

**Comment by agriyakhetarpal** [comment]
Hi, @prady0t – are you already on this? Let us know if you are, and one of us can assign you to it

**Comment by prady0t** [comment]
Yes please assign this to me
