### ISSUE TITLE
[Bug]: plot_voltage_components() not working

### ISSUE THREAD

**Issue by nickbrady** [pybamm-team/PyBaMM#4034]
### PyBaMM Version

23.9 and 24.1

### Python Version

3.9.6 and 3.10.12

### Describe the bug

If I follow the code outlined in [Tutorial 3: Basic Plotting](https://docs.pybamm.org/en/latest/source/examples/notebooks/getting_started/tutorial-3-basic-plotting.html) sim.plot_voltage_components() produces the error: AttributeError: 'Simulation' object has no attribute 'plot_voltage_components'

I also confirmed that the same error appears when running the [colab notebook associated with Tutorial 3](https://githubtocolab.com/pybamm-team/PyBaMM/blob/develop/docs/source/examples/notebooks/getting_started/tutorial-3-basic-plotting.ipynb). The pybamm version is 24.1 and python version 3.10 in the colab notebook.

### Steps to Reproduce

MWE
```python
import pybamm

model = pybamm.lithium_ion.DFN()
sim = pybamm.Simulation(model)
sim.solve([0, 3600])

sim.plot_voltage_components()
```

**Comment by agriyakhetarpal** [comment]
Hi, @nickbrady – closing this with reasons similar to those highlighted in #4035. I appreciate the feedback, however! I think we should more correctly mark the notebooks on development versions of the documentation to not mislead users about unreleased features. I shall do that in a PR soon.
