### ISSUE TITLE
[Bug]: AttributeError: module 'pybamm.experiment.step' has no attribute 'CustomStepExplicit'

### ISSUE THREAD

**Issue by nickbrady** [pybamm-team/PyBaMM#4035]
### PyBaMM Version

24.1

### Python Version

3.9.6 and 3.10.12

### Describe the bug

Following the examples in ["Custom Experiments"](https://docs.pybamm.org/en/latest/source/examples/notebooks/simulations_and_experiments/custom-experiments.html), one cannot reproduce the custom steps outlined in the example.

The same error is produced in the associated [colab notebook](https://githubtocolab.com/pybamm-team/PyBaMM/blob/develop/docs/source/examples/notebooks/simulations_and_experiments/custom-experiments.ipynb)

### Steps to Reproduce

MWE
```python
def custom_step_power(variables):
    target_power = 4
    voltage = variables["Voltage [V]"]
    return target_power / voltage


# Run for 10 minutes and plot
step = pybamm.step.CustomStepExplicit(custom_step_power, duration=600)
```

**Comment by agriyakhetarpal** [comment]
Hi, @nickbrady – this notebook was updated very recently with #3835 and this functionality is not available with the stable version of PyBaMM yet. It will be available with the release of PyBaMM v24.5 and its associated pre-releases. If you wish to access it, you can build PyBaMM from sources as documented in the [installation guide](https://docs.pybamm.org/en/latest/source/user_guide/installation/index.html#full-installation-guide).
