### ISSUE TITLE
Calculate summary variables only when they are called

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/PyBaMM#4058]
As discussed in #3995 

- create a `SummaryVariable` object that saves `solution.last_state` and uses it to calculate the esoh variables only when they are called (the same way as `Solution` calculates the variables only when they are called)
- allow users to pass in functions that calculate summary variables based on other variables

**Comment by pipliggins** [comment]
@rtimms reading through #3995 it looks like the decision was to not allow users to define their own summary variables, have I got that right?

**Comment by rtimms** [comment]
If we just keep summary variables as a list then I think defining your own summary variables is hard. Right now the summary variables just calculate the value of the variable at the last time point, and then change in that variable. 

We could do something more complicated like pass in functions that take a solution and perform some operation to get a summary variable, but I'm not sure there is a strong use case for this. It can always be done as a post-processing step. If you only want the last value of some quantity then users can add custom variables to the model and then add that to the list of summary variables.
