### ISSUE TITLE
All contributors badge does not update

### ISSUE THREAD

**Issue by brosaplanella** [pybamm-team/PyBaMM#4086]
The all-contributors badge on the README file does not update when new contributors are added (e.g. it's stuck to 77 but we have 81 in the all contributors table). It might be that we just need to add the README back to the files list in the configuration file (https://allcontributors.org/docs/en/bot/configuration), but not sure if that will bring the table back to the README.

**Comment by kratman** [comment]
Yeah that is updated automatically as well:
```
<!-- ALL-CONTRIBUTORS-BADGE:START - Do not remove or modify this section -->
[![All Contributors](https://img.shields.io/badge/all_contributors-77-orange.svg)](#-contributors)
<!-- ALL-CONTRIBUTORS-BADGE:END -->
```
Not the nicest way for the badge to work, but I guess it keeps them from requiring an account

I will find a fix for this since I broke it.
