### ISSUE TITLE
How to run a single charging simulation

### ISSUE THREAD

**Issue by Tangzl922** [pybamm-team/PyBaMM#4096]
Hello,

I want to simulate the charging and discharging process separately without using experiments. Is it possible to run a single charging simulation using only 'Simulation' class? I tried setting initial SOC but it kept discharging from that SOC.

Best regards

**Comment by kratman** [comment]
It is possible to manipulate things like the current without using experiments directly as long as you are OK with more limited functionality.

A normal discharging simulation looks like this:
```
model = pybamm.lithium_ion.DFN()
parameter_values = pybamm.ParameterValues("Chen2020")
sim = pybamm.Simulation(model, parameter_values=parameter_values)
sim.solve([0, 3600], initial_soc=1.0)
sim.plot(["Current [A]", "Voltage [V]"])
```
![image](https://github.com/pybamm-team/PyBaMM/assets/10170302/0207db54-13d3-4763-88c6-5b13051a8f11)


You can change the state of charge and reverse the current to do charging instead:
```
model = pybamm.lithium_ion.DFN()
parameter_values = pybamm.ParameterValues("Chen2020")
parameter_values["Current function [A]"] *= -1
sim = pybamm.Simulation(model, parameter_values=parameter_values)
sim.solve([0, 3600], initial_soc=0.0)
sim.plot(["Current [A]", "Voltage [V]"])
```
![image](https://github.com/pybamm-team/PyBaMM/assets/10170302/2609b660-2845-4ea8-b336-0923ec4c77a4)


Of course realistic charging and discharging will be slightly different, but this is a quick way it can be done.

**Comment by kratman** [comment]
@Tangzl922 Let me know if that helps

**Comment by Tangzl922** [comment]
Hi it works, thanks for your answer!
