### ISSUE TITLE
Make function for handling time or reuse an existing one

### ISSUE THREAD

**Issue by kratman** [pybamm-team/PyBaMM#4113]
The following code was added in #4073:
```python
            elif term.endswith("s"):
                end_time_s = term.split("s")[0]
                termination_dict["time"] = (float(end_time_s), "s")
            elif term.endswith("min"):
                end_time_s = term.split("min")[0]
                termination_dict["time"] = (float(end_time_s) * 60, "s")
            elif term.endswith("h"):
                end_time_s = term.split("h")[0]
                termination_dict["time"] = (float(end_time_s) * 3600, "s")
```
This should probably be converted to a function. For example, if a space is required in the string then:
```python
elif temer.split(" ")[1] in ["h", "min", "s"]:
    end_time = term.split(" ")[0]
    unit = term.split(" ")[1]
    termination_dict["time"] = convert_time_to_seconds(end_time, unit)
```

**Comment by kratman** [comment]
Note: Part of this ticket is finding out if there are other instances where this change can be made. So whoever takes this up, please search for other time conversions

**Comment by valentinsulzer** [comment]
There is a `_convert_time_to_seconds` function https://github.com/pybamm-team/PyBaMM/blob/develop/pybamm/experiment/step/base_step.py#L344

**Comment by agriyakhetarpal** [comment]
From https://github.com/pybamm-team/PyBaMM/pull/4073#discussion_r1617775872 I think you'll need to comment here, @mleot, so that GitHub can add your name to the list of potential assignees

**Comment by mleot** [comment]
Got it, commenting here.
