### ISSUE TITLE
Remove `pybamm_install_jax` and references to it

### ISSUE THREAD

**Issue by agriyakhetarpal** [pybamm-team/PyBaMM#4131]
Based on https://github.com/pybamm-team/PyBaMM/issues/4127#issuecomment-2145762187 and pointed out by @DavidMStraub, after v24.5 gets released on PyPI, the `pybamm_install_jax` entry point and its corresponding method `install_jax` in `pybamm/util.py` can be removed from the source code for v24.9, following the completion of its deprecation cycle since v23.9.

There might be a few references in the documentation about it as well, I have not checked those at this time.

**Comment by arjxn-py** [comment]
Priority is dependent upon how close we're to v24.9, so feel free to update that in future whenever
