### ISSUE TITLE
Fix Relative Imports in the codebase

### ISSUE THREAD

**Issue by arjxn-py** [pybamm-team/PyBaMM#4134]
Currently, there are several instances of relative imports, such as:
```python
from ..lithium_ion.dfn import DFN as LithiumIonDFN
```

Relative imports can be problematic as they can make the code less readable and harder to maintain. They are also prone to errors during refactoring and restructuring of the codebase. To improve code quality and maintainability, we should transition to absolute imports, which are clearer and more robust.

### Direction
Ruff which we use already provides functionality to enforce absolute imports instead of relative ones. This can be achieved by enabling the relative-imports rule in Ruff.

### Possible Implementation
We will configure Ruff to flag relative imports and suggest using absolute imports. This configuration can be added to the `pyproject.toml` file.

Here's how you may update the `pyproject.toml` to include this rule:

```python
[tool.ruff.lint]
select = [
    "TID252",
]
```

*Originally been posted in [4117(comment)](https://github.com/pybamm-team/PyBaMM/pull/4117#discussion_r1621065664)*

**Comment by prady0t** [comment]
You can assign this to me.
