### ISSUE TITLE
Update Code of Conduct

### ISSUE THREAD

**Issue by brosaplanella** [pybamm-team/PyBaMM#4160]
PyBaMM's code of conduct is adapted from contributor covenant 1.4. It would be good to update to the newest version (v2.1) as done in https://github.com/pybamm-team/pybamm-cookiecutter/pull/10. 

This probably needs formal approval from the Steering Council at some point, but given than it is an update on our current CoC it should be fine to do it retrospectively (tagging SC members @valentinsulzer @martinjrobins @Scottmar93 @Saransh-cpp @gjo97).

**Comment by valentinsulzer** [comment]
Fine by me

**Comment by gjo97** [comment]
Fine by me too
