### ISSUE TITLE
Broken link references in SPM example notebook 

### ISSUE THREAD

**Issue by santacodes** [pybamm-team/PyBaMM#4181]
The link references in the SPM example notebooks use markdown reference links with an `inline code` -  
```md
[`reference`](/link)
```
which doesn't render properly into a reST link ref [here](https://docs.pybamm.org/en/latest/source/examples/notebooks/models/SPM.html).

Preview - 

![docerror](https://github.com/pybamm-team/PyBaMM/assets/52504160/0930f4aa-fcf7-411c-8f28-6bddaecaf012)

**Comment by santacodes** [comment]
@arjxn-py this is a different issue relating to broken links in the documentation of PyBaMM 😅

**Comment by arjxn-py** [comment]
Oh oops 😬
