### ISSUE TITLE
Use `tempfile` for temporary JSON files.

### ISSUE THREAD

**Issue by prady0t** [pybamm-team/PyBaMM#4206]
After merging #4125 , we generate a lot of temporary JSON files while running tests. These files are short-lived and are created and deleted with every test passing, although if the tests fail these files have to be deleted manually.

You can see the number of json files being generated when test suit fails many times : 

<img width="492" alt="Screenshot 2024-06-18 at 6 27 55 PM" src="https://github.com/pybamm-team/PyBaMM/assets/99216956/46f898c4-cdd1-424d-8e75-2351b8280a06">

We can use `tempfile` to generate temporary files to fix this. See : https://docs.python.org/3/library/tempfile.html

**Comment by prady0t** [comment]
You can assign this to me, I will open a PR soon.

**Comment by kratman** [comment]
This is true for notebooks as well. They make images and other files, but do not clean them up

**Comment by agriyakhetarpal** [comment]
For the notebooks, I think it's better to not use tempfiles so as to not mislead newcomers to PyBaMM and Python, plus users might want to inspect the images after the notebook/cell has been executed
