### ISSUE TITLE
[Bug]: pybamm.step.current(1, duration="1 hour", termination="2.5 V")，

### ISSUE THREAD

**Issue by ADSDAW** [pybamm-team/PyBaMM#4233]
### PyBaMM Version

22.9

### Python Version

3.7

### Describe the bug

The step attribute is gone in pybamm.step.current()

### Steps to Reproduce

pybamm.step.current(1, duration="1 hour", termination="2.5 V")
Error：AttributeError: module 'pybamm' has no attribute 'step'

**Comment by kratman** [comment]
@ADSDAW The version of pybamm you are using is quite old and we do not support less than python 3.9 anymore. Can you try using a newer python version (I recommend python 3.11) and the pybamm version 24.1?

**Comment by ADSDAW** [comment]
Thank  u vary much
