### ISSUE TITLE
Pybtex warnings on downstream projects

### ISSUE THREAD

**Issue by kratman** [pybamm-team/PyBaMM#4304]
When importing projects which use PyBaMM (e.g. pybamm-eis) users can get the following warning:
```
>>> import pybammeis
2024-07-29 18:14:25.383 - [WARNING] citations.read_citations(76): Citations could not be read
because the 'pybtex' library is not installed. Install 'pybamm[cite]' to enable citation reading.
```
This warning should probably be removed since it is popping up in other projects

**Comment by 1e9abhi1e10** [comment]
Hey team,
I've created PR #4322 to fix the citation warning issue by using a `pass` statement. Should we consider other approaches like debug-level logging, setting a flag, or using a global config instead? What do you think would work best for our needs?
