### ISSUE TITLE
[Bug]: Spurious key 'check_already_exists' added to output of `pybamm.ParameterValues.create_from_bpx`

### ISSUE THREAD

**Issue by ejfdickinson** [pybamm-team/PyBaMM#4339]
### PyBaMM Version

24.5

### Python Version

23.9

### Describe the bug

Due to a keyword argument error, a spurious / meaningless key `'check_already_exists'` is added to the `pybamm.ParameterValues` object output from `pybamm.ParameterValues.create_from_bpx()`.

This occurs because of the following line in `parameters.bpx._bpx_to_param_dict()`:

```python
    pybamm_dict.update(
        {"Total heat transfer coefficient [W.m-2.K-1]": 0}, check_already_exists=False
    )
```

Here `pybamm_dict` is type `dict`, not `pybamm.ParameterValues`, so the `check_already_exists` keyword argument is erroneous and is interpreted as a new key to add. To fix, delete this keyword argument.

### Steps to Reproduce

Call `pybamm.ParameterValues.create_from_bpx()` on any schema-valid file and consult the output.

**Comment by kratman** [comment]
@ejfdickinson I put up a fix for this
