### ISSUE TITLE
Possible to split optional and required dependencies on conda

### ISSUE THREAD

**Issue by Saransh-cpp** [pybamm-team/PyBaMM#4342]
See how hist splits its installation as `hist_base` (with required dependencies) and `hist` (with all the optional dependencies) -

https://github.com/conda-forge/hist-feedstock/blob/33fb4d946e7f9672c6b448b65ff199adcabdb8d1/recipe/meta.yaml#L15-L59

**Comment by agriyakhetarpal** [comment]
Another possible medium task for someone who does this is to compile the IDAKLU solver for PyBaMM in conda-forge since we currently ship without it. I shall open a new issue about this, though.

**Comment by Saransh-cpp** [comment]
Being worked in https://github.com/conda-forge/pybamm-feedstock/pull/70

**Comment by prady0t** [comment]
> Another possible medium task for someone who does this is to compile the IDAKLU solver for PyBaMM in conda-forge since we currently ship without it. I shall open a new issue about this, though.

Should I open an issue (if not yet) and start working on this?

**Comment by agriyakhetarpal** [comment]
> > Another possible medium task for someone who does this is to compile the IDAKLU solver for PyBaMM in conda-forge since we currently ship without it. I shall open a new issue about this, though.
> 
> Should I open an issue (if not yet) and start working on this?

I've already opened it here: https://github.com/conda-forge/pybamm-feedstock/issues/65. Please feel free to get started and fork away!

**Comment by Saransh-cpp** [comment]
This is up now - https://anaconda.org/conda-forge/pybamm-base!
