### ISSUE TITLE
Entropic change should be a function of sto only

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/PyBaMM#4405]
It seems odd to me that we allow the entropic change parameter to be a a function of both `sto` and `c_s_max`. It seems this stems from the Marquis2019 parameter set that takes the entropic change function from [Scott Moura's FastDFN code](https://github.com/scott-moura/fastDFN). IMO it should just be a function of `sto` and the function there that depends on `sto` was probably parameterised for a given `c_s_max`, in which case we can just update the coefficients accordingly.

This would be a breaking change. Do people think it would be worth it?

**Comment by valentinsulzer** [comment]
Yes
