### ISSUE TITLE
Mismatch of estimated OCP and OCP from PyBAMM

### ISSUE THREAD

**Issue by Saketh1729** [pybamm-team/PyBaMM#4522]
In the simulation attached below I have used the parameters from Chen2020 to simulate the Single Particle Model. I have extracted the positive electrode stoichiometry as an array and have estimated the OCP by plugging in the value to the function defined in the Chen2020.py file.

But, when I cross-reference this OCP plot with the OCP directly obtained from PyBAMM simulation, there is a deviation . Please let me know what could be done.
The plot showcasing the deviation is: 
![Image](https://github.com/user-attachments/assets/9e56bc91-671b-4d8f-a231-a565a0e10834)

The code for generation of the image is : 

```python
import pybamm
import numpy as np
from matplotlib import pyplot as plt
from Chen2020 import nmc_LGM50_ocp_Chen2020 as nmcocp

model = pybamm.lithium_ion.SPM()
parameter = pybamm.ParameterValues('Chen2020')
sim=pybamm.Simulation(model, parameter_values=parameter, C_rate =1)
simulation = sim.solve([0,3600])
xp=simulation['Positive electrode stoichiometry']
t=simulation['Time [s]']
OCP_pos = simulation['X-averaged positive electrode open-circuit potential [V]']
arr =np.array(xp.entries)
ocp_theo = []
for a in arr:
  ocp_theo.append(nmcocp(a))
plt.plot(t.entries, ocp_theo, label='Estimated OCP') # OCP obtained by giving the stoichiometry into the Chen2020 function
plt.plot(t.entries, OCP_pos.entries, label='Simulation OCP') #OCP obtained directly from simulation
plt.xlabel('Time [s]')
plt.ylabel('OCP [V]')
plt.legend()

```

**Comment by valentinsulzer** [comment]
"X-averaged positive electrode open-circuit potential [V]" is the evaluated at the surface in the particle, so it is affected by concentration gradients in the particle. Try plotting "Negative electrode bulk open-circuit potential [V]" instead.

**Comment by Saketh1729** [comment]
Taking the bulk open-circuit potential has resolved the issue, they are now in perfect overlap. Thank you so much .
