### ISSUE TITLE
[Bug]: `pybamm.ParameterValues.pop()` does not return the popped value

### ISSUE THREAD

**Issue by ejfdickinson** [pybamm-team/PyBaMM#4569]
### PyBaMM Version

24.9

### Python Version

3.9

### Describe the bug

The dict-like `pybamm.ParameterValues` class implements `pop()`. `pop()` is expected to return the popped value, but the method implementation has no return value.

To fix, replace `pybamm.parameters.parameter_values.py:186-187`:

```python
    def pop(self, *args, **kwargs):
        self._dict_items.pop(*args, **kwargs)
```

becomes

```python
    def pop(self, *args, **kwargs):
        return self._dict_items.pop(*args, **kwargs)
```

### Steps to Reproduce

The return value of `parameter_values.pop(k)` is `None` for any `pybamm.ParameterValues` object.

**Comment by kratman** [comment]
I will push a change for this real fast
