### ISSUE TITLE
Add temperature to lithium-ion models

### ISSUE THREAD

**Issue by Scottmar93** [pybamm-team/PyBaMM#457]
**Summary**
Add temperature equations to pybamm with focus of getting working for lithium-ion for now 

 **Motivation**
need temperature dependence for paper

**Comment by rtimms** [comment]
would be good to have a lumped thermal model (i.e. x dependence integrated out) since this is the relevant limit for most models and significantly reduces the number of extra eqns to solve

**Comment by Scottmar93** [comment]
Sounds good, will do a full and a lumped model for the 1D models for now and we can think about how to do it in 2D later
