### ISSUE TITLE
2+1D Pouch Cell Model-Error in checking negative electrode potential

### ISSUE THREAD

**Issue by Santiagopeacely** [pybamm-team/PyBaMM#4617]
Hello, when I use the options = {"current collector": "potential pair" and "dimension": 2}, I am going to check the change of negative potential, but there is an error. I hope you can help me solve it. Thank you very much.

![Image](https://github.com/user-attachments/assets/f11d2cf6-68dc-4e80-b038-532ab94e0d2d)
![Image](https://github.com/user-attachments/assets/8f6a5567-8593-4a66-9076-a498f4132b7e)

**Comment by brosaplanella** [comment]
Hi! We have now moved our support to the [PyBaMM Discourse](https://pybamm.discourse.group/). Can you post your question there?
