### ISSUE TITLE
如何实现该案例

### ISSUE THREAD

**Issue by Santiagopeacely** [pybamm-team/PyBaMM#4618]
I am trying to implement the case in the figure, but I am unable to do so. Is it a problem with my variable selection or something else? Could you please help me answer this? Thank you
![Image](https://github.com/user-attachments/assets/056e187d-715b-4c7f-9950-27086a1eafb9)
![Image](https://github.com/user-attachments/assets/57b330e9-6784-4ad6-bb80-0650727a8419)

**Comment by brosaplanella** [comment]
Hi! We have now moved our support to the [PyBaMM Discourse](https://pybamm.discourse.group/). Can you post your question there?
