### ISSUE TITLE
Review dependencies in documentation

### ISSUE THREAD

**Issue by Saransh-cpp** [pybamm-team/PyBaMM#4631]
I can see that a few PyBaMM dependencies are missing from - https://docs.pybamm.org/en/stable/source/user_guide/installation/index.html.

The dependencies in `pyproject.toml` and documentation should match.

**Comment by agriyakhetarpal** [comment]
@prady0t, Saransh is conducting a hackathon next week. Could we please leave some of the new issues he's opening and the existing low-priority ones for newcomers? Thanks!

**Comment by agriyakhetarpal** [comment]
@prady0t, Saransh is conducting a hackathon at UCL next week. Could we please leave some of the new issues he's opening and the existing low-priority ones for newcomers? Thanks!

**Comment by prady0t** [comment]
Oh I wasn't aware thanks for letting me know!

**Comment by Saransh-cpp** [comment]
Feel free to take this up now, @prady0t :)
