### ISSUE TITLE
Request for Practical Simulation Case Studies and Resources in PyBaMM

### ISSUE THREAD

**Issue by Yull-1** [pybamm-team/PyBaMM#4636]
Hi PyBaMM Team,

I am currently working with PyBaMM to simulate lithium-ion batteries, but I have found that there are relatively few practical case studies or detailed examples available, particularly for real-world applications. In comparison to platforms like COMSOL, which offer an extensive library of example models and case studies, I believe more comprehensive references would greatly benefit new users like myself who are looking to apply PyBaMM to more complex and varied scenarios.

Thank you for your time and assistance. I look forward to your reply.

**Comment by martinjrobins** [comment]
Hi @Yull-1, can you please elaborate how the existing examples in the user guide (https://docs.pybamm.org/en/stable/source/user_guide/index.html) or example notebooks (https://docs.pybamm.org/en/stable/source/examples/index.html) fall short of what you are expecting? We're always looking to improve the documentation so specific issues that we can action are always valuable

**Comment by kratman** [comment]
@Yull-1 Do you have any updates for this ticket?

**Comment by Yull-1** [comment]
Thank you, there are no further questions
