### ISSUE TITLE
Autoresponse in Github discussions pointing people to Discourse

### ISSUE THREAD

**Issue by brosaplanella** [pybamm-team/PyBaMM#4647]
Now that we have migrated to Discourse, it would be useful to set up an autoresponse to newly created GitHub discussions pointing people to Discourse.

This action should do the job: https://github.com/marketplace/actions/discussion-auto-responder

**Comment by agriyakhetarpal** [comment]
Also, to take up in the same PR: add links to Discourse in a more prominent place in the repository README + docs pages

**Comment by Saransh-cpp** [comment]
Maybe also as an issue type -

![Image](https://github.com/user-attachments/assets/d72adbe6-b09e-4f7b-b5f1-ecc4cca7f767)

**Comment by agriyakhetarpal** [comment]
It looks like a lot of people are still posting in GitHub Discussions and might not be aware of Discourse at all, so I'll mark it with a higher priority for anyone who would like to take it up

**Comment by agriyakhetarpal** [comment]
Of course, please feel free to. We should get this done quickly. Could you also test on your fork while you're at it?

**Comment by ahamed24** [comment]
@arjxn-py if you dont mind. Could i take this up :)

**Comment by arjxn-py** [comment]
Hi @ahamed24, yes if you want to give it a try, you're welcome
