### ISSUE TITLE
Update versioning docs

### ISSUE THREAD

**Issue by Saransh-cpp** [pybamm-team/PyBaMM#4656]
PyBaMM had a new release in November, deviating from the release cycle highlighted in https://github.com/pybamm-team/PyBaMM?tab=readme-ov-file#versioning

The versioning scheme should be updated to reflect the new cycle (and I am not sure what that is).

**Comment by agriyakhetarpal** [comment]
> the new cycle (and I am not sure what that is)

AFAIA, the release cycle is the same as of now (three releases a year), it's just that the November release was an off-band one: https://pybamm.org/news/2024/11/21/pybamm-24.11/

**Comment by agriyakhetarpal** [comment]
We can probably close this, unless you had something else in mind!

**Comment by Saransh-cpp** [comment]
Ah, thanks! I was looking for a deadline for the conda docs and the GitHub release page confused me.
