### ISSUE TITLE
[Bug]: what is the default hysteresis model in SPM

### ISSUE THREAD

**Issue by Algo-eng** [pybamm-team/PyBaMM#4657]
### PyBaMM Version

24.9

### Python Version

3.12.7

### Describe the bug

Without providing model option for open circuit potential 

But providing lithiation and delithiation ocps to parameters set, it is simulating hysteresis.

Help me to understand what is happening exactly 

### Steps to Reproduce

Used SPM with lumped thermal model, surface form algebraic, particle size distribution, contact resistance true.

Provided both positive and negative electrode lithiation, delithiation and average ocps, diffusivities, exchange current densities.

Simulated for charging and discharging.

There is difference in voltage curve like hysteresis.

### Relevant log output

```shell

```

**Comment by Saransh-cpp** [comment]
Hi, @Algo-eng. This issue looks like a discussion/question and not a bug. Could you please move this to pybamm's discourse - https://pybamm.discourse.group? Thanks!
