### ISSUE TITLE
[Bug]: max_y_value

### ISSUE THREAD

**Issue by Algo-eng** [pybamm-team/PyBaMM#4659]
### PyBaMM Version

24.9

### Python Version

3.12.7

### Describe the bug

What is the meaning of max_y_value?

While cyclic aging simulation it is saying, y[1:2] exceeded given limit. 

### Steps to Reproduce

What is the meaning of max_y_value?

While cyclic aging simulation it is saying, y[1:2] exceeded given limit. 

### Relevant log output

```shell

```

**Comment by Saransh-cpp** [comment]
Hi, @Algo-eng. This issue looks like a discussion/question and not a bug. Could you please move this to pybamm's discourse - https://pybamm.discourse.group? Thanks!

**Comment by Algo-eng** [comment]
Posted in discourse, please check
