### ISSUE TITLE
Fix all-contributors bot so we can have required workflows

### ISSUE THREAD

**Issue by kratman** [pybamm-team/PyBaMM#4671]
The all-contributors bot uses the [skip ci] command. This prevents us from having required checks on github actions. I attempted a workaround, but had to revert the change since it did not work properly.

This is mainly a reminder for myself. I will fix this in a couple days

**Comment by agriyakhetarpal** [comment]
To fix: set `skipCi` to `false` in the `all-contributors` bot's settings and use `paths:` / `paths-ignore:` accordingly to ignore the `all-contributors.md` file for all workflows.

xref: #3662

**Comment by kratman** [comment]
Thanks. I was trying GitHub side options yesterday, but ran out of time. I figured this was possible, I will try it this afternoon
