### ISSUE TITLE
Add a warning to the list of dependencies in the docs.

### ISSUE THREAD

**Issue by prady0t** [pybamm-team/PyBaMM#4705]
As [discussed](https://github.com/pybamm-team/PyBaMM/pull/4689#issuecomment-2558267310), add a warning [admonition](https://pydata-sphinx-theme.readthedocs.io/en/stable/examples/kitchen-sink/admonitions.html#warning) to warn user for a potentially outdated list of dependencies on [this](https://docs.pybamm.org/en/latest/source/user_guide/installation/index.html) page.

**Comment by RohitP2005** [comment]
@prady0t i would like to take on this issue

**Comment by prady0t** [comment]
> @prady0t i would like to take on this issue
> 
Sure go ahead!
