### ISSUE TITLE
Running thermal_lithium_ion example doesn't find parameters

### ISSUE THREAD

**Issue by TomTranter** [pybamm-team/PyBaMM#494]
**Describe the bug**
FileNotFoundError: [Errno 2] File b'C:\\Code\\PyBaMM\\examples\\scripts\\input\\parameters\\lithium-ion\\mcmb2528_lif6-in-ecdmc_lico2_parameters_Dualfoil.csv' does not exist: b'C:\\Code\\PyBaMM\\examples\\scripts\\input\\parameters\\lithium-ion\\mcmb2528_lif6-in-ecdmc_lico2_parameters_Dualfoil.csv'

**To Reproduce**
Steps to reproduce the behaviour:
check out master
run example

I think it needs these lines added like the other examples
import os
os.chdir(pybamm.__path__[0]+'/..')
or perhaps the base_battery_model should try to find a file in cwd and if not found go to the root

**Comment by martinjrobins** [comment]
thanks for reporting this @TomTranter. 

Pybamm should automatically use the root directory where you installed it. you actually shouldn't need `os.chdir(pybamm.path[0]+'/..')` anymore. 

how did you install pybamm, was it using `pip install <path_to_pybamm>`?

can you run this and let me know what you get:
```python
import pybamm
print(pybamm.root_dir())
```

**Comment by TomTranter** [comment]
I did use pip and have the code in the the directory ''c:\\code\\pybamm'' which is found by the root_dir() function. However, Line 27 of base_battery_model uses os.getcwd()
```
input_path = os.path.join(os.getcwd(), "input", "parameters", "lithium-ion")
```

**Comment by martinjrobins** [comment]
ahhh, I see it now. @Scottmar93 just merged in a refactor of the models that introduced this. I'll change this back to `pybamm.root_dir()`

**Comment by Scottmar93** [comment]
Sorry about this. Thank you for catching this Martin
