### ISSUE TITLE
Add further instructions for installing without -e

### ISSUE THREAD

**Issue by Scottmar93** [pybamm-team/PyBaMM#498]
Jon has an issue installing PyBaMM without developers options. Import pybamm worked fine within the PyBaMM/ directory but no module `pybamm` was found in the subdirectories (e.g. PyBaMM/examples/). Tried adding the pybamm directory to the PYTHONPATH but don't think that has worked. @martinjrobins and ideas as to why this would happen?

**Comment by Scottmar93** [comment]
solution was: 
`export PYTHONPATH=$PYTHONPATH:/path/to/pybamm/`

**Comment by jonchapman1** [comment]
ipython finds pybamm OK.
But Jupyter cannot find pybamm.
I noticed the same issue on Binder. When I run a notebook through there it cannot find pybamm.

**Comment by martinjrobins** [comment]
solution requires adding this line in `setup.py`:

```python
packages=find_packages(),
```

I'll add this in
