### ISSUE TITLE
error on assertWarns - test_base_model.py

### ISSUE THREAD

**Issue by martinjrobins** [pybamm-team/PyBaMM#505]
The assertion test in `test_base_model.py` fails:

```python
with self.assertWarns(pybamm.ModelWarning):
    model.check_well_posedness()
```

might be related to this bug:
https://bugs.python.org/issue29620

turned off this warning test for now, but need to figure out why this fails. The `check_well_posedness` raises the expected warning, but then unittest itself throws an error

**Comment by tinosulzer** [comment]
does it work locally but not on travis for you? works locally for me

**Comment by martinjrobins** [comment]
yea, it works fine locally for me, I only see it on travis, which makes it difficult to debug.
