### ISSUE TITLE
Master branch failing 

### ISSUE THREAD

**Issue by Scottmar93** [pybamm-team/PyBaMM#514]
Master branch is failing related to scikits-FEM i think following pull request #487.

error is
```
File "/home/travis/build/pybamm-team/PyBaMM/pybamm/meshes/scikit_fem_submeshes.py", line 93, in __init__
    lambda y, z: self.on_boundary(y, z, tabs["negative"])
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/skfem/assembly/global_basis/global_basis.py", line 168, in get_dofs
    facets = self.mesh.facets_satisfying(facets)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/skfem/mesh/mesh.py", line 360, in facets_satisfying
    return np.nonzero(test(np.array(midp)))[0]
TypeError: <lambda>() missing 1 required positional argument: 'z'
```

**Comment by martinjrobins** [comment]
the lambda has two arguments, y and z, but the code in scikits fem calls the lambda with a single np.ndarray. @rtimms: do you know why this suddenly doesn't work?

**Comment by rtimms** [comment]
@martinjrobins looks like scikit changed the interface for the method `facets_satisfying` from being coords x,y to an array of coords. have fixed this now. however, running `run-test.py --unit` all the tests pass, but get a shape error on `test_spatial_methods.test_scikit_finite_element.TestScikitFiniteElement` when running `run-tests.py --quick`. running the test on its own is also fine. any ideas what might be causing this?

**Comment by tinosulzer** [comment]
When you run all unit tests, `pybamm.settings.debug_mode` is set to `True` and then the shape of every symbol you create is tested in `Symbol.__init__`. By default (running individual tests) `pybamm.settings.debug_mode` is `False`. Can you try setting `pybamm.settings.debug_mode = True` in the individual test?

**Comment by martinjrobins** [comment]
not sure, the quick option should just run the unit tests as normal

**Comment by tinosulzer** [comment]
So unit uses an executable whereas quick uses a subprocess. The executable ignores the debug mode option. Maybe easiest to just make unit also use a subprocess, and get rid of executables since we don't need python2 any more.
We should probably also set `pybamm.settings.debug_mode = True` in all the individual unit tests as well to avoid this kind of confusion
