### ISSUE TITLE
improve shape tests for 2plus1D

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/PyBaMM#527]
Sometimes shape test gives an error because the domain of a variable isn't set to current collector in 2D, when it should be. In practice the object ends up being the correct shape, just the domain it is labelled with is wrong. e.g. in `inverse_butler_volmer` the line `eta_r = (2 / ne) * pybamm.Function(np.arcsinh, j / (2 * j0))` gives a shape error. `j` has the expected shape, but `j0` doesn't as it contains a broadcast whose child had domain `[]` but should be `["current collector"]`

**Comment by tinosulzer** [comment]
I've fixed this in #546 (I think)
