### ISSUE TITLE
many particles temperature dependent diffusion

### ISSUE THREAD

**Issue by Scottmar93** [pybamm-team/PyBaMM#535]
For the DFN with a full thermal model, we required `D(c_s, T)` in the particle. For a full thermal model: 
- T is a function of `x` (the macroscale variable) but not of `r`. 
- the domain of `T` is `["negative electrode"]` and therefore not equal to the domain of `c_s` which is `["negative particle"]` (and so function raises domain errors)

Briefly tried `pybamm.Broadcast(T, ["negative particle"], broadcast_type="primary")` and got shape errors but I think this is probably the right direction.

**Comment by tinosulzer** [comment]
@Scottmar93 have a look but I think this is now fixed in master
