### ISSUE TITLE
Remove sto*0 from solid diffusivity functions

### ISSUE THREAD

**Issue by Scottmar93** [pybamm-team/PyBaMM#547]
I just put a hack of `sto*0` into the solid diffusion functions for now to satisfy the shape tests. We should refactor shape tests for functions so that this does not need to be done.

**Comment by tinosulzer** [comment]
Fixed in #546 :)

**Comment by tinosulzer** [comment]
Turns out this fails later on :(
Would require changing `Addition._binary_simplify` to maintain the shape in the case where we have Matrix(0) + Scalar(not zero). Not going to do this right now.
