### ISSUE TITLE
step by step instructions for windows users

### ISSUE THREAD

**Issue by martinjrobins** [pybamm-team/PyBaMM#576]
- based on WSL - describe how WSL works
- virtual-env, how to install. remember to re-activate
- how to install scikits.odes dependencies

based on the exact order

**Comment by martinjrobins** [comment]
TO INVESTIGATE: file saving/creating between WSL and windows

**Comment by ferranbrosa** [comment]
For file saving/creating Visual Studio Code works very well and you can get it to run directly in WSL. It is a bit tricky to set up and you need to open a port (not sure if that is the right wording) so you can see the plots in Windows. We could suggest that Windows users do that in the basic instructions (if they are not advanced users probably they won't have a preference about the editor).
