### ISSUE TITLE
Electrolyte potential strangely large

### ISSUE THREAD

**Issue by ferranbrosa** [pybamm-team/PyBaMM#585]
**Describe the bug**
When you run the example scripts for the SPMe and the DFN models the dimensional electrolyte potential is surprisingly large (of the order of 3V or higher). That is strange, especially for the SPMe in which the predicted size, from the analysis, is that it should be of the order of 180 \pm 25 mV.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '/PyBaMM/examples/scripts/DFN.py' or /PyBaMM/examples/scripts/SPMe.py'
2. Run it
3. Check electrolyte profile at late times.

**Comment by rtimms** [comment]
have fixed this. looks like the potential scale had been inadvertently deleted at some point. will make a PR now
