### ISSUE TITLE
Example notebook showing changing submodel

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/PyBaMM#606]
Add an example notebook showing how to load up a default model (e.g. SPM) and swap out a submodel, e.g. ODEs for particle concentration (fast diffusion) instead of Fickian. Also show how to build up your own model from submodels.

**Comment by rtimms** [comment]
Would simply having an option `build=True` by default for any of the pre-defined models be an easy fix for this? By default the model builds, but you can load it with `build=False` then swap out a submodel e.g. `model.submodels["electrolyte diffusion"] = my_new_electrolyte_model`, and run `model.build_model`? Thoughts @martinjrobins @Scottmar93 @tinosulzer

**Comment by martinjrobins** [comment]
that sounds like a good solution to me

**Comment by tinosulzer** [comment]
yep sounds good
