### ISSUE TITLE
Broadcast to cell edges

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/PyBaMM#609]
We should allow for Broadcasts onto cell edges if required by the spatial method. This is needed e.g. for `fast_diffusion`, in `constant_stefan_maxwell_diffusion` and in `isothermal` models. At the moment these all broadcast zero flux to the appropriate domain, but this ends up being evaluated on cell centers, not edges.

**Comment by tinosulzer** [comment]
As part of this I have moved the particle submodels to all be in the same folder, trying to clear up the submodel structure, is that ok? @Scottmar93
