### ISSUE TITLE
Use repeat strucuture when calculating the Jacobian. 

### ISSUE THREAD

**Issue by Scottmar93** [pybamm-team/PyBaMM#650]
When discritizing in primary and secondary dimensions, use the `pybamm.Kron` symbol instead of 
```
pybamm.Matrix(np.kron(submatrix))
```
and add a method for evaluating `pybamm.Kron` when calculating the jacobian. This method should find the child submatrix, take the jacobian, and then `np.kron` the result. 

This should be more efficient than taking the jacobian of the full "already kroned" matrix.

**Comment by Scottmar93** [comment]
@tinosulzer  @rtimms we can probably close this now?

**Comment by tinosulzer** [comment]
Closing, @rtimms  feel free to reopen if still working on this
