### ISSUE TITLE
Add an Experiment class 

### ISSUE THREAD

**Issue by Scottmar93** [pybamm-team/PyBaMM#658]
**Summary**
Add an `Experiment` class where the user can define all thing related to the specific set up of an experiment, including:
- initial conditions
- cycling profile
- SOC to concentrations calculator
- cooling set up? 

Feel free to suggest other things that should be in this

 **Motivation**
Performing different experiments on models will be one of the main use cases of PyBaMM so we should have a clear and simple method for setting this up.

**Comment by ferranbrosa** [comment]
Some experiments (GITT, HPPC...) are based on applying pulses to the battery. This can be easily implemented as a time dependent current, but it would be interesting to include a pulse function so it is friendly to users who are not used to coding. This can be helpful when including it in the GUI.
