### ISSUE TITLE
Use fuzzy string matching 

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#662]
Fuzzy string matching libraries [already exist](https://chairnerd.seatgeek.com/fuzzywuzzy-fuzzy-string-matching-in-python/).
We could help the problem of "lots of variables in the variables dict" by implementing `model.variables` as a "fuzzy dictionary" which, when a key is required, does something like:

- try finding the key
- if `KeyError`, look in dict for similar keys (e.g. at most 3 most similar keys above a certain threshold of similarity)
- allow the user to change the key they're asking for
- continue

**Comment by Scottmar93** [comment]
Seems a cool idea. Would be good to return a warning that says: 'couldn't find "x" so using "y" instead'. I think we should also have the option to turn on/off this fuzzy key so that we can raise error when running tests.

**Comment by tinosulzer** [comment]
Oh yeah I hadn't thought of the tests. Maybe easier to just raise an error that suggests a different name instead (the same way git does when you type in the wrong command)

**Comment by Scottmar93** [comment]
Do we not already have that type of functionality though? In that if we type the wrong string in we will see an error message saying something along the lines of "domain must be in ["negative particle", ... etc], and not X"? It won't suggest the closest matching string to your domain but given there is only about 5 domains so its not hard for the user to see what they should have typed.
