### ISSUE TITLE
Casadi solver

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#664]
Add casadi solver. Requires writing the tree to a casadi format. Makes use of their Jacobian evaluation, and hopefully later also optimization toolbox

**Comment by tinosulzer** [comment]
Casadi doesn't support root-finding and has no plans to: https://github.com/casadi/casadi/pull/2210, https://github.com/casadi/casadi/issues/2201.

Maybe still possible to use their jacobian and adjoint and pass to other solvers.

**Comment by rtimms** [comment]
:( still, might be worth adding some kind of `to_casadi` functionality so we can use its other features
