### ISSUE TITLE
Fix link in Windows installation instructions

### ISSUE THREAD

**Issue by jedgedrudd** [pybamm-team/PyBaMM#682]
**Describe the bug**
The "here" in the line "Now head over and follow the installation instructions for PyBaMM for linux here" links to https://github.com/pybamm-team/PyBaMM/blob/master/INSTALL_LINUX.md, but this should be https://github.com/pybamm-team/PyBaMM/INSTALL_LINUX.md

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to INSTALL-WINDOWS.md
2. Scroll down to 'Now head over and follow the installation instructions for PyBaMM for linux here'
4. Click on "here" in this line

**Expected behaviour**

**Screenshots**

**Additional context**

**Comment by tinosulzer** [comment]
Fixed
