### ISSUE TITLE
Results folders

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#683]
Have thought about the results folder and I think a good workflow would be to have a separate repository for each set of results (e.g. paper). Then each repository can 

- Be tested on travis, or not, up to the repository owner
- Be kept up to date with latest version of PyBaMM, or not, up to the repo owner. To freeze a specific version of PyBaMM, the repo readme can checkout a particular version, or commit hash
- Be public or private, up to the repo owner.

Then the `results` folder in pybamm just gives links to different results repositories. We could host some of these on `pybamm-team` if we want. We can also provide a template for how to make a results repository, with optional travis tests.

Thoughts?

**Comment by Scottmar93** [comment]
I think this is a really good idea. Make a lot sense to separate what is the core repo from individuals results and leave maintenance to results to individuals
