### ISSUE TITLE
Add simulation class 

### ISSUE THREAD

**Issue by Scottmar93** [pybamm-team/PyBaMM#688]
**Summary**
Create a simulation class which wraps model, discretization, parameters etc. 

**Motivation** 
Can be extended to allow linking of the experiment, model, discretization, and solver together and allow each to reference each other. Also simplifies the pybamm user interface so that users only need to see what the actually are setting

**Comment by tinosulzer** [comment]
See #39 and the branch `issue-39-simulation-class` - happy for you to take over on this though :)

**Comment by Scottmar93** [comment]
Ah nice thought you had deleted the branch so just made a quick mock up of what the class would look like. Will take a look at #39 as well.  Doesn't seem like there is too much to do but might be nice to have some reset type features that would allow you to undiscretize your model etc.

**Comment by tinosulzer** [comment]
Sounds good, note you can do `disc.process_model(model, inplace=False)` to leave the original model un-discretised
