### ISSUE TITLE
Add ability to automatically store the previous simulation within simulation object

### ISSUE THREAD

**Issue by Scottmar93** [pybamm-team/PyBaMM#696]
**Summary**
Use deepcopy to create a copy of a previous simulation object so that if someone accidentally resets the simulation they can recover the discretization and solution.

**Comment by tinosulzer** [comment]
is this done?

**Comment by rtimms** [comment]
I think we can close this? You can't do `simulation.reset` anymore, so I don't think this functionality is needed.

**Comment by tinosulzer** [comment]
Yeah happy to close this
