### ISSUE TITLE
helper function for changing BCs

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/PyBaMM#712]
It would be nice to be easily update boundary conditions after loading up a model.

It might also be easier to navigate the model boundary conditions if the keys of the dict were the variable name string rather than the object itself, as it is currently hard to quickly manually edit BCs. I', not sure if this causes problems elsewhere during discretisation though. In any case a helper function would be useful.

**Comment by Scottmar93** [comment]
Helper function could take in a variable name string, look through the variables to see what the symbol is and then find the corresponding boundary condition. This avoids needing to change the structure of boundary conditions elsewhere

**Comment by tinosulzer** [comment]
Isn't it just this?
```python3
c_e = model.variables["Electrolyte concentration"]
model.boundary_conditions[c_e] = {
    "left": (pybamm.Scalar(1), "Neumann"),
    "right": (pybamm.Scalar(-1), "Neumann"),
}
```
Not sure this warrants a helper function?

**Comment by rtimms** [comment]
Agreed, closing.
