### ISSUE TITLE
Print equations nicely and without expanding tree

### ISSUE THREAD

**Issue by TomTranter** [pybamm-team/PyBaMM#722]
**Summary**
Rendering the expression tree is a giant mess and impossible to decipher. It would be great to be able to see what the equations are for each function/variable in one line without rendering the whole tree underneath. Also rendering them in Latex would be good. Sympy is able to render equations in Latex very nicely

**Comment by TomTranter** [comment]
https://docs.sympy.org/latest/tutorial/printing.html

**Comment by tinosulzer** [comment]
The main challenge here is with parameters that are combinations of other parameters: how do we know what to call them if we are not expanding them?

A nice workaround is to overload the `__setattr__` method in `LithiumIonParameters` (more  specifically, in a base `Parameters` class) as follows:
```python3
def __setattr__(self, name, value):
        if isinstance(value, pybamm.Symbol):
            value.name_for_printing = name
        super().__setattr__(name, value)
```

Then anywhere else in the class if we do something like
```python3
self.L_x = self.L_n + self.L_s + self.L_p
```
the rhs symbol (an `Addition`) will be given a print name of `L_x`. 

Similarly we can define print names for all kinds of symbols, and then we just need to convert to sympy for printing

**Comment by tinosulzer** [comment]
https://github.com/connorferster/handcalcs
