### ISSUE TITLE
Add ability to solve on tabs 

### ISSUE THREAD

**Issue by Scottmar93** [pybamm-team/PyBaMM#733]
**Summary**
Add a "tabs" submodel to account for solving the electrical problem on the tabs or extend the current collector models to include the tabs.

**Comment by tinosulzer** [comment]
Can this be closed? @rtimms @Scottmar93

**Comment by rtimms** [comment]
Yeah, I don't think we have any plans to add this. Can open a new issue later if anyone is interested.
