### ISSUE TITLE
Implement Doyle-Fuller-Newman (DFN) Model

### ISSUE THREAD

**Issue by Scottmar93** [pybamm-team/PyBaMM#74]
**Update**
Scope of this issue has been extended to also implementing the SPM and SPMe by calling submodels since the forms of the models are so similar. 
 
**Summary**
We need to implement a `DFN` class. To do this, we need: 
- A `butler_volmer` function that creates a `G` given in terms of the other parameters and variables in the model
- An `StefanMaxwellCurrent` class which implements the conservation of current equations in the electrolyte as well as the McInnes equation for phi_e. 
- A `StandardElectrode` class which implements current conservation and Ohm's law in the macroscale electrode 
- A `DFN` class which:
   - makes a `G` using the `butler_volmer` function
   - creates the electrolyte model by calling `StefanMaxwellDiffusion` and `StefanMaxwellCurrent`
   -  creates the macroscale electrode model by calling `StandardElectrode`.
   - create negative and positive electrode particles using `StandardParticle`. It must be somehow indicated that a particle must be inserted in every cell of the discretised model. 
- Within `DFN` we should also add the following useful variables: 
  - current 
  - overpotentials 
  - the terminal voltage

**Comment by tinosulzer** [comment]
Would you do this using the capacitance + rearranging trick, or solve the DAE system?

**Comment by Scottmar93** [comment]
> Would you do this using the capacitance + rearranging trick, or solve the DAE system?

I think it would be good to implement the DAE system and tackle the various problems that come along with it but we should eventually have both implementations so that they can be compared. If they both produce the same results and one is particularly faster then we can choose that to be the default DFN model. 

We should have the DAE version because it is easier to add degradation mechanisms such as side reactions and also acts as a good test model to try out DAE solvers which we will require when we go to 2D and 3D.
