### ISSUE TITLE
DAE solver for non-smooth currents

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#759]
Fix (at least one of the) DAE solvers to work when the input current is not smooth.

Hacky approach is to do step-by-step and match up discontinuities with steps, or try stepping the differential and algebraic equations separately

**Comment by martinjrobins** [comment]
could we augment `model.events` to take 2 types of events: "termination" and "discontinuity". The solver would then make sure to integrate up to just before a discontinuity, and restart integration just after the discontinuity.

**Comment by tinosulzer** [comment]
Good idea, so would the discontinuities be a list of variables for which to look out for discontinuities? Or do we analyse the input current (a parameter) before solving to identify discontinuities and then tell the model/solver about them before solving?

**Comment by martinjrobins** [comment]
I'm thinking that the user would manually specify where the discontinuities occur in time, based on the parameters of the model. Therefore discontinuities would be an expression that evaluates to the time when the discontinuity takes place. 

So, given a model that has parameter `a` and which exhibits a discontinuity at `2*a`, the user would set `model.events = [(pybamm.DISCONTINUITY, 2*a)]`

Then it would be easy for the solver to get the list of where discontinuities occur in time, and make sure that the integration is restarted at each discontinuous time-point

**Comment by martinjrobins** [comment]
Each event now needs 3 pieces of info, its name, expression and type (DISCONTINUITY or TERMINATION). I think this needs a separate class to encapsulate this (and provide some documentation). Implemented this as `Event`, so that to create some events you might do something like this:

```python
        model.events = [
            pybamm.Event("var1 = 1.5", pybamm.min(var1 - 1.5)),
            pybamm.Event("var2 = 2.5", pybamm.min(var2 - 2.5)),
            pybamm.Event("nonsmooth rate",
                         pybamm.Scalar(2.5),
                         pybamm.EventType.DISCONTINUITY
                         )
        ]
```
