### ISSUE TITLE
Simplifying solver interface

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#784]
It should be possible to merge 

- `base_solver`, `ode_solver` and `dae_solver` into a single base class
- `scikits_ode_solver` and `scikits_dae_solver` into a single class

Do you think this would simplify the interface @rtimms ?

**Comment by rtimms** [comment]
yeah I think that would be good. could we also remove `compute_solution` and call `integrate` directly from `solve` and `step`? `compute_solution` saves rewriting the little integrate, get termination reason block of code in both `step` and `solve`, but it wouldn't be a massive bit of repetition and would probably be easier to follow for new users. (I think I introduced `compute_solution`, but I don't like it now haha)

I think the only solver with a drastically different interface is casadi, and we already overwrite some methods there anyway.

**Comment by tinosulzer** [comment]
Ok, that sounds good - no worries, `compute_solution` seemed like a good idea at the time haha
