### ISSUE TITLE
Jupyterhub launch email

### ISSUE THREAD

**Issue by jedgedrudd** [pybamm-team/PyBaMM#799]
**Summary**
Draw up an email to announce the launch of our Jupyterhub and give starter information about how to use it.

 **Motivation**
Since the VM is now running, we may as well make people aware that the service is there. (addendum: please turn off the VM until the email is sent? :) 

**Additional context**

**Comment by martinjrobins** [comment]
VM is currently off (I turned it off on the 20th Jan)

**Comment by jedgedrudd** [comment]
VM can now be turned back on - azure account is on a monthly subscription

**Comment by jedgedrudd** [comment]
Can we now send out a launch email, or is it best to wait for the workshop?

**Comment by tinosulzer** [comment]
I don't think we need jupyter hub now that google colab is working

**Comment by tinosulzer** [comment]
Closing this issue. Have we turned off the jupyter hub?
