### ISSUE TITLE
After install and run-tests, I have following errors. 

### ISSUE THREAD

**Issue by gyouhoc** [pybamm-team/PyBaMM#803]
**Describe the bug**

I have following error after the run-tests. 

![Capture](https://user-images.githubusercontent.com/60714526/73880590-b7584e00-482c-11ea-80b2-165ab7345a36.PNG)

**To Reproduce**
Steps to reproduce the behaviour:

run-tests

**Expected behaviour**
no error

**Screenshots**
Provided

**Additional context**
Can I move on working with the simulator with this error?

**Comment by tinosulzer** [comment]
I think this is because you're missing graphviz, try on linux
```
sudo apt-get install graphviz
```
or on mac
```
brew install graphviz
```

**Comment by tinosulzer** [comment]
This test isn't that important though, and won't affect running the simulator

**Comment by tinosulzer** [comment]
hi @gyouhoc , did you manage to get this working?

**Comment by gyouhoc** [comment]
I haven't installed graphviz yet. I will let you know after I install it. 
However, this error doesn't influence on the PyBaMM simulation.
I am working on the tutorials now.

**Comment by gyouhoc** [comment]
I installed graphviz 0.13.2 but I still have a same error.

**Comment by tinosulzer** [comment]
I have opened a pull request to make graphviz an optional dependency. In the meantime, what OS are you on? And can you try with a more recent version of graphviz (e.g. 2.42.2)?

**Comment by gyouhoc** [comment]
I am using Windows 10. 
I will check the most recent version of graphviz.
