### ISSUE TITLE
Cheatsheet for the workshop

### ISSUE THREAD

**Issue by ferranbrosa** [pybamm-team/PyBaMM#822]
**Summary**
I think it would be very helpful for the workshop to provide a PyBaMM cheatsheet with the basic commands and syntax, so people don't have to spend too much time looking it up through the examples.

 **Motivation**
Ideas on what to include:

- How to list all the processed variables `list(model.variables.keys())`
- How to run a simulation and what are the optional parameters to pass.
- The syntax of the experiments.

**Additional context**

**Comment by Scottmar93** [comment]
Add to the documentation (also have a print to pdf option)

**Comment by rtimms** [comment]
it might be useful to think about making some feedback forms so we get useful and constructive feedback about things to improve. if we can be specific and brief we might get better responses

**Comment by rtimms** [comment]
any input for the cheat sheet welcome! then we can put something together over the next 2 weeks

**Comment by ferranbrosa** [comment]
I think that, as a starting point for the upcoming workshop, we could go with how to run a simulation with everything as default, and then how to change every single aspect (in terms of what to pass and so on). Also, how to get the list of variables of the model and how to use QuickPlot.

Later on we can think of a cheatsheet with more advanced features like how to build new models.

**Comment by tinosulzer** [comment]
Also how to define an experiment class, some of the parameters you might want to update more regularly (current functions, initial conditions), some of the more common variable names

**Comment by tinosulzer** [comment]
Useful links for anyone wanting to contribute further (CONTRIBUTING.md, online docs)

**Comment by rtimms** [comment]
I've started a CHEATSHEET.md. Please add/remove/edit/reformat as you wish

**Comment by tinosulzer** [comment]
This is the collaborative markdown thing I was talking about, might make it easier to write collaboratively: https://hackmd.io/@tinosulzer/HyeLXOUH8/edit

**Comment by rtimms** [comment]
ah thanks! I had forgotten you'd mentioned that

**Comment by tinosulzer** [comment]
Closing this; to be edited as part of the website
