### ISSUE TITLE
Add SEI long term growth models to PyBaMM

### ISSUE THREAD

**Issue by Scottmar93** [pybamm-team/PyBaMM#834]
Add the following SEI long term growth models: 
- [ ] Reaction limited
- [ ] Solvent-diffusion limited
- [ ] Electron-migration limited
- [ ] Lithium-interstitial-migration limited

**Comment by tinosulzer** [comment]
feel free to untangle the interface submodels as part of this 😅

**Comment by tinosulzer** [comment]
@Scottmar93 I'll try to get this cleaned up and merged (I have merged in #933 )
