### ISSUE TITLE
Add Li-ion side reactions for thermal runaway modeling

### ISSUE THREAD

**Issue by viviantran27** [pybamm-team/PyBaMM#928]
**Summary**
The single-cell thermal runaway model that will be implemented is from the reference listed below. It includes a lumped thermal model, an OCV-R model for short-circuit ohmic heating, and a side reaction model for exothermic reaction heating. The first two can already be implemented in Pybamm, but the side reactions will need to be included. This involves adding the SEI, anode, and cathode decompositions. The model is from the following reference:

Cai, Ting, Anna G. Stefanopoulou, and Jason B. Siegel. "Early Detection for Li-Ion Batteries Thermal Runaway Based on Gas Sensing." ECS Transactions 89.1 (2019): 85-97.

**Comment by kratman** [comment]
@viviantran27 Is this still relevant or can it be closed.

It looks like some work was done on this ticket since there are tagged commits from @valentinsulzer
