### ISSUE TITLE
Setting SOC before simulation

### ISSUE THREAD

**Issue by gyouhoc** [pybamm-team/PyBaMM#946]
**Summary**
 is there a convenient way to adjust SOC before the simulation? 

 **Motivation**
Setting SOC

**Comment by tinosulzer** [comment]
Not yet, since this is dependent on how you define "SOC". 
At the moment, you have to change the parameters "Initial concentration in negative electrode [mol.m-3]" and "Initial concentration in positive electrode [mol.m-3]"

**Comment by gyouhoc** [comment]
thax for the info
