### ISSUE TITLE
Rest preceding discharge step causes DAE solver bug (Chen 2020)

### ISSUE THREAD

**Issue by Kieran-ORegan** [pybamm-team/PyBaMM#955]
Including a rest before the following discharge step does not allow successful simulation due to a bug with 'DAE solver'.
 
"Newton/Linesearch algorithm failed to converge"

experiment = pybamm.Experiment(
                     ["Rest for 5 minutes",
                         "Discharge at 0.5C until 2.5 V",
            "Rest for 120 minutes"],
           period="10 seconds",
)
model = pybamm.lithium_ion.DFN()
chemistry = pybamm.parameter_sets.Chen2020
parameter_values = pybamm.ParameterValues(chemistry=chemistry)
parameter_values["Negative electrode diffusivity [m2.s-1]"] = 1.3e-14
sim = pybamm.Simulation(model, parameter_values=parameter_values, experiment=experiment)
sim.solve()
 
![image](https://user-images.githubusercontent.com/63075253/79118639-57c77300-7d86-11ea-87f1-6fcec623794a.png)

**Comment by rtimms** [comment]
looks like this will be fixed by PR #951

**Comment by tinosulzer** [comment]
Yep this should be fixed now
