### ISSUE TITLE
exchange current density

### ISSUE THREAD

**Issue by gyouhoc** [pybamm-team/PyBaMM#966]
Hi, 

As I review the list of the input parameters for both anode and cathode, I realize that there is no parameter for the exchange current density ,io, for both electrodes. Would you direct me how to setup this number for the simulation? 

thank you

**Comment by tinosulzer** [comment]
The relevant parameter is "reaction rate", then the exchange-current density is hard-coded in as 
```python3
i0 = reaction_rate * (
                c_e ** (1 / 2) * c_s_surf ** (1 / 2) * (1 - c_s_surf) ** (1 / 2)
            )
```
It would probably be more standard to have an exchange-current density parameter though (which takes in c_s_surf and c_e), right @rtimms @Scottmar93 @ferranbrosa @TomTranter ?

**Comment by rtimms** [comment]
will need to take `c_s_max` etc as it will need to be defined in dimensional form to be consistent with other parameters
