### ISSUE TITLE
plot pybamm arrays

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/PyBaMM#992]
It would be nice to automate the plotting of `pybamm.Array` objects for doing things like the example below. I think just 1D is fine for now. More complicated will usually be of solution entries, so handled via `Quickplot`, but it would be nice to easily plot parameters that are functions. I guess 2D is useful since this depends on T and sto. Thoughts?

Edit: I know calling `.entries` isn't a huge deal, but think this would be easy to implement and avoid needing to import matplotlib 

```
import pybamm
import numpy as np
import matplotlib.pyplot as plt

param = pybamm.ParameterValues(chemistry=pybamm.parameter_sets.Ecker2015)
D_fun = param["Negative electrode diffusivity [m2.s-1]"]
x = pybamm.Array(np.linspace(0,1,100))
D = D_fun(x, 300)
plt.plot(x.entries,D.entries) 
```

**Comment by tinosulzer** [comment]
do you mean something to replace the last line with `pybamm.plot(x,D)`?

**Comment by rtimms** [comment]
yeah, sorry I wasn't very clear

**Comment by tinosulzer** [comment]
Yeah that sounds like a good feature. And you could do `pybamm.plot([x,T], D(x,T))` for 2D.
